## Evaluating Hyperparameters - Deep CNN

#### This script follows the structure below

## 1.Importing libraries
## 2.Data Wrangling
## 3.Reshape Data for the CNN Algorithm
## 4.Spliting the Data
## 5. Bayesian Hyperparameter Optimization
## 6. Running CNN with Optimized Search Parameters
## 7. Creating Confusion Matrix

# 1.Importing libraries

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import time
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.multiclass import type_of_target
import tensorflow as tf
from numpy import unique
from numpy import reshape
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score
from tensorflow.keras.layers import Input, Conv1D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D, SimpleRNN
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from scikeras.wrappers import KerasClassifier  # Use scikeras for scikit-learn compatibility
from math import floor
from bayes_opt import BayesianOptimization
from tensorflow.keras.layers import LeakyReLU  # Use tensorflow.keras instead of keras
LeakyReLU = LeakyReLU(negative_slope=0.1)
import warnings

In [4]:
# Creating a path for importing the climate data set

path = r'/Users/daniel/Desktop/Ordner/Data Analyst/Data Analytics Course/Data Specialization/Data Sets'

In [5]:
# Import the data set

df_weather = pd.read_csv(os.path.join(path, 'weather_clean.csv'),index_col = False)

df_answer = pd.read_csv(os.path.join(path, 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'),index_col = False)

In [6]:
df_weather.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [7]:
df_answer.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# 2.Data Wrangling

In [9]:
# Drop DATE column from weather data set

df_weather = df_weather.drop(['DATE', 'MONTH'], axis=1)

In [10]:
df_weather.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [19]:
# Drop DATE column from answers

df_answer.drop(columns = 'DATE', inplace = True)

In [21]:
df_answer.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [23]:
df_weather.shape

(22950, 135)

In [25]:
df_answer.shape

(22950, 15)

# 3. Reshaping for Modeling

In [30]:
# Turn X and answers from a df to arrays

X = np.array(df_weather)
y = np.array(df_answer)

In [32]:
X = X.reshape(-1,15,9)

In [34]:
X.shape

(22950, 15, 9)

In [36]:
# Use argmax to transform y

y =  np.argmax(y, axis = 1)
y

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
y.shape

(22950,)

In [40]:
# Check y layout

from sklearn.utils.multiclass import type_of_target
type_of_target(y)

'multiclass'

# 4. Data Split

In [43]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [45]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212,)
(5738, 15, 9) (5738,)

# 5. Bayesian Hyperparameter Optimization

In [48]:
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15 # Number of weather stations
# Make scorer accuracy
score_acc = make_scorer(accuracy_score)

In [50]:
# Create function

def bay_area(neurons, activation, kernel, optimizer, learning_rate, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','SGD']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]  #optimizerD[optimizerL[round(optimizer)]]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def cnn_model():
        model = Sequential()
        model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(timesteps, input_dim)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(MaxPooling1D())
        model.add(Flatten())
        model.add(Dense(n_classes, activation='softmax')) #sigmoid softmax
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=cnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
    score = cross_val_score(nn, X_train, y_train, scoring=score_acc, cv=kfold, params={'callbacks':[es]}).mean()
    return score

In [54]:
start = time.time()
params ={
    'neurons': (10, 100),
    'kernel': (1, 3),
    'activation':(0, 9), 
    'optimizer':(0,7),
    'learning_rate':(0.01, 1),
    'batch_size': (200, 1000), 
    'epochs':(20, 50),
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}
# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=42)
nn_opt.maximize(init_points=15, n_iter=4) 
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   | activa... | batch_... |  dropout  | dropou... |  epochs   |  kernel   |  layers1  |  layers2  | learni... |  neurons  | normal... | optimizer |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Epoch 1/25

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 1s - 63ms/step - accuracy: 0.6266 - loss: 2.6937
Epoch 2/25
15/15 - 1s - 36ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 1s - 36ms/step - accuracy: 0.6440 - loss: 2.6970
Epoch 4/25
15/15 - 1s - 35ms/step - accuracy: 0.6440 - loss: 2.6942
Epoch 5/25
15/15 - 1s - 36ms/step - accuracy: 0.6440 - loss: 2.6917
Epoch 6/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6894
Epoch 7/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6873
Epoch 8/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6853
Epoch 9/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6834
Epoch 10/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6817
Epoch 11/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6800
Epoch 12/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6783
Epoch 13/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6768
Epoch 14/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6753
Epoch 15/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6738
Epoch 16/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6723
Epoch 17/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6709
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6695
Epoch 19/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6681
Epoch 20/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6667
Epoch 21/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6653
Epoch 22/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6639
Epoch 23/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6625
Epoch 24/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6611
Epoch 25/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6597
4/4 - 0s - 25ms/step
Epoch 1/25

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 1s - 65ms/step - accuracy: 0.6028 - loss: 2.7093
Epoch 2/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6971
Epoch 4/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6943
Epoch 5/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6918
Epoch 6/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6895
Epoch 7/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6874
Epoch 8/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6854
Epoch 9/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6836
Epoch 10/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6819
Epoch 11/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6802
Epoch 12/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6786
Epoch 13/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6770
Epoch 14/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6755
Epoch 15/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6741
Epoch 16/25
15/15 - 1s - 39ms/step - accuracy: 0.6440 - loss: 2.6727
Epoch 17/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6713
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6699
Epoch 19/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6686
Epoch 20/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6673
Epoch 21/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6660
Epoch 22/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6647
Epoch 23/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6635
Epoch 24/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6622
Epoch 25/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6609
4/4 - 0s - 25ms/step
Epoch 1/25

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 1s - 65ms/step - accuracy: 0.6362 - loss: 2.6829
Epoch 2/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.7003
Epoch 3/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6969
Epoch 4/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6940
Epoch 5/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6914
Epoch 6/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6891
Epoch 7/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6869
Epoch 8/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6849
Epoch 9/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6830
Epoch 10/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6811
Epoch 11/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6794
Epoch 12/25
15/15 - 1s - 39ms/step - accuracy: 0.6439 - loss: 2.6776
Epoch 13/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6760
Epoch 14/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6743
Epoch 15/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6727
Epoch 16/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6711
Epoch 17/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6695
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6680
Epoch 19/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6664
Epoch 20/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6648
Epoch 21/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6632
Epoch 22/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6616
Epoch 23/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6600
Epoch 24/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6583
Epoch 25/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6566
4/4 - 0s - 24ms/step
Epoch 1/25

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 1s - 65ms/step - accuracy: 0.6046 - loss: 2.7045
Epoch 2/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.7004
Epoch 3/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6970
Epoch 4/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6942
Epoch 5/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6917
Epoch 6/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6894
Epoch 7/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6873
Epoch 8/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6853
Epoch 9/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6835
Epoch 10/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6817
Epoch 11/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6800
Epoch 12/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6784
Epoch 13/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6768
Epoch 14/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6753
Epoch 15/25
15/15 - 1s - 38ms/step - accuracy: 0.6440 - loss: 2.6738
Epoch 16/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6723
Epoch 17/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6709
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6695
Epoch 19/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6681
Epoch 20/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6667
Epoch 21/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6653
Epoch 22/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6639
Epoch 23/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6625
Epoch 24/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6611
Epoch 25/25
15/15 - 1s - 37ms/step - accuracy: 0.6440 - loss: 2.6597
4/4 - 0s - 25ms/step
Epoch 1/25

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

15/15 - 1s - 64ms/step - accuracy: 0.6006 - loss: 2.7177
Epoch 2/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.7004
Epoch 3/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6971
Epoch 4/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6943
Epoch 5/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6918
Epoch 6/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6895
Epoch 7/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6874
Epoch 8/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6854
Epoch 9/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6836
Epoch 10/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6818
Epoch 11/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6801
Epoch 12/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6785
Epoch 13/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6769
Epoch 14/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6754
Epoch 15/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6739
Epoch 16/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6725
Epoch 17/25
15/15 - 1s - 39ms/step - accuracy: 0.6439 - loss: 2.6711
Epoch 18/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6697
Epoch 19/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6683
Epoch 20/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6670
Epoch 21/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6656
Epoch 22/25
15/15 - 1s - 38ms/step - accuracy: 0.6439 - loss: 2.6643
Epoch 23/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6629
Epoch 24/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6616
Epoch 25/25
15/15 - 1s - 37ms/step - accuracy: 0.6439 - loss: 2.6602
4/4 - 0s - 25ms/step
| 1         | 0.644     | 3.371     | 960.6     | 0.732     | 0.1796    | 24.68     | 1.312     | 1.116     | 2.732     | 0.6051    | 73.73     | 0.02058   | 6.789     |
Epoch 1/29

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 0s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 5ms/step
Epoch 1/29

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 0s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 5ms/step
Epoch 1/29

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 0s - 12ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 28/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 29/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
10/10 - 0s - 5ms/step
Epoch 1/29

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 0s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 28/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
Epoch 29/29
38/38 - 0s - 3ms/step - accuracy: 0.6440 - loss: nan
10/10 - 0s - 5ms/step
Epoch 1/29

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

38/38 - 0s - 12ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/29
38/38 - 0s - 2ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 28/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
Epoch 29/29
38/38 - 0s - 3ms/step - accuracy: 0.6439 - loss: nan
10/10 - 0s - 5ms/step
| 2         | 0.644     | 7.492     | 369.9     | 0.1818    | 0.05502   | 29.13     | 2.05      | 1.864     | 1.582     | 0.6157    | 22.55     | 0.2921    | 2.565     |
Epoch 1/38

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 71ms/step - accuracy: 0.5258 - loss: 1.5948
Epoch 2/38
17/17 - 1s - 40ms/step - accuracy: 0.6918 - loss: 0.9056
Epoch 3/38
17/17 - 1s - 41ms/step - accuracy: 0.7245 - loss: 0.8058
Epoch 4/38
17/17 - 1s - 41ms/step - accuracy: 0.7475 - loss: 0.7484
Epoch 5/38
17/17 - 1s - 41ms/step - accuracy: 0.7648 - loss: 0.7034
Epoch 6/38
17/17 - 1s - 41ms/step - accuracy: 0.7789 - loss: 0.6659
Epoch 7/38
17/17 - 1s - 41ms/step - accuracy: 0.7856 - loss: 0.6318
Epoch 8/38
17/17 - 1s - 41ms/step - accuracy: 0.7986 - loss: 0.5998
Epoch 9/38
17/17 - 1s - 42ms/step - accuracy: 0.8070 - loss: 0.5698
Epoch 10/38
17/17 - 1s - 42ms/step - accuracy: 0.8144 - loss: 0.5389
Epoch 11/38
17/17 - 1s - 41ms/step - accuracy: 0.8221 - loss: 0.5112
Epoch 12/38
17/17 - 1s - 42ms/step - accuracy: 0.8339 - loss: 0.4840
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8415 - loss: 0.4570
Epoch 14/38
17/17 - 1s - 42ms/step - accuracy: 0.8496 - loss: 0.4374
Epoch 15/38
17/17 - 1s - 41ms/step - accuracy: 0.8607 - loss: 0.4112
Epoch 16/38
17/17 - 1s - 41ms/step - accuracy: 0.8645 - loss: 0.3949
Epoch 17/38
17/17 - 1s - 41ms/step - accuracy: 0.8760 - loss: 0.3729
Epoch 18/38
17/17 - 1s - 41ms/step - accuracy: 0.8802 - loss: 0.3555
Epoch 19/38
17/17 - 1s - 41ms/step - accuracy: 0.8820 - loss: 0.3477
Epoch 20/38
17/17 - 1s - 41ms/step - accuracy: 0.8904 - loss: 0.3305
Epoch 21/38
17/17 - 1s - 41ms/step - accuracy: 0.8918 - loss: 0.3192
Epoch 22/38
17/17 - 1s - 41ms/step - accuracy: 0.8908 - loss: 0.3218
Epoch 23/38
17/17 - 1s - 41ms/step - accuracy: 0.9012 - loss: 0.2936
Epoch 24/38
17/17 - 1s - 41ms/step - accuracy: 0.9030 - loss: 0.2854
Epoch 25/38
17/17 - 1s - 41ms/step - accuracy: 0.9025 - loss: 0.2875
Epoch 26/38
17/17 - 1s - 41ms/step - accuracy: 0.9067 - loss: 0.2718
Epoch 27/38
17/17 - 1s - 41ms/step - accuracy: 0.9097 - loss: 0.2679
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9137 - loss: 0.2595
Epoch 29/38
17/17 - 1s - 41ms/step - accuracy: 0.9172 - loss: 0.2493
Epoch 30/38
17/17 - 1s - 41ms/step - accuracy: 0.9133 - loss: 0.2496
Epoch 31/38
17/17 - 1s - 41ms/step - accuracy: 0.9216 - loss: 0.2376
Epoch 32/38
17/17 - 1s - 41ms/step - accuracy: 0.9227 - loss: 0.2316
Epoch 33/38
17/17 - 1s - 41ms/step - accuracy: 0.9280 - loss: 0.2227
Epoch 34/38
17/17 - 1s - 41ms/step - accuracy: 0.9261 - loss: 0.2217
Epoch 35/38
17/17 - 1s - 41ms/step - accuracy: 0.9322 - loss: 0.2088
Epoch 36/38
17/17 - 1s - 42ms/step - accuracy: 0.9322 - loss: 0.2053
Epoch 37/38
17/17 - 1s - 42ms/step - accuracy: 0.9368 - loss: 0.1968
Epoch 38/38
17/17 - 1s - 41ms/step - accuracy: 0.9354 - loss: 0.1978
5/5 - 0s - 23ms/step
Epoch 1/38

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 2s - 97ms/step - accuracy: 0.5532 - loss: 1.4953
Epoch 2/38
17/17 - 1s - 41ms/step - accuracy: 0.6820 - loss: 0.9091
Epoch 3/38
17/17 - 1s - 41ms/step - accuracy: 0.7168 - loss: 0.8119
Epoch 4/38
17/17 - 1s - 40ms/step - accuracy: 0.7440 - loss: 0.7497
Epoch 5/38
17/17 - 1s - 41ms/step - accuracy: 0.7631 - loss: 0.7014
Epoch 6/38
17/17 - 1s - 41ms/step - accuracy: 0.7750 - loss: 0.6625
Epoch 7/38
17/17 - 1s - 41ms/step - accuracy: 0.7848 - loss: 0.6257
Epoch 8/38
17/17 - 1s - 42ms/step - accuracy: 0.7942 - loss: 0.5914
Epoch 9/38
17/17 - 1s - 41ms/step - accuracy: 0.8033 - loss: 0.5575
Epoch 10/38
17/17 - 1s - 41ms/step - accuracy: 0.8133 - loss: 0.5263
Epoch 11/38
17/17 - 1s - 41ms/step - accuracy: 0.8239 - loss: 0.4985
Epoch 12/38
17/17 - 1s - 41ms/step - accuracy: 0.8310 - loss: 0.4719
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8414 - loss: 0.4474
Epoch 14/38
17/17 - 1s - 41ms/step - accuracy: 0.8464 - loss: 0.4251
Epoch 15/38
17/17 - 1s - 41ms/step - accuracy: 0.8570 - loss: 0.4036
Epoch 16/38
17/17 - 1s - 42ms/step - accuracy: 0.8639 - loss: 0.3864
Epoch 17/38
17/17 - 1s - 41ms/step - accuracy: 0.8693 - loss: 0.3746
Epoch 18/38
17/17 - 1s - 41ms/step - accuracy: 0.8747 - loss: 0.3576
Epoch 19/38
17/17 - 1s - 42ms/step - accuracy: 0.8824 - loss: 0.3404
Epoch 20/38
17/17 - 1s - 42ms/step - accuracy: 0.8839 - loss: 0.3312
Epoch 21/38
17/17 - 1s - 42ms/step - accuracy: 0.8906 - loss: 0.3151
Epoch 22/38
17/17 - 1s - 42ms/step - accuracy: 0.8952 - loss: 0.3070
Epoch 23/38
17/17 - 1s - 41ms/step - accuracy: 0.8951 - loss: 0.3042
Epoch 24/38
17/17 - 1s - 42ms/step - accuracy: 0.9017 - loss: 0.2875
Epoch 25/38
17/17 - 1s - 41ms/step - accuracy: 0.9045 - loss: 0.2824
Epoch 26/38
17/17 - 1s - 41ms/step - accuracy: 0.9067 - loss: 0.2711
Epoch 27/38
17/17 - 1s - 41ms/step - accuracy: 0.9141 - loss: 0.2596
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9142 - loss: 0.2557
Epoch 29/38
17/17 - 1s - 41ms/step - accuracy: 0.9150 - loss: 0.2508
Epoch 30/38
17/17 - 1s - 41ms/step - accuracy: 0.9155 - loss: 0.2509
Epoch 31/38
17/17 - 1s - 42ms/step - accuracy: 0.9208 - loss: 0.2362
Epoch 32/38
17/17 - 1s - 41ms/step - accuracy: 0.9196 - loss: 0.2398
Epoch 33/38
17/17 - 1s - 42ms/step - accuracy: 0.9229 - loss: 0.2261
Epoch 34/38
17/17 - 1s - 41ms/step - accuracy: 0.9217 - loss: 0.2322
Epoch 35/38
17/17 - 1s - 41ms/step - accuracy: 0.9274 - loss: 0.2196
Epoch 36/38
17/17 - 1s - 41ms/step - accuracy: 0.9308 - loss: 0.2115
Epoch 37/38
17/17 - 1s - 41ms/step - accuracy: 0.9300 - loss: 0.2093
Epoch 38/38
17/17 - 1s - 41ms/step - accuracy: 0.9317 - loss: 0.2046
5/5 - 0s - 24ms/step
Epoch 1/38

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 71ms/step - accuracy: 0.5585 - loss: 1.5048
Epoch 2/38
17/17 - 1s - 41ms/step - accuracy: 0.6750 - loss: 0.9256
Epoch 3/38
17/17 - 1s - 41ms/step - accuracy: 0.7142 - loss: 0.8318
Epoch 4/38
17/17 - 1s - 41ms/step - accuracy: 0.7386 - loss: 0.7691
Epoch 5/38
17/17 - 1s - 41ms/step - accuracy: 0.7571 - loss: 0.7195
Epoch 6/38
17/17 - 1s - 41ms/step - accuracy: 0.7720 - loss: 0.6725
Epoch 7/38
17/17 - 1s - 41ms/step - accuracy: 0.7836 - loss: 0.6325
Epoch 8/38
17/17 - 1s - 40ms/step - accuracy: 0.7966 - loss: 0.5910
Epoch 9/38
17/17 - 1s - 41ms/step - accuracy: 0.8071 - loss: 0.5567
Epoch 10/38
17/17 - 1s - 41ms/step - accuracy: 0.8174 - loss: 0.5217
Epoch 11/38
17/17 - 1s - 41ms/step - accuracy: 0.8288 - loss: 0.4949
Epoch 12/38
17/17 - 1s - 41ms/step - accuracy: 0.8381 - loss: 0.4636
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8497 - loss: 0.4380
Epoch 14/38
17/17 - 1s - 41ms/step - accuracy: 0.8585 - loss: 0.4128
Epoch 15/38
17/17 - 1s - 41ms/step - accuracy: 0.8677 - loss: 0.3914
Epoch 16/38
17/17 - 1s - 41ms/step - accuracy: 0.8706 - loss: 0.3777
Epoch 17/38
17/17 - 1s - 41ms/step - accuracy: 0.8789 - loss: 0.3551
Epoch 18/38
17/17 - 1s - 41ms/step - accuracy: 0.8860 - loss: 0.3359
Epoch 19/38
17/17 - 1s - 41ms/step - accuracy: 0.8901 - loss: 0.3226
Epoch 20/38
17/17 - 1s - 41ms/step - accuracy: 0.8972 - loss: 0.3081
Epoch 21/38
17/17 - 1s - 41ms/step - accuracy: 0.8969 - loss: 0.3039
Epoch 22/38
17/17 - 1s - 41ms/step - accuracy: 0.9081 - loss: 0.2816
Epoch 23/38
17/17 - 1s - 41ms/step - accuracy: 0.9114 - loss: 0.2736
Epoch 24/38
17/17 - 1s - 41ms/step - accuracy: 0.9076 - loss: 0.2772
Epoch 25/38
17/17 - 1s - 41ms/step - accuracy: 0.9158 - loss: 0.2524
Epoch 26/38
17/17 - 1s - 42ms/step - accuracy: 0.9145 - loss: 0.2583
Epoch 27/38
17/17 - 1s - 42ms/step - accuracy: 0.9175 - loss: 0.2466
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9220 - loss: 0.2345
Epoch 29/38
17/17 - 1s - 41ms/step - accuracy: 0.9227 - loss: 0.2309
Epoch 30/38
17/17 - 1s - 41ms/step - accuracy: 0.9219 - loss: 0.2301
Epoch 31/38
17/17 - 1s - 41ms/step - accuracy: 0.9248 - loss: 0.2237
Epoch 32/38
17/17 - 1s - 42ms/step - accuracy: 0.9269 - loss: 0.2164
Epoch 33/38
17/17 - 1s - 42ms/step - accuracy: 0.9211 - loss: 0.2336
Epoch 34/38
17/17 - 1s - 41ms/step - accuracy: 0.9312 - loss: 0.2053
Epoch 35/38
17/17 - 1s - 42ms/step - accuracy: 0.9309 - loss: 0.2070
Epoch 36/38
17/17 - 1s - 41ms/step - accuracy: 0.9365 - loss: 0.1939
Epoch 37/38
17/17 - 1s - 41ms/step - accuracy: 0.9364 - loss: 0.1916
Epoch 38/38
17/17 - 1s - 41ms/step - accuracy: 0.9351 - loss: 0.1915
5/5 - 0s - 23ms/step
Epoch 1/38

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 70ms/step - accuracy: 0.5528 - loss: 1.4718
Epoch 2/38
17/17 - 1s - 41ms/step - accuracy: 0.6871 - loss: 0.9107
Epoch 3/38
17/17 - 1s - 41ms/step - accuracy: 0.7325 - loss: 0.8000
Epoch 4/38
17/17 - 1s - 40ms/step - accuracy: 0.7606 - loss: 0.7281
Epoch 5/38
17/17 - 1s - 41ms/step - accuracy: 0.7752 - loss: 0.6730
Epoch 6/38
17/17 - 1s - 41ms/step - accuracy: 0.7882 - loss: 0.6275
Epoch 7/38
17/17 - 1s - 42ms/step - accuracy: 0.7993 - loss: 0.5874
Epoch 8/38
17/17 - 1s - 41ms/step - accuracy: 0.8121 - loss: 0.5468
Epoch 9/38
17/17 - 1s - 41ms/step - accuracy: 0.8229 - loss: 0.5132
Epoch 10/38
17/17 - 1s - 42ms/step - accuracy: 0.8321 - loss: 0.4838
Epoch 11/38
17/17 - 1s - 42ms/step - accuracy: 0.8420 - loss: 0.4517
Epoch 12/38
17/17 - 1s - 42ms/step - accuracy: 0.8511 - loss: 0.4267
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8601 - loss: 0.4070
Epoch 14/38
17/17 - 1s - 41ms/step - accuracy: 0.8667 - loss: 0.3859
Epoch 15/38
17/17 - 1s - 41ms/step - accuracy: 0.8702 - loss: 0.3763
Epoch 16/38
17/17 - 1s - 42ms/step - accuracy: 0.8821 - loss: 0.3526
Epoch 17/38
17/17 - 1s - 42ms/step - accuracy: 0.8839 - loss: 0.3391
Epoch 18/38
17/17 - 1s - 42ms/step - accuracy: 0.8869 - loss: 0.3279
Epoch 19/38
17/17 - 1s - 41ms/step - accuracy: 0.8959 - loss: 0.3071
Epoch 20/38
17/17 - 1s - 42ms/step - accuracy: 0.8912 - loss: 0.3153
Epoch 21/38
17/17 - 1s - 41ms/step - accuracy: 0.9020 - loss: 0.2920
Epoch 22/38
17/17 - 1s - 41ms/step - accuracy: 0.9060 - loss: 0.2816
Epoch 23/38
17/17 - 1s - 41ms/step - accuracy: 0.9068 - loss: 0.2765
Epoch 24/38
17/17 - 1s - 41ms/step - accuracy: 0.9004 - loss: 0.2853
Epoch 25/38
17/17 - 1s - 41ms/step - accuracy: 0.9118 - loss: 0.2615
Epoch 26/38
17/17 - 1s - 41ms/step - accuracy: 0.9118 - loss: 0.2642
Epoch 27/38
17/17 - 1s - 41ms/step - accuracy: 0.9173 - loss: 0.2491
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9168 - loss: 0.2507
Epoch 29/38
17/17 - 1s - 41ms/step - accuracy: 0.9155 - loss: 0.2451
Epoch 30/38
17/17 - 1s - 42ms/step - accuracy: 0.9267 - loss: 0.2253
Epoch 31/38
17/17 - 1s - 41ms/step - accuracy: 0.9269 - loss: 0.2242
Epoch 32/38
17/17 - 1s - 41ms/step - accuracy: 0.9291 - loss: 0.2180
Epoch 33/38
17/17 - 1s - 42ms/step - accuracy: 0.9246 - loss: 0.2177
Epoch 34/38
17/17 - 1s - 41ms/step - accuracy: 0.9341 - loss: 0.2035
Epoch 35/38
17/17 - 1s - 41ms/step - accuracy: 0.9305 - loss: 0.2129
Epoch 36/38
17/17 - 1s - 42ms/step - accuracy: 0.9354 - loss: 0.1986
Epoch 37/38
17/17 - 1s - 41ms/step - accuracy: 0.9145 - loss: 0.2540
Epoch 38/38
17/17 - 1s - 41ms/step - accuracy: 0.9309 - loss: 0.2070
5/5 - 0s - 24ms/step
Epoch 1/38

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 72ms/step - accuracy: 0.5715 - loss: 1.4490
Epoch 2/38
17/17 - 1s - 41ms/step - accuracy: 0.6941 - loss: 0.8907
Epoch 3/38
17/17 - 1s - 41ms/step - accuracy: 0.7337 - loss: 0.7923
Epoch 4/38
17/17 - 1s - 40ms/step - accuracy: 0.7522 - loss: 0.7332
Epoch 5/38
17/17 - 1s - 41ms/step - accuracy: 0.7680 - loss: 0.6848
Epoch 6/38
17/17 - 1s - 41ms/step - accuracy: 0.7833 - loss: 0.6416
Epoch 7/38
17/17 - 1s - 41ms/step - accuracy: 0.7941 - loss: 0.6005
Epoch 8/38
17/17 - 1s - 41ms/step - accuracy: 0.8045 - loss: 0.5650
Epoch 9/38
17/17 - 1s - 42ms/step - accuracy: 0.8145 - loss: 0.5322
Epoch 10/38
17/17 - 1s - 41ms/step - accuracy: 0.8232 - loss: 0.5003
Epoch 11/38
17/17 - 1s - 41ms/step - accuracy: 0.8342 - loss: 0.4724
Epoch 12/38
17/17 - 1s - 41ms/step - accuracy: 0.8408 - loss: 0.4462
Epoch 13/38
17/17 - 1s - 41ms/step - accuracy: 0.8521 - loss: 0.4223
Epoch 14/38
17/17 - 1s - 42ms/step - accuracy: 0.8597 - loss: 0.4035
Epoch 15/38
17/17 - 1s - 42ms/step - accuracy: 0.8698 - loss: 0.3763
Epoch 16/38
17/17 - 1s - 41ms/step - accuracy: 0.8744 - loss: 0.3622
Epoch 17/38
17/17 - 1s - 42ms/step - accuracy: 0.8813 - loss: 0.3448
Epoch 18/38
17/17 - 1s - 41ms/step - accuracy: 0.8874 - loss: 0.3298
Epoch 19/38
17/17 - 1s - 42ms/step - accuracy: 0.8898 - loss: 0.3222
Epoch 20/38
17/17 - 1s - 42ms/step - accuracy: 0.8951 - loss: 0.3069
Epoch 21/38
17/17 - 1s - 42ms/step - accuracy: 0.8954 - loss: 0.3054
Epoch 22/38
17/17 - 1s - 42ms/step - accuracy: 0.9001 - loss: 0.2889
Epoch 23/38
17/17 - 1s - 41ms/step - accuracy: 0.9063 - loss: 0.2744
Epoch 24/38
17/17 - 1s - 41ms/step - accuracy: 0.9083 - loss: 0.2675
Epoch 25/38
17/17 - 1s - 41ms/step - accuracy: 0.9058 - loss: 0.2769
Epoch 26/38
17/17 - 1s - 42ms/step - accuracy: 0.9111 - loss: 0.2580
Epoch 27/38
17/17 - 1s - 41ms/step - accuracy: 0.9154 - loss: 0.2455
Epoch 28/38
17/17 - 1s - 41ms/step - accuracy: 0.9139 - loss: 0.2497
Epoch 29/38
17/17 - 1s - 42ms/step - accuracy: 0.9168 - loss: 0.2455
Epoch 30/38
17/17 - 1s - 41ms/step - accuracy: 0.9237 - loss: 0.2269
Epoch 31/38
17/17 - 1s - 42ms/step - accuracy: 0.9194 - loss: 0.2355
Epoch 32/38
17/17 - 1s - 41ms/step - accuracy: 0.9230 - loss: 0.2287
Epoch 33/38
17/17 - 1s - 41ms/step - accuracy: 0.9264 - loss: 0.2166
Epoch 34/38
17/17 - 1s - 42ms/step - accuracy: 0.9306 - loss: 0.2095
Epoch 35/38
17/17 - 1s - 42ms/step - accuracy: 0.9245 - loss: 0.2230
Epoch 36/38
17/17 - 1s - 41ms/step - accuracy: 0.9311 - loss: 0.2018
Epoch 37/38
17/17 - 1s - 42ms/step - accuracy: 0.9350 - loss: 0.1972
Epoch 38/38
17/17 - 1s - 41ms/step - accuracy: 0.9310 - loss: 0.2038
5/5 - 0s - 23ms/step
| 3         | 0.8543    | 4.105     | 828.1     | 0.1997    | 0.1543    | 37.77     | 1.093     | 2.215     | 1.341     | 0.0744    | 95.4      | 0.9656    | 5.659     |
Epoch 1/24

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 17ms/step - accuracy: 0.5365 - loss: 2.3509
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6401 - loss: 1.8991
Epoch 3/24
50/50 - 1s - 11ms/step - accuracy: 0.6430 - loss: 1.6106
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.4424
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.3471
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.2877
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.2481
Epoch 8/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.2202
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1981
Epoch 10/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1807
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1682
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1553
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1456
Epoch 14/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1364
Epoch 15/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1293
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1223
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1161
Epoch 18/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1104
Epoch 19/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1056
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1008
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0961
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0916
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.0886
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0844
13/13 - 0s - 7ms/step
Epoch 1/24

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 16ms/step - accuracy: 0.3999 - loss: 2.3746
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6358 - loss: 1.9103
Epoch 3/24
50/50 - 1s - 11ms/step - accuracy: 0.6404 - loss: 1.6175
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6420 - loss: 1.4389
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6433 - loss: 1.3335
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.2678
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.2240
Epoch 8/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1939
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1720
Epoch 10/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1546
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1411
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1302
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1210
Epoch 14/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1131
Epoch 15/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1061
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.0999
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0945
Epoch 18/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.0902
Epoch 19/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.0857
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6446 - loss: 1.0824
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6435 - loss: 1.0788
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.0755
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6446 - loss: 1.0731
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6446 - loss: 1.0701
13/13 - 0s - 7ms/step
Epoch 1/24

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 16ms/step - accuracy: 0.5113 - loss: 2.2983
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6394 - loss: 1.7510
Epoch 3/24
50/50 - 1s - 11ms/step - accuracy: 0.6424 - loss: 1.4980
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6433 - loss: 1.3731
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.3011
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.2538
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.2197
Epoch 8/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1951
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1745
Epoch 10/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1597
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1462
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1346
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1255
Epoch 14/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1171
Epoch 15/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1092
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.1035
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0972
Epoch 18/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.0918
Epoch 19/24
50/50 - 1s - 11ms/step - accuracy: 0.6442 - loss: 1.0869
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6442 - loss: 1.0823
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6444 - loss: 1.0777
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6454 - loss: 1.0746
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6455 - loss: 1.0712
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6459 - loss: 1.0671
13/13 - 0s - 7ms/step
Epoch 1/24

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 16ms/step - accuracy: 0.4432 - loss: 2.3920
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6329 - loss: 1.8676
Epoch 3/24
50/50 - 1s - 11ms/step - accuracy: 0.6386 - loss: 1.5604
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6405 - loss: 1.3969
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6419 - loss: 1.3085
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6431 - loss: 1.2565
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6435 - loss: 1.2212
Epoch 8/24
50/50 - 1s - 11ms/step - accuracy: 0.6436 - loss: 1.1972
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.1779
Epoch 10/24
50/50 - 1s - 11ms/step - accuracy: 0.6437 - loss: 1.1622
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1498
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1392
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1302
Epoch 14/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1227
Epoch 15/24
50/50 - 1s - 12ms/step - accuracy: 0.6440 - loss: 1.1165
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1100
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.1052
Epoch 18/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0994
Epoch 19/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0950
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0913
Epoch 21/24
50/50 - 1s - 14ms/step - accuracy: 0.6440 - loss: 1.0869
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0833
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0802
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6440 - loss: 1.0770
13/13 - 0s - 7ms/step
Epoch 1/24

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

50/50 - 1s - 16ms/step - accuracy: 0.2674 - loss: 2.5603
Epoch 2/24
50/50 - 1s - 11ms/step - accuracy: 0.6295 - loss: 2.0762
Epoch 3/24
50/50 - 1s - 11ms/step - accuracy: 0.6402 - loss: 1.7330
Epoch 4/24
50/50 - 1s - 11ms/step - accuracy: 0.6426 - loss: 1.5120
Epoch 5/24
50/50 - 1s - 11ms/step - accuracy: 0.6434 - loss: 1.3834
Epoch 6/24
50/50 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.3058
Epoch 7/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.2561
Epoch 8/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.2217
Epoch 9/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1957
Epoch 10/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1768
Epoch 11/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1615
Epoch 12/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1478
Epoch 13/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1388
Epoch 14/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1295
Epoch 15/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1222
Epoch 16/24
50/50 - 1s - 11ms/step - accuracy: 0.6439 - loss: 1.1159
Epoch 17/24
50/50 - 1s - 11ms/step - accuracy: 0.6441 - loss: 1.1097
Epoch 18/24
50/50 - 1s - 11ms/step - accuracy: 0.6442 - loss: 1.1047
Epoch 19/24
50/50 - 1s - 12ms/step - accuracy: 0.6444 - loss: 1.1003
Epoch 20/24
50/50 - 1s - 11ms/step - accuracy: 0.6443 - loss: 1.0961
Epoch 21/24
50/50 - 1s - 11ms/step - accuracy: 0.6442 - loss: 1.0910
Epoch 22/24
50/50 - 1s - 11ms/step - accuracy: 0.6453 - loss: 1.0880
Epoch 23/24
50/50 - 1s - 11ms/step - accuracy: 0.6446 - loss: 1.0840
Epoch 24/24
50/50 - 1s - 11ms/step - accuracy: 0.6452 - loss: 1.0811
13/13 - 0s - 7ms/step
| 4         | 0.6458    | 2.742     | 278.1     | 0.6842    | 0.132     | 23.66     | 1.99      | 1.069     | 2.819     | 0.2662    | 69.63     | 0.3117    | 3.64      |
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 0s - 11ms/step - accuracy: 0.6124 - loss: 1.3223
Epoch 2/48
40/40 - 0s - 4ms/step - accuracy: 0.6876 - loss: 0.9411
Epoch 3/48
40/40 - 0s - 4ms/step - accuracy: 0.7159 - loss: 0.8224
Epoch 4/48
40/40 - 0s - 4ms/step - accuracy: 0.7385 - loss: 0.7558
Epoch 5/48
40/40 - 0s - 4ms/step - accuracy: 0.7452 - loss: 0.7188
Epoch 6/48
40/40 - 0s - 4ms/step - accuracy: 0.7542 - loss: 0.6958
Epoch 7/48
40/40 - 0s - 4ms/step - accuracy: 0.7613 - loss: 0.6707
Epoch 8/48
40/40 - 0s - 4ms/step - accuracy: 0.7673 - loss: 0.6572
Epoch 9/48
40/40 - 0s - 4ms/step - accuracy: 0.7712 - loss: 0.6388
Epoch 10/48
40/40 - 0s - 4ms/step - accuracy: 0.7743 - loss: 0.6290
Epoch 11/48
40/40 - 0s - 4ms/step - accuracy: 0.7772 - loss: 0.6181
Epoch 12/48
40/40 - 0s - 4ms/step - accuracy: 0.7831 - loss: 0.6039
Epoch 13/48
40/40 - 0s - 4ms/step - accuracy: 0.7868 - loss: 0.5960
Epoch 14/48
40/40 - 0s - 4ms/step - accuracy: 0.7916 - loss: 0.5867
Epoch 15/48
40/40 - 0s - 4ms/step - accuracy: 0.7917 - loss: 0.5814
Epoch 16/48
40/40 - 0s - 4ms/step - accuracy: 0.7958 - loss: 0.5665
Epoch 17/48
40/40 - 0s - 4ms/step - accuracy: 0.7995 - loss: 0.5647
Epoch 18/48
40/40 - 0s - 4ms/step - accuracy: 0.7979 - loss: 0.5583
Epoch 19/48
40/40 - 0s - 4ms/step - accuracy: 0.8022 - loss: 0.5486
Epoch 20/48
40/40 - 0s - 4ms/step - accuracy: 0.8059 - loss: 0.5413
Epoch 21/48
40/40 - 0s - 4ms/step - accuracy: 0.8066 - loss: 0.5365
Epoch 22/48
40/40 - 0s - 4ms/step - accuracy: 0.8086 - loss: 0.5263
Epoch 23/48
40/40 - 0s - 4ms/step - accuracy: 0.8131 - loss: 0.5264
Epoch 24/48
40/40 - 0s - 4ms/step - accuracy: 0.8153 - loss: 0.5100
Epoch 25/48
40/40 - 0s - 4ms/step - accuracy: 0.8132 - loss: 0.5137
Epoch 26/48
40/40 - 0s - 4ms/step - accuracy: 0.8165 - loss: 0.5076
Epoch 27/48
40/40 - 0s - 4ms/step - accuracy: 0.8198 - loss: 0.4947
Epoch 28/48
40/40 - 0s - 4ms/step - accuracy: 0.8214 - loss: 0.4966
Epoch 29/48
40/40 - 0s - 4ms/step - accuracy: 0.8261 - loss: 0.4837
Epoch 30/48
40/40 - 0s - 4ms/step - accuracy: 0.8241 - loss: 0.4797
Epoch 31/48
40/40 - 0s - 4ms/step - accuracy: 0.8274 - loss: 0.4770
Epoch 32/48
40/40 - 0s - 4ms/step - accuracy: 0.8285 - loss: 0.4691
Epoch 33/48
40/40 - 0s - 4ms/step - accuracy: 0.8300 - loss: 0.4691
Epoch 34/48
40/40 - 0s - 4ms/step - accuracy: 0.8321 - loss: 0.4577
Epoch 35/48
40/40 - 0s - 4ms/step - accuracy: 0.8353 - loss: 0.4521
Epoch 36/48
40/40 - 0s - 4ms/step - accuracy: 0.8386 - loss: 0.4442
Epoch 37/48
40/40 - 0s - 4ms/step - accuracy: 0.8406 - loss: 0.4434
Epoch 38/48
40/40 - 0s - 4ms/step - accuracy: 0.8408 - loss: 0.4398
Epoch 39/48
40/40 - 0s - 4ms/step - accuracy: 0.8463 - loss: 0.4236
Epoch 40/48
40/40 - 0s - 4ms/step - accuracy: 0.8434 - loss: 0.4314
Epoch 41/48
40/40 - 0s - 4ms/step - accuracy: 0.8487 - loss: 0.4156
Epoch 42/48
40/40 - 0s - 4ms/step - accuracy: 0.8499 - loss: 0.4123
Epoch 43/48
40/40 - 0s - 4ms/step - accuracy: 0.8481 - loss: 0.4110
Epoch 44/48
40/40 - 0s - 4ms/step - accuracy: 0.8533 - loss: 0.4006
Epoch 45/48
40/40 - 0s - 4ms/step - accuracy: 0.8546 - loss: 0.3979
Epoch 46/48
40/40 - 0s - 4ms/step - accuracy: 0.8525 - loss: 0.4047
Epoch 47/48
40/40 - 0s - 4ms/step - accuracy: 0.8578 - loss: 0.3911
Epoch 48/48
40/40 - 0s - 4ms/step - accuracy: 0.8627 - loss: 0.3853
10/10 - 0s - 6ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 0s - 11ms/step - accuracy: 0.5977 - loss: 1.2644
Epoch 2/48
40/40 - 0s - 5ms/step - accuracy: 0.6483 - loss: 1.0275
Epoch 3/48
40/40 - 0s - 4ms/step - accuracy: 0.6799 - loss: 0.9286
Epoch 4/48
40/40 - 0s - 4ms/step - accuracy: 0.7125 - loss: 0.8472
Epoch 5/48
40/40 - 0s - 4ms/step - accuracy: 0.7301 - loss: 0.7995
Epoch 6/48
40/40 - 0s - 4ms/step - accuracy: 0.7406 - loss: 0.7576
Epoch 7/48
40/40 - 0s - 4ms/step - accuracy: 0.7471 - loss: 0.7339
Epoch 8/48
40/40 - 0s - 4ms/step - accuracy: 0.7539 - loss: 0.7058
Epoch 9/48
40/40 - 0s - 4ms/step - accuracy: 0.7575 - loss: 0.6853
Epoch 10/48
40/40 - 0s - 4ms/step - accuracy: 0.7644 - loss: 0.6766
Epoch 11/48
40/40 - 0s - 4ms/step - accuracy: 0.7688 - loss: 0.6579
Epoch 12/48
40/40 - 0s - 4ms/step - accuracy: 0.7730 - loss: 0.6391
Epoch 13/48
40/40 - 0s - 4ms/step - accuracy: 0.7725 - loss: 0.6336
Epoch 14/48
40/40 - 0s - 4ms/step - accuracy: 0.7805 - loss: 0.6156
Epoch 15/48
40/40 - 0s - 4ms/step - accuracy: 0.7855 - loss: 0.6035
Epoch 16/48
40/40 - 0s - 4ms/step - accuracy: 0.7855 - loss: 0.5972
Epoch 17/48
40/40 - 0s - 4ms/step - accuracy: 0.7893 - loss: 0.5912
Epoch 18/48
40/40 - 0s - 4ms/step - accuracy: 0.7932 - loss: 0.5797
Epoch 19/48
40/40 - 0s - 4ms/step - accuracy: 0.7958 - loss: 0.5748
Epoch 20/48
40/40 - 0s - 4ms/step - accuracy: 0.8016 - loss: 0.5603
Epoch 21/48
40/40 - 0s - 4ms/step - accuracy: 0.8013 - loss: 0.5596
Epoch 22/48
40/40 - 0s - 4ms/step - accuracy: 0.8032 - loss: 0.5479
Epoch 23/48
40/40 - 0s - 4ms/step - accuracy: 0.8051 - loss: 0.5448
Epoch 24/48
40/40 - 0s - 4ms/step - accuracy: 0.8051 - loss: 0.5376
Epoch 25/48
40/40 - 0s - 5ms/step - accuracy: 0.8096 - loss: 0.5338
Epoch 26/48
40/40 - 0s - 5ms/step - accuracy: 0.8089 - loss: 0.5268
Epoch 27/48
40/40 - 0s - 5ms/step - accuracy: 0.8118 - loss: 0.5149
Epoch 28/48
40/40 - 0s - 4ms/step - accuracy: 0.8129 - loss: 0.5130
Epoch 29/48
40/40 - 0s - 4ms/step - accuracy: 0.8157 - loss: 0.5109
Epoch 30/48
40/40 - 0s - 4ms/step - accuracy: 0.8194 - loss: 0.4995
Epoch 31/48
40/40 - 0s - 4ms/step - accuracy: 0.8194 - loss: 0.4971
Epoch 32/48
40/40 - 0s - 4ms/step - accuracy: 0.8210 - loss: 0.4853
Epoch 33/48
40/40 - 0s - 4ms/step - accuracy: 0.8200 - loss: 0.4859
Epoch 34/48
40/40 - 0s - 4ms/step - accuracy: 0.8249 - loss: 0.4774
Epoch 35/48
40/40 - 0s - 4ms/step - accuracy: 0.8250 - loss: 0.4744
Epoch 36/48
40/40 - 0s - 4ms/step - accuracy: 0.8310 - loss: 0.4657
Epoch 37/48
40/40 - 0s - 4ms/step - accuracy: 0.8322 - loss: 0.4596
Epoch 38/48
40/40 - 0s - 4ms/step - accuracy: 0.8294 - loss: 0.4561
Epoch 39/48
40/40 - 0s - 4ms/step - accuracy: 0.8333 - loss: 0.4513
Epoch 40/48
40/40 - 0s - 4ms/step - accuracy: 0.8320 - loss: 0.4505
Epoch 41/48
40/40 - 0s - 4ms/step - accuracy: 0.8374 - loss: 0.4446
Epoch 42/48
40/40 - 0s - 4ms/step - accuracy: 0.8405 - loss: 0.4349
Epoch 43/48
40/40 - 0s - 4ms/step - accuracy: 0.8448 - loss: 0.4295
Epoch 44/48
40/40 - 0s - 4ms/step - accuracy: 0.8423 - loss: 0.4270
Epoch 45/48
40/40 - 0s - 4ms/step - accuracy: 0.8421 - loss: 0.4264
Epoch 46/48
40/40 - 0s - 4ms/step - accuracy: 0.8451 - loss: 0.4244
Epoch 47/48
40/40 - 0s - 4ms/step - accuracy: 0.8476 - loss: 0.4134
Epoch 48/48
40/40 - 0s - 4ms/step - accuracy: 0.8514 - loss: 0.4114
10/10 - 0s - 6ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 0s - 11ms/step - accuracy: 0.5893 - loss: 1.3192
Epoch 2/48
40/40 - 0s - 4ms/step - accuracy: 0.6709 - loss: 0.9774
Epoch 3/48
40/40 - 0s - 4ms/step - accuracy: 0.6996 - loss: 0.8793
Epoch 4/48
40/40 - 0s - 4ms/step - accuracy: 0.7142 - loss: 0.8210
Epoch 5/48
40/40 - 0s - 4ms/step - accuracy: 0.7267 - loss: 0.7792
Epoch 6/48
40/40 - 0s - 4ms/step - accuracy: 0.7428 - loss: 0.7311
Epoch 7/48
40/40 - 0s - 4ms/step - accuracy: 0.7489 - loss: 0.7116
Epoch 8/48
40/40 - 0s - 4ms/step - accuracy: 0.7554 - loss: 0.6878
Epoch 9/48
40/40 - 0s - 4ms/step - accuracy: 0.7593 - loss: 0.6695
Epoch 10/48
40/40 - 0s - 4ms/step - accuracy: 0.7672 - loss: 0.6497
Epoch 11/48
40/40 - 0s - 4ms/step - accuracy: 0.7728 - loss: 0.6322
Epoch 12/48
40/40 - 0s - 4ms/step - accuracy: 0.7786 - loss: 0.6216
Epoch 13/48
40/40 - 0s - 4ms/step - accuracy: 0.7776 - loss: 0.6155
Epoch 14/48
40/40 - 0s - 4ms/step - accuracy: 0.7835 - loss: 0.5988
Epoch 15/48
40/40 - 0s - 4ms/step - accuracy: 0.7871 - loss: 0.5962
Epoch 16/48
40/40 - 0s - 4ms/step - accuracy: 0.7864 - loss: 0.5894
Epoch 17/48
40/40 - 0s - 4ms/step - accuracy: 0.7934 - loss: 0.5713
Epoch 18/48
40/40 - 0s - 4ms/step - accuracy: 0.7928 - loss: 0.5730
Epoch 19/48
40/40 - 0s - 4ms/step - accuracy: 0.7956 - loss: 0.5627
Epoch 20/48
40/40 - 0s - 4ms/step - accuracy: 0.7959 - loss: 0.5609
Epoch 21/48
40/40 - 0s - 4ms/step - accuracy: 0.7991 - loss: 0.5505
Epoch 22/48
40/40 - 0s - 4ms/step - accuracy: 0.8010 - loss: 0.5455
Epoch 23/48
40/40 - 0s - 4ms/step - accuracy: 0.8039 - loss: 0.5419
Epoch 24/48
40/40 - 0s - 4ms/step - accuracy: 0.8061 - loss: 0.5348
Epoch 25/48
40/40 - 0s - 4ms/step - accuracy: 0.8085 - loss: 0.5255
Epoch 26/48
40/40 - 0s - 4ms/step - accuracy: 0.8115 - loss: 0.5225
Epoch 27/48
40/40 - 0s - 4ms/step - accuracy: 0.8121 - loss: 0.5203
Epoch 28/48
40/40 - 0s - 4ms/step - accuracy: 0.8125 - loss: 0.5161
Epoch 29/48
40/40 - 0s - 4ms/step - accuracy: 0.8187 - loss: 0.5042
Epoch 30/48
40/40 - 0s - 4ms/step - accuracy: 0.8168 - loss: 0.5041
Epoch 31/48
40/40 - 0s - 4ms/step - accuracy: 0.8176 - loss: 0.4990
Epoch 32/48
40/40 - 0s - 4ms/step - accuracy: 0.8217 - loss: 0.4881
Epoch 33/48
40/40 - 0s - 4ms/step - accuracy: 0.8234 - loss: 0.4890
Epoch 34/48
40/40 - 0s - 4ms/step - accuracy: 0.8235 - loss: 0.4836
Epoch 35/48
40/40 - 0s - 4ms/step - accuracy: 0.8297 - loss: 0.4760
Epoch 36/48
40/40 - 0s - 4ms/step - accuracy: 0.8276 - loss: 0.4777
Epoch 37/48
40/40 - 0s - 4ms/step - accuracy: 0.8304 - loss: 0.4648
Epoch 38/48
40/40 - 0s - 4ms/step - accuracy: 0.8316 - loss: 0.4662
Epoch 39/48
40/40 - 0s - 4ms/step - accuracy: 0.8354 - loss: 0.4552
Epoch 40/48
40/40 - 0s - 4ms/step - accuracy: 0.8359 - loss: 0.4561
Epoch 41/48
40/40 - 0s - 4ms/step - accuracy: 0.8368 - loss: 0.4535
Epoch 42/48
40/40 - 0s - 4ms/step - accuracy: 0.8396 - loss: 0.4432
Epoch 43/48
40/40 - 0s - 4ms/step - accuracy: 0.8389 - loss: 0.4445
Epoch 44/48
40/40 - 0s - 4ms/step - accuracy: 0.8414 - loss: 0.4378
Epoch 45/48
40/40 - 0s - 4ms/step - accuracy: 0.8439 - loss: 0.4397
Epoch 46/48
40/40 - 0s - 4ms/step - accuracy: 0.8425 - loss: 0.4292
Epoch 47/48
40/40 - 0s - 4ms/step - accuracy: 0.8470 - loss: 0.4229
Epoch 48/48
40/40 - 0s - 4ms/step - accuracy: 0.8448 - loss: 0.4215
10/10 - 0s - 6ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 0s - 11ms/step - accuracy: 0.5870 - loss: 1.3890
Epoch 2/48
40/40 - 0s - 4ms/step - accuracy: 0.6574 - loss: 0.9963
Epoch 3/48
40/40 - 0s - 4ms/step - accuracy: 0.6834 - loss: 0.9050
Epoch 4/48
40/40 - 0s - 4ms/step - accuracy: 0.7060 - loss: 0.8449
Epoch 5/48
40/40 - 0s - 4ms/step - accuracy: 0.7303 - loss: 0.7943
Epoch 6/48
40/40 - 0s - 4ms/step - accuracy: 0.7394 - loss: 0.7569
Epoch 7/48
40/40 - 0s - 4ms/step - accuracy: 0.7489 - loss: 0.7278
Epoch 8/48
40/40 - 0s - 4ms/step - accuracy: 0.7537 - loss: 0.7080
Epoch 9/48
40/40 - 0s - 4ms/step - accuracy: 0.7621 - loss: 0.6868
Epoch 10/48
40/40 - 0s - 4ms/step - accuracy: 0.7678 - loss: 0.6685
Epoch 11/48
40/40 - 0s - 4ms/step - accuracy: 0.7727 - loss: 0.6508
Epoch 12/48
40/40 - 0s - 5ms/step - accuracy: 0.7765 - loss: 0.6363
Epoch 13/48
40/40 - 0s - 4ms/step - accuracy: 0.7748 - loss: 0.6304
Epoch 14/48
40/40 - 0s - 4ms/step - accuracy: 0.7824 - loss: 0.6111
Epoch 15/48
40/40 - 0s - 5ms/step - accuracy: 0.7826 - loss: 0.6053
Epoch 16/48
40/40 - 0s - 4ms/step - accuracy: 0.7901 - loss: 0.5932
Epoch 17/48
40/40 - 0s - 5ms/step - accuracy: 0.7904 - loss: 0.5870
Epoch 18/48
40/40 - 0s - 5ms/step - accuracy: 0.7884 - loss: 0.5822
Epoch 19/48
40/40 - 0s - 5ms/step - accuracy: 0.7977 - loss: 0.5626
Epoch 20/48
40/40 - 0s - 4ms/step - accuracy: 0.7978 - loss: 0.5582
Epoch 21/48
40/40 - 0s - 4ms/step - accuracy: 0.8001 - loss: 0.5504
Epoch 22/48
40/40 - 0s - 4ms/step - accuracy: 0.8023 - loss: 0.5503
Epoch 23/48
40/40 - 0s - 5ms/step - accuracy: 0.8055 - loss: 0.5416
Epoch 24/48
40/40 - 0s - 4ms/step - accuracy: 0.8092 - loss: 0.5337
Epoch 25/48
40/40 - 0s - 4ms/step - accuracy: 0.8109 - loss: 0.5260
Epoch 26/48
40/40 - 0s - 4ms/step - accuracy: 0.8076 - loss: 0.5299
Epoch 27/48
40/40 - 0s - 4ms/step - accuracy: 0.8116 - loss: 0.5146
Epoch 28/48
40/40 - 0s - 4ms/step - accuracy: 0.8129 - loss: 0.5184
Epoch 29/48
40/40 - 0s - 4ms/step - accuracy: 0.8129 - loss: 0.5105
Epoch 30/48
40/40 - 0s - 4ms/step - accuracy: 0.8182 - loss: 0.5025
Epoch 31/48
40/40 - 0s - 4ms/step - accuracy: 0.8174 - loss: 0.5021
Epoch 32/48
40/40 - 0s - 4ms/step - accuracy: 0.8176 - loss: 0.4960
Epoch 33/48
40/40 - 0s - 4ms/step - accuracy: 0.8195 - loss: 0.4950
Epoch 34/48
40/40 - 0s - 4ms/step - accuracy: 0.8205 - loss: 0.4888
Epoch 35/48
40/40 - 0s - 4ms/step - accuracy: 0.8227 - loss: 0.4872
Epoch 36/48
40/40 - 0s - 4ms/step - accuracy: 0.8219 - loss: 0.4879
Epoch 37/48
40/40 - 0s - 4ms/step - accuracy: 0.8245 - loss: 0.4790
Epoch 38/48
40/40 - 0s - 4ms/step - accuracy: 0.8287 - loss: 0.4709
Epoch 39/48
40/40 - 0s - 4ms/step - accuracy: 0.8306 - loss: 0.4665
Epoch 40/48
40/40 - 0s - 4ms/step - accuracy: 0.8267 - loss: 0.4682
Epoch 41/48
40/40 - 0s - 4ms/step - accuracy: 0.8306 - loss: 0.4641
Epoch 42/48
40/40 - 0s - 4ms/step - accuracy: 0.8298 - loss: 0.4653
Epoch 43/48
40/40 - 0s - 4ms/step - accuracy: 0.8332 - loss: 0.4536
Epoch 44/48
40/40 - 0s - 4ms/step - accuracy: 0.8293 - loss: 0.4591
Epoch 45/48
40/40 - 0s - 4ms/step - accuracy: 0.8323 - loss: 0.4561
Epoch 46/48
40/40 - 0s - 4ms/step - accuracy: 0.8328 - loss: 0.4499
Epoch 47/48
40/40 - 0s - 4ms/step - accuracy: 0.8362 - loss: 0.4466
Epoch 48/48
40/40 - 0s - 4ms/step - accuracy: 0.8368 - loss: 0.4450
10/10 - 0s - 6ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

40/40 - 0s - 11ms/step - accuracy: 0.5916 - loss: 1.3347
Epoch 2/48
40/40 - 0s - 4ms/step - accuracy: 0.6651 - loss: 0.9849
Epoch 3/48
40/40 - 0s - 4ms/step - accuracy: 0.6850 - loss: 0.9014
Epoch 4/48
40/40 - 0s - 4ms/step - accuracy: 0.7102 - loss: 0.8437
Epoch 5/48
40/40 - 0s - 4ms/step - accuracy: 0.7225 - loss: 0.7962
Epoch 6/48
40/40 - 0s - 4ms/step - accuracy: 0.7379 - loss: 0.7525
Epoch 7/48
40/40 - 0s - 4ms/step - accuracy: 0.7442 - loss: 0.7247
Epoch 8/48
40/40 - 0s - 4ms/step - accuracy: 0.7518 - loss: 0.6993
Epoch 9/48
40/40 - 0s - 4ms/step - accuracy: 0.7598 - loss: 0.6804
Epoch 10/48
40/40 - 0s - 4ms/step - accuracy: 0.7658 - loss: 0.6599
Epoch 11/48
40/40 - 0s - 4ms/step - accuracy: 0.7638 - loss: 0.6580
Epoch 12/48
40/40 - 0s - 4ms/step - accuracy: 0.7725 - loss: 0.6379
Epoch 13/48
40/40 - 0s - 4ms/step - accuracy: 0.7739 - loss: 0.6204
Epoch 14/48
40/40 - 0s - 4ms/step - accuracy: 0.7818 - loss: 0.6075
Epoch 15/48
40/40 - 0s - 4ms/step - accuracy: 0.7824 - loss: 0.5979
Epoch 16/48
40/40 - 0s - 4ms/step - accuracy: 0.7866 - loss: 0.5899
Epoch 17/48
40/40 - 0s - 4ms/step - accuracy: 0.7926 - loss: 0.5782
Epoch 18/48
40/40 - 0s - 4ms/step - accuracy: 0.7918 - loss: 0.5709
Epoch 19/48
40/40 - 0s - 4ms/step - accuracy: 0.7984 - loss: 0.5596
Epoch 20/48
40/40 - 0s - 4ms/step - accuracy: 0.8007 - loss: 0.5602
Epoch 21/48
40/40 - 0s - 4ms/step - accuracy: 0.8044 - loss: 0.5410
Epoch 22/48
40/40 - 0s - 4ms/step - accuracy: 0.8018 - loss: 0.5448
Epoch 23/48
40/40 - 0s - 4ms/step - accuracy: 0.8086 - loss: 0.5308
Epoch 24/48
40/40 - 0s - 4ms/step - accuracy: 0.8078 - loss: 0.5308
Epoch 25/48
40/40 - 0s - 4ms/step - accuracy: 0.8081 - loss: 0.5194
Epoch 26/48
40/40 - 0s - 4ms/step - accuracy: 0.8143 - loss: 0.5185
Epoch 27/48
40/40 - 0s - 4ms/step - accuracy: 0.8157 - loss: 0.5086
Epoch 28/48
40/40 - 0s - 4ms/step - accuracy: 0.8175 - loss: 0.5003
Epoch 29/48
40/40 - 0s - 4ms/step - accuracy: 0.8164 - loss: 0.5002
Epoch 30/48
40/40 - 0s - 4ms/step - accuracy: 0.8227 - loss: 0.4923
Epoch 31/48
40/40 - 0s - 4ms/step - accuracy: 0.8235 - loss: 0.4839
Epoch 32/48
40/40 - 0s - 4ms/step - accuracy: 0.8262 - loss: 0.4810
Epoch 33/48
40/40 - 0s - 4ms/step - accuracy: 0.8314 - loss: 0.4685
Epoch 34/48
40/40 - 0s - 4ms/step - accuracy: 0.8275 - loss: 0.4712
Epoch 35/48
40/40 - 0s - 4ms/step - accuracy: 0.8283 - loss: 0.4685
Epoch 36/48
40/40 - 0s - 4ms/step - accuracy: 0.8305 - loss: 0.4626
Epoch 37/48
40/40 - 0s - 4ms/step - accuracy: 0.8296 - loss: 0.4645
Epoch 38/48
40/40 - 0s - 4ms/step - accuracy: 0.8333 - loss: 0.4537
Epoch 39/48
40/40 - 0s - 4ms/step - accuracy: 0.8362 - loss: 0.4460
Epoch 40/48
40/40 - 0s - 4ms/step - accuracy: 0.8378 - loss: 0.4467
Epoch 41/48
40/40 - 0s - 4ms/step - accuracy: 0.8374 - loss: 0.4446
Epoch 42/48
40/40 - 0s - 4ms/step - accuracy: 0.8433 - loss: 0.4329
Epoch 43/48
40/40 - 0s - 4ms/step - accuracy: 0.8408 - loss: 0.4325
Epoch 44/48
40/40 - 0s - 4ms/step - accuracy: 0.8455 - loss: 0.4264
Epoch 45/48
40/40 - 0s - 4ms/step - accuracy: 0.8491 - loss: 0.4161
Epoch 46/48
40/40 - 0s - 4ms/step - accuracy: 0.8506 - loss: 0.4178
Epoch 47/48
40/40 - 0s - 4ms/step - accuracy: 0.8477 - loss: 0.4151
Epoch 48/48
40/40 - 0s - 4ms/step - accuracy: 0.8498 - loss: 0.4137
10/10 - 0s - 6ms/step
| 5         | 0.8427    | 4.92      | 347.9     | 0.9696    | 0.2325    | 48.18     | 2.79      | 2.196     | 2.844     | 0.09761   | 27.64     | 0.04523   | 2.277     |
Epoch 1/28

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 1s - 42ms/step - accuracy: 0.6276 - loss: 1.3110
Epoch 2/28
34/34 - 1s - 29ms/step - accuracy: 0.7149 - loss: 0.8485
Epoch 3/28
34/34 - 1s - 28ms/step - accuracy: 0.7450 - loss: 0.7567
Epoch 4/28
34/34 - 1s - 28ms/step - accuracy: 0.7629 - loss: 0.7001
Epoch 5/28
34/34 - 1s - 28ms/step - accuracy: 0.7757 - loss: 0.6663
Epoch 6/28
34/34 - 1s - 28ms/step - accuracy: 0.7713 - loss: 0.6576
Epoch 7/28
34/34 - 1s - 28ms/step - accuracy: 0.7919 - loss: 0.5909
Epoch 8/28
34/34 - 1s - 29ms/step - accuracy: 0.8063 - loss: 0.5596
Epoch 9/28
34/34 - 1s - 29ms/step - accuracy: 0.8110 - loss: 0.5369
Epoch 10/28
34/34 - 1s - 29ms/step - accuracy: 0.8224 - loss: 0.5081
Epoch 11/28
34/34 - 1s - 29ms/step - accuracy: 0.8206 - loss: 0.5115
Epoch 12/28
34/34 - 1s - 28ms/step - accuracy: 0.8370 - loss: 0.4636
Epoch 13/28
34/34 - 1s - 28ms/step - accuracy: 0.8217 - loss: 0.5040
Epoch 14/28
34/34 - 1s - 29ms/step - accuracy: 0.8423 - loss: 0.4550
Epoch 15/28
34/34 - 1s - 29ms/step - accuracy: 0.8494 - loss: 0.4249
Epoch 16/28
34/34 - 1s - 28ms/step - accuracy: 0.8518 - loss: 0.4167
Epoch 17/28
34/34 - 1s - 28ms/step - accuracy: 0.8482 - loss: 0.4243
Epoch 18/28
34/34 - 1s - 29ms/step - accuracy: 0.8616 - loss: 0.3897
Epoch 19/28
34/34 - 1s - 28ms/step - accuracy: 0.8587 - loss: 0.3938
Epoch 20/28
34/34 - 1s - 28ms/step - accuracy: 0.8660 - loss: 0.3761
Epoch 21/28
34/34 - 1s - 29ms/step - accuracy: 0.8708 - loss: 0.3589
Epoch 22/28
34/34 - 1s - 29ms/step - accuracy: 0.8738 - loss: 0.3578
Epoch 23/28
34/34 - 1s - 29ms/step - accuracy: 0.8746 - loss: 0.3507
Epoch 24/28
34/34 - 1s - 28ms/step - accuracy: 0.8730 - loss: 0.3590
Epoch 25/28
34/34 - 1s - 28ms/step - accuracy: 0.8826 - loss: 0.3363
Epoch 26/28
34/34 - 1s - 29ms/step - accuracy: 0.8900 - loss: 0.3164
Epoch 27/28
34/34 - 1s - 29ms/step - accuracy: 0.8874 - loss: 0.3206
Epoch 28/28
34/34 - 1s - 29ms/step - accuracy: 0.8933 - loss: 0.3058
9/9 - 0s - 15ms/step
Epoch 1/28

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 1s - 42ms/step - accuracy: 0.6231 - loss: 1.3140
Epoch 2/28
34/34 - 1s - 28ms/step - accuracy: 0.7064 - loss: 0.8652
Epoch 3/28
34/34 - 1s - 28ms/step - accuracy: 0.7388 - loss: 0.7623
Epoch 4/28
34/34 - 1s - 28ms/step - accuracy: 0.7624 - loss: 0.6985
Epoch 5/28
34/34 - 1s - 28ms/step - accuracy: 0.7774 - loss: 0.6407
Epoch 6/28
34/34 - 1s - 29ms/step - accuracy: 0.7882 - loss: 0.6043
Epoch 7/28
34/34 - 1s - 28ms/step - accuracy: 0.8023 - loss: 0.5661
Epoch 8/28
34/34 - 1s - 29ms/step - accuracy: 0.8169 - loss: 0.5261
Epoch 9/28
34/34 - 1s - 28ms/step - accuracy: 0.8216 - loss: 0.5106
Epoch 10/28
34/34 - 1s - 28ms/step - accuracy: 0.8277 - loss: 0.4825
Epoch 11/28
34/34 - 1s - 28ms/step - accuracy: 0.8393 - loss: 0.4590
Epoch 12/28
34/34 - 1s - 28ms/step - accuracy: 0.8256 - loss: 0.4956
Epoch 13/28
34/34 - 1s - 28ms/step - accuracy: 0.8449 - loss: 0.4326
Epoch 14/28
34/34 - 1s - 28ms/step - accuracy: 0.8415 - loss: 0.4462
Epoch 15/28
34/34 - 1s - 29ms/step - accuracy: 0.8473 - loss: 0.4292
Epoch 16/28
34/34 - 1s - 28ms/step - accuracy: 0.8622 - loss: 0.3894
Epoch 17/28
34/34 - 1s - 28ms/step - accuracy: 0.8537 - loss: 0.4104
Epoch 18/28
34/34 - 1s - 29ms/step - accuracy: 0.8665 - loss: 0.3670
Epoch 19/28
34/34 - 1s - 29ms/step - accuracy: 0.8725 - loss: 0.3567
Epoch 20/28
34/34 - 1s - 28ms/step - accuracy: 0.8616 - loss: 0.3841
Epoch 21/28
34/34 - 1s - 29ms/step - accuracy: 0.8727 - loss: 0.3527
Epoch 22/28
34/34 - 1s - 29ms/step - accuracy: 0.8728 - loss: 0.3520
Epoch 23/28
34/34 - 1s - 29ms/step - accuracy: 0.8784 - loss: 0.3289
Epoch 24/28
34/34 - 1s - 29ms/step - accuracy: 0.8785 - loss: 0.3314
Epoch 25/28
34/34 - 1s - 29ms/step - accuracy: 0.8777 - loss: 0.3426
Epoch 26/28
34/34 - 1s - 29ms/step - accuracy: 0.8959 - loss: 0.2941
Epoch 27/28
34/34 - 1s - 29ms/step - accuracy: 0.8975 - loss: 0.2838
Epoch 28/28
34/34 - 1s - 29ms/step - accuracy: 0.8944 - loss: 0.2965
9/9 - 0s - 15ms/step
Epoch 1/28

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 1s - 42ms/step - accuracy: 0.6186 - loss: 1.2789
Epoch 2/28
34/34 - 1s - 29ms/step - accuracy: 0.7020 - loss: 0.8433
Epoch 3/28
34/34 - 1s - 28ms/step - accuracy: 0.7348 - loss: 0.7648
Epoch 4/28
34/34 - 1s - 29ms/step - accuracy: 0.7581 - loss: 0.6989
Epoch 5/28
34/34 - 1s - 28ms/step - accuracy: 0.7733 - loss: 0.6534
Epoch 6/28
34/34 - 1s - 28ms/step - accuracy: 0.7840 - loss: 0.6174
Epoch 7/28
34/34 - 1s - 28ms/step - accuracy: 0.7954 - loss: 0.5913
Epoch 8/28
34/34 - 1s - 28ms/step - accuracy: 0.8075 - loss: 0.5546
Epoch 9/28
34/34 - 1s - 29ms/step - accuracy: 0.8239 - loss: 0.5092
Epoch 10/28
34/34 - 1s - 29ms/step - accuracy: 0.8255 - loss: 0.4965
Epoch 11/28
34/34 - 1s - 29ms/step - accuracy: 0.8352 - loss: 0.4682
Epoch 12/28
34/34 - 1s - 28ms/step - accuracy: 0.8455 - loss: 0.4440
Epoch 13/28
34/34 - 1s - 28ms/step - accuracy: 0.8407 - loss: 0.4525
Epoch 14/28
34/34 - 1s - 29ms/step - accuracy: 0.8458 - loss: 0.4382
Epoch 15/28
34/34 - 1s - 29ms/step - accuracy: 0.8493 - loss: 0.4300
Epoch 16/28
34/34 - 1s - 29ms/step - accuracy: 0.8590 - loss: 0.3952
Epoch 17/28
34/34 - 1s - 28ms/step - accuracy: 0.8688 - loss: 0.3654
Epoch 18/28
34/34 - 1s - 28ms/step - accuracy: 0.8696 - loss: 0.3727
Epoch 19/28
34/34 - 1s - 28ms/step - accuracy: 0.8723 - loss: 0.3562
Epoch 20/28
34/34 - 1s - 28ms/step - accuracy: 0.8782 - loss: 0.3505
Epoch 21/28
34/34 - 1s - 29ms/step - accuracy: 0.8792 - loss: 0.3485
Epoch 22/28
34/34 - 1s - 29ms/step - accuracy: 0.8805 - loss: 0.3312
Epoch 23/28
34/34 - 1s - 28ms/step - accuracy: 0.8813 - loss: 0.3300
Epoch 24/28
34/34 - 1s - 28ms/step - accuracy: 0.8717 - loss: 0.3624
Epoch 25/28
34/34 - 1s - 29ms/step - accuracy: 0.8718 - loss: 0.3630
Epoch 26/28
34/34 - 1s - 29ms/step - accuracy: 0.8731 - loss: 0.3492
Epoch 27/28
34/34 - 1s - 29ms/step - accuracy: 0.8894 - loss: 0.3102
Epoch 28/28
34/34 - 1s - 28ms/step - accuracy: 0.8704 - loss: 0.3675
9/9 - 0s - 15ms/step
Epoch 1/28

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 1s - 42ms/step - accuracy: 0.6017 - loss: 1.3195
Epoch 2/28
34/34 - 1s - 29ms/step - accuracy: 0.6987 - loss: 0.8633
Epoch 3/28
34/34 - 1s - 29ms/step - accuracy: 0.7253 - loss: 0.7753
Epoch 4/28
34/34 - 1s - 28ms/step - accuracy: 0.7548 - loss: 0.6965
Epoch 5/28
34/34 - 1s - 28ms/step - accuracy: 0.7792 - loss: 0.6393
Epoch 6/28
34/34 - 1s - 29ms/step - accuracy: 0.7978 - loss: 0.5882
Epoch 7/28
34/34 - 1s - 29ms/step - accuracy: 0.8017 - loss: 0.5696
Epoch 8/28
34/34 - 1s - 29ms/step - accuracy: 0.8097 - loss: 0.5405
Epoch 9/28
34/34 - 1s - 29ms/step - accuracy: 0.8286 - loss: 0.4931
Epoch 10/28
34/34 - 1s - 29ms/step - accuracy: 0.8285 - loss: 0.4873
Epoch 11/28
34/34 - 1s - 29ms/step - accuracy: 0.8296 - loss: 0.4789
Epoch 12/28
34/34 - 1s - 29ms/step - accuracy: 0.8394 - loss: 0.4491
Epoch 13/28
34/34 - 1s - 29ms/step - accuracy: 0.8469 - loss: 0.4300
Epoch 14/28
34/34 - 1s - 29ms/step - accuracy: 0.8425 - loss: 0.4318
Epoch 15/28
34/34 - 1s - 30ms/step - accuracy: 0.8589 - loss: 0.3959
Epoch 16/28
34/34 - 1s - 28ms/step - accuracy: 0.8694 - loss: 0.3664
Epoch 17/28
34/34 - 1s - 29ms/step - accuracy: 0.8745 - loss: 0.3619
Epoch 18/28
34/34 - 1s - 29ms/step - accuracy: 0.8481 - loss: 0.4303
Epoch 19/28
34/34 - 1s - 29ms/step - accuracy: 0.8690 - loss: 0.3656
Epoch 20/28
34/34 - 1s - 29ms/step - accuracy: 0.8803 - loss: 0.3391
Epoch 21/28
34/34 - 1s - 29ms/step - accuracy: 0.8694 - loss: 0.3668
Epoch 22/28
34/34 - 1s - 29ms/step - accuracy: 0.8824 - loss: 0.3368
Epoch 23/28
34/34 - 1s - 29ms/step - accuracy: 0.8809 - loss: 0.3324
Epoch 24/28
34/34 - 1s - 29ms/step - accuracy: 0.8914 - loss: 0.3110
Epoch 25/28
34/34 - 1s - 29ms/step - accuracy: 0.8933 - loss: 0.3038
Epoch 26/28
34/34 - 1s - 29ms/step - accuracy: 0.8886 - loss: 0.3175
Epoch 27/28
34/34 - 1s - 29ms/step - accuracy: 0.8956 - loss: 0.2928
Epoch 28/28
34/34 - 1s - 28ms/step - accuracy: 0.8921 - loss: 0.3051
9/9 - 0s - 15ms/step
Epoch 1/28

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 - 1s - 42ms/step - accuracy: 0.6219 - loss: 1.2702
Epoch 2/28
34/34 - 1s - 29ms/step - accuracy: 0.7059 - loss: 0.8550
Epoch 3/28
34/34 - 1s - 29ms/step - accuracy: 0.7425 - loss: 0.7502
Epoch 4/28
34/34 - 1s - 28ms/step - accuracy: 0.7627 - loss: 0.6923
Epoch 5/28
34/34 - 1s - 28ms/step - accuracy: 0.7782 - loss: 0.6433
Epoch 6/28
34/34 - 1s - 28ms/step - accuracy: 0.7896 - loss: 0.6032
Epoch 7/28
34/34 - 1s - 28ms/step - accuracy: 0.7996 - loss: 0.5693
Epoch 8/28
34/34 - 1s - 28ms/step - accuracy: 0.8054 - loss: 0.5531
Epoch 9/28
34/34 - 1s - 28ms/step - accuracy: 0.8224 - loss: 0.5077
Epoch 10/28
34/34 - 1s - 28ms/step - accuracy: 0.8320 - loss: 0.4806
Epoch 11/28
34/34 - 1s - 28ms/step - accuracy: 0.8184 - loss: 0.5140
Epoch 12/28
34/34 - 1s - 29ms/step - accuracy: 0.8366 - loss: 0.4612
Epoch 13/28
34/34 - 1s - 28ms/step - accuracy: 0.8230 - loss: 0.4932
Epoch 14/28
34/34 - 1s - 28ms/step - accuracy: 0.8433 - loss: 0.4394
Epoch 15/28
34/34 - 1s - 28ms/step - accuracy: 0.8431 - loss: 0.4375
Epoch 16/28
34/34 - 1s - 28ms/step - accuracy: 0.8584 - loss: 0.3974
Epoch 17/28
34/34 - 1s - 29ms/step - accuracy: 0.8595 - loss: 0.3958
Epoch 18/28
34/34 - 1s - 28ms/step - accuracy: 0.8545 - loss: 0.3988
Epoch 19/28
34/34 - 1s - 29ms/step - accuracy: 0.8568 - loss: 0.4032
Epoch 20/28
34/34 - 1s - 28ms/step - accuracy: 0.8694 - loss: 0.3622
Epoch 21/28
34/34 - 1s - 28ms/step - accuracy: 0.8695 - loss: 0.3714
Epoch 22/28
34/34 - 1s - 28ms/step - accuracy: 0.8789 - loss: 0.3428
Epoch 23/28
34/34 - 1s - 29ms/step - accuracy: 0.8863 - loss: 0.3260
Epoch 24/28
34/34 - 1s - 29ms/step - accuracy: 0.8872 - loss: 0.3200
Epoch 25/28
34/34 - 1s - 28ms/step - accuracy: 0.8720 - loss: 0.3638
Epoch 26/28
34/34 - 1s - 28ms/step - accuracy: 0.8879 - loss: 0.3182
Epoch 27/28
34/34 - 1s - 28ms/step - accuracy: 0.8964 - loss: 0.3034
Epoch 28/28
34/34 - 1s - 28ms/step - accuracy: 0.8708 - loss: 0.3677
9/9 - 0s - 15ms/step
| 6         | 0.8617    | 3.498     | 417.1     | 0.8287    | 0.107     | 28.43     | 2.085     | 1.282     | 2.604     | 0.08381   | 98.82     | 0.7722    | 1.391     |
Epoch 1/43

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 30ms/step - accuracy: 0.5846 - loss: 1.5423
Epoch 2/43
17/17 - 0s - 21ms/step - accuracy: 0.6358 - loss: 1.1365
Epoch 3/43
17/17 - 0s - 21ms/step - accuracy: 0.6451 - loss: 1.0854
Epoch 4/43
17/17 - 0s - 22ms/step - accuracy: 0.6549 - loss: 1.0535
Epoch 5/43
17/17 - 0s - 22ms/step - accuracy: 0.6618 - loss: 1.0282
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6596 - loss: 1.0173
Epoch 7/43
17/17 - 0s - 22ms/step - accuracy: 0.6646 - loss: 0.9991
Epoch 8/43
17/17 - 0s - 22ms/step - accuracy: 0.6635 - loss: 0.9893
Epoch 9/43
17/17 - 0s - 22ms/step - accuracy: 0.6696 - loss: 0.9794
Epoch 10/43
17/17 - 0s - 22ms/step - accuracy: 0.6704 - loss: 0.9661
Epoch 11/43
17/17 - 0s - 22ms/step - accuracy: 0.6772 - loss: 0.9560
Epoch 12/43
17/17 - 0s - 22ms/step - accuracy: 0.6817 - loss: 0.9449
Epoch 13/43
17/17 - 0s - 22ms/step - accuracy: 0.6796 - loss: 0.9369
Epoch 14/43
17/17 - 0s - 22ms/step - accuracy: 0.6812 - loss: 0.9265
Epoch 15/43
17/17 - 0s - 22ms/step - accuracy: 0.6843 - loss: 0.9180
Epoch 16/43
17/17 - 0s - 22ms/step - accuracy: 0.6894 - loss: 0.9070
Epoch 17/43
17/17 - 0s - 23ms/step - accuracy: 0.6852 - loss: 0.8976
Epoch 18/43
17/17 - 0s - 23ms/step - accuracy: 0.6935 - loss: 0.8925
Epoch 19/43
17/17 - 0s - 21ms/step - accuracy: 0.6978 - loss: 0.8913
Epoch 20/43
17/17 - 0s - 22ms/step - accuracy: 0.6977 - loss: 0.8801
Epoch 21/43
17/17 - 0s - 22ms/step - accuracy: 0.6963 - loss: 0.8774
Epoch 22/43
17/17 - 0s - 22ms/step - accuracy: 0.6981 - loss: 0.8679
Epoch 23/43
17/17 - 0s - 22ms/step - accuracy: 0.7019 - loss: 0.8695
Epoch 24/43
17/17 - 0s - 22ms/step - accuracy: 0.7040 - loss: 0.8621
Epoch 25/43
17/17 - 0s - 22ms/step - accuracy: 0.7033 - loss: 0.8531
Epoch 26/43
17/17 - 0s - 21ms/step - accuracy: 0.7056 - loss: 0.8508
Epoch 27/43
17/17 - 0s - 21ms/step - accuracy: 0.7099 - loss: 0.8494
Epoch 28/43
17/17 - 0s - 22ms/step - accuracy: 0.7123 - loss: 0.8381
Epoch 29/43
17/17 - 0s - 22ms/step - accuracy: 0.7138 - loss: 0.8370
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7116 - loss: 0.8303
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.7093 - loss: 0.8323
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7149 - loss: 0.8281
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7141 - loss: 0.8272
Epoch 34/43
17/17 - 0s - 21ms/step - accuracy: 0.7133 - loss: 0.8231
Epoch 35/43
17/17 - 0s - 22ms/step - accuracy: 0.7159 - loss: 0.8190
Epoch 36/43
17/17 - 0s - 21ms/step - accuracy: 0.7178 - loss: 0.8175
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7205 - loss: 0.8127
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7207 - loss: 0.8130
Epoch 39/43
17/17 - 0s - 22ms/step - accuracy: 0.7198 - loss: 0.8068
Epoch 40/43
17/17 - 0s - 21ms/step - accuracy: 0.7186 - loss: 0.8078
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7206 - loss: 0.8049
Epoch 42/43
17/17 - 0s - 21ms/step - accuracy: 0.7194 - loss: 0.8079
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7215 - loss: 0.8065
5/5 - 0s - 15ms/step
Epoch 1/43

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 32ms/step - accuracy: 0.5746 - loss: 1.6160
Epoch 2/43
17/17 - 0s - 22ms/step - accuracy: 0.6465 - loss: 1.0791
Epoch 3/43
17/17 - 0s - 22ms/step - accuracy: 0.6490 - loss: 1.0333
Epoch 4/43
17/17 - 0s - 21ms/step - accuracy: 0.6547 - loss: 1.0012
Epoch 5/43
17/17 - 0s - 22ms/step - accuracy: 0.6650 - loss: 0.9753
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6713 - loss: 0.9528
Epoch 7/43
17/17 - 0s - 22ms/step - accuracy: 0.6745 - loss: 0.9375
Epoch 8/43
17/17 - 0s - 22ms/step - accuracy: 0.6824 - loss: 0.9198
Epoch 9/43
17/17 - 0s - 21ms/step - accuracy: 0.6844 - loss: 0.9086
Epoch 10/43
17/17 - 0s - 22ms/step - accuracy: 0.6855 - loss: 0.8975
Epoch 11/43
17/17 - 0s - 22ms/step - accuracy: 0.6923 - loss: 0.8882
Epoch 12/43
17/17 - 0s - 21ms/step - accuracy: 0.6971 - loss: 0.8720
Epoch 13/43
17/17 - 0s - 22ms/step - accuracy: 0.6982 - loss: 0.8717
Epoch 14/43
17/17 - 0s - 22ms/step - accuracy: 0.7011 - loss: 0.8622
Epoch 15/43
17/17 - 0s - 21ms/step - accuracy: 0.7048 - loss: 0.8547
Epoch 16/43
17/17 - 0s - 21ms/step - accuracy: 0.7049 - loss: 0.8520
Epoch 17/43
17/17 - 0s - 22ms/step - accuracy: 0.7083 - loss: 0.8444
Epoch 18/43
17/17 - 0s - 23ms/step - accuracy: 0.7059 - loss: 0.8418
Epoch 19/43
17/17 - 0s - 21ms/step - accuracy: 0.7072 - loss: 0.8342
Epoch 20/43
17/17 - 0s - 21ms/step - accuracy: 0.7102 - loss: 0.8344
Epoch 21/43
17/17 - 0s - 22ms/step - accuracy: 0.7120 - loss: 0.8315
Epoch 22/43
17/17 - 0s - 22ms/step - accuracy: 0.7107 - loss: 0.8287
Epoch 23/43
17/17 - 0s - 22ms/step - accuracy: 0.7138 - loss: 0.8242
Epoch 24/43
17/17 - 0s - 22ms/step - accuracy: 0.7159 - loss: 0.8193
Epoch 25/43
17/17 - 0s - 22ms/step - accuracy: 0.7181 - loss: 0.8225
Epoch 26/43
17/17 - 0s - 22ms/step - accuracy: 0.7177 - loss: 0.8140
Epoch 27/43
17/17 - 0s - 22ms/step - accuracy: 0.7162 - loss: 0.8168
Epoch 28/43
17/17 - 0s - 22ms/step - accuracy: 0.7221 - loss: 0.8058
Epoch 29/43
17/17 - 0s - 22ms/step - accuracy: 0.7206 - loss: 0.8082
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7228 - loss: 0.8069
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.7191 - loss: 0.8049
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7271 - loss: 0.7972
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7252 - loss: 0.7988
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7266 - loss: 0.7986
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7210 - loss: 0.8031
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7257 - loss: 0.7902
Epoch 37/43
17/17 - 0s - 22ms/step - accuracy: 0.7263 - loss: 0.7902
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7298 - loss: 0.7892
Epoch 39/43
17/17 - 0s - 22ms/step - accuracy: 0.7288 - loss: 0.7886
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7292 - loss: 0.7860
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7287 - loss: 0.7838
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7283 - loss: 0.7826
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7320 - loss: 0.7792
5/5 - 0s - 15ms/step
Epoch 1/43

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 30ms/step - accuracy: 0.6023 - loss: 1.5124
Epoch 2/43
17/17 - 0s - 21ms/step - accuracy: 0.6455 - loss: 1.1454
Epoch 3/43
17/17 - 0s - 22ms/step - accuracy: 0.6537 - loss: 1.0920
Epoch 4/43
17/17 - 0s - 21ms/step - accuracy: 0.6516 - loss: 1.0643
Epoch 5/43
17/17 - 0s - 22ms/step - accuracy: 0.6624 - loss: 1.0333
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6601 - loss: 1.0132
Epoch 7/43
17/17 - 0s - 22ms/step - accuracy: 0.6692 - loss: 0.9884
Epoch 8/43
17/17 - 0s - 22ms/step - accuracy: 0.6703 - loss: 0.9778
Epoch 9/43
17/17 - 0s - 21ms/step - accuracy: 0.6683 - loss: 0.9618
Epoch 10/43
17/17 - 0s - 22ms/step - accuracy: 0.6761 - loss: 0.9511
Epoch 11/43
17/17 - 0s - 22ms/step - accuracy: 0.6792 - loss: 0.9407
Epoch 12/43
17/17 - 0s - 22ms/step - accuracy: 0.6846 - loss: 0.9292
Epoch 13/43
17/17 - 0s - 22ms/step - accuracy: 0.6853 - loss: 0.9187
Epoch 14/43
17/17 - 0s - 21ms/step - accuracy: 0.6917 - loss: 0.9118
Epoch 15/43
17/17 - 0s - 22ms/step - accuracy: 0.6943 - loss: 0.9057
Epoch 16/43
17/17 - 0s - 22ms/step - accuracy: 0.6980 - loss: 0.8907
Epoch 17/43
17/17 - 0s - 23ms/step - accuracy: 0.6954 - loss: 0.8841
Epoch 18/43
17/17 - 0s - 22ms/step - accuracy: 0.6985 - loss: 0.8814
Epoch 19/43
17/17 - 0s - 22ms/step - accuracy: 0.6991 - loss: 0.8753
Epoch 20/43
17/17 - 0s - 22ms/step - accuracy: 0.7033 - loss: 0.8665
Epoch 21/43
17/17 - 0s - 22ms/step - accuracy: 0.7056 - loss: 0.8633
Epoch 22/43
17/17 - 0s - 22ms/step - accuracy: 0.7102 - loss: 0.8561
Epoch 23/43
17/17 - 0s - 21ms/step - accuracy: 0.7144 - loss: 0.8452
Epoch 24/43
17/17 - 0s - 22ms/step - accuracy: 0.7125 - loss: 0.8469
Epoch 25/43
17/17 - 0s - 21ms/step - accuracy: 0.7133 - loss: 0.8450
Epoch 26/43
17/17 - 0s - 22ms/step - accuracy: 0.7154 - loss: 0.8365
Epoch 27/43
17/17 - 0s - 22ms/step - accuracy: 0.7174 - loss: 0.8370
Epoch 28/43
17/17 - 0s - 22ms/step - accuracy: 0.7129 - loss: 0.8373
Epoch 29/43
17/17 - 0s - 22ms/step - accuracy: 0.7174 - loss: 0.8268
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7205 - loss: 0.8243
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.7215 - loss: 0.8197
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7227 - loss: 0.8175
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7229 - loss: 0.8180
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7242 - loss: 0.8137
Epoch 35/43
17/17 - 0s - 21ms/step - accuracy: 0.7236 - loss: 0.8154
Epoch 36/43
17/17 - 0s - 21ms/step - accuracy: 0.7227 - loss: 0.8109
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7224 - loss: 0.8102
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7238 - loss: 0.8051
Epoch 39/43
17/17 - 0s - 21ms/step - accuracy: 0.7250 - loss: 0.8041
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7278 - loss: 0.7997
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7259 - loss: 0.8021
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7303 - loss: 0.7936
Epoch 43/43
17/17 - 0s - 21ms/step - accuracy: 0.7301 - loss: 0.7951
5/5 - 0s - 15ms/step
Epoch 1/43

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 63ms/step - accuracy: 0.5895 - loss: 1.4583
Epoch 2/43
17/17 - 0s - 22ms/step - accuracy: 0.6443 - loss: 1.1374
Epoch 3/43
17/17 - 0s - 22ms/step - accuracy: 0.6503 - loss: 1.0952
Epoch 4/43
17/17 - 0s - 22ms/step - accuracy: 0.6540 - loss: 1.0743
Epoch 5/43
17/17 - 0s - 21ms/step - accuracy: 0.6515 - loss: 1.0646
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6622 - loss: 1.0387
Epoch 7/43
17/17 - 0s - 22ms/step - accuracy: 0.6641 - loss: 1.0372
Epoch 8/43
17/17 - 0s - 22ms/step - accuracy: 0.6643 - loss: 1.0262
Epoch 9/43
17/17 - 0s - 22ms/step - accuracy: 0.6733 - loss: 1.0107
Epoch 10/43
17/17 - 0s - 22ms/step - accuracy: 0.6689 - loss: 1.0059
Epoch 11/43
17/17 - 0s - 22ms/step - accuracy: 0.6768 - loss: 0.9919
Epoch 12/43
17/17 - 0s - 22ms/step - accuracy: 0.6763 - loss: 0.9824
Epoch 13/43
17/17 - 0s - 22ms/step - accuracy: 0.6824 - loss: 0.9763
Epoch 14/43
17/17 - 0s - 22ms/step - accuracy: 0.6832 - loss: 0.9644
Epoch 15/43
17/17 - 0s - 23ms/step - accuracy: 0.6839 - loss: 0.9587
Epoch 16/43
17/17 - 0s - 22ms/step - accuracy: 0.6863 - loss: 0.9469
Epoch 17/43
17/17 - 0s - 22ms/step - accuracy: 0.6886 - loss: 0.9420
Epoch 18/43
17/17 - 0s - 22ms/step - accuracy: 0.6895 - loss: 0.9321
Epoch 19/43
17/17 - 0s - 22ms/step - accuracy: 0.6940 - loss: 0.9241
Epoch 20/43
17/17 - 0s - 22ms/step - accuracy: 0.6977 - loss: 0.9123
Epoch 21/43
17/17 - 0s - 22ms/step - accuracy: 0.6964 - loss: 0.9060
Epoch 22/43
17/17 - 0s - 22ms/step - accuracy: 0.7036 - loss: 0.8962
Epoch 23/43
17/17 - 0s - 22ms/step - accuracy: 0.7038 - loss: 0.8899
Epoch 24/43
17/17 - 0s - 22ms/step - accuracy: 0.7092 - loss: 0.8765
Epoch 25/43
17/17 - 0s - 22ms/step - accuracy: 0.7035 - loss: 0.8829
Epoch 26/43
17/17 - 0s - 22ms/step - accuracy: 0.7066 - loss: 0.8679
Epoch 27/43
17/17 - 0s - 22ms/step - accuracy: 0.7062 - loss: 0.8681
Epoch 28/43
17/17 - 0s - 22ms/step - accuracy: 0.7103 - loss: 0.8653
Epoch 29/43
17/17 - 0s - 22ms/step - accuracy: 0.7137 - loss: 0.8525
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7158 - loss: 0.8502
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.7152 - loss: 0.8477
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7142 - loss: 0.8386
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7187 - loss: 0.8356
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7174 - loss: 0.8360
Epoch 35/43
17/17 - 0s - 22ms/step - accuracy: 0.7220 - loss: 0.8321
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7224 - loss: 0.8252
Epoch 37/43
17/17 - 0s - 21ms/step - accuracy: 0.7264 - loss: 0.8206
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7235 - loss: 0.8208
Epoch 39/43
17/17 - 0s - 22ms/step - accuracy: 0.7246 - loss: 0.8165
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7274 - loss: 0.8119
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7245 - loss: 0.8098
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7240 - loss: 0.8084
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7274 - loss: 0.8023
5/5 - 0s - 15ms/step
Epoch 1/43

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 1s - 30ms/step - accuracy: 0.5483 - loss: 1.6376
Epoch 2/43
17/17 - 0s - 22ms/step - accuracy: 0.6315 - loss: 1.1399
Epoch 3/43
17/17 - 0s - 22ms/step - accuracy: 0.6405 - loss: 1.0917
Epoch 4/43
17/17 - 0s - 22ms/step - accuracy: 0.6474 - loss: 1.0568
Epoch 5/43
17/17 - 0s - 21ms/step - accuracy: 0.6553 - loss: 1.0337
Epoch 6/43
17/17 - 0s - 22ms/step - accuracy: 0.6609 - loss: 1.0127
Epoch 7/43
17/17 - 0s - 22ms/step - accuracy: 0.6611 - loss: 0.9996
Epoch 8/43
17/17 - 0s - 22ms/step - accuracy: 0.6667 - loss: 0.9835
Epoch 9/43
17/17 - 0s - 22ms/step - accuracy: 0.6708 - loss: 0.9740
Epoch 10/43
17/17 - 0s - 22ms/step - accuracy: 0.6720 - loss: 0.9584
Epoch 11/43
17/17 - 0s - 22ms/step - accuracy: 0.6767 - loss: 0.9493
Epoch 12/43
17/17 - 0s - 22ms/step - accuracy: 0.6739 - loss: 0.9457
Epoch 13/43
17/17 - 0s - 22ms/step - accuracy: 0.6834 - loss: 0.9321
Epoch 14/43
17/17 - 0s - 22ms/step - accuracy: 0.6826 - loss: 0.9281
Epoch 15/43
17/17 - 0s - 23ms/step - accuracy: 0.6851 - loss: 0.9185
Epoch 16/43
17/17 - 0s - 22ms/step - accuracy: 0.6881 - loss: 0.9118
Epoch 17/43
17/17 - 0s - 22ms/step - accuracy: 0.6914 - loss: 0.9076
Epoch 18/43
17/17 - 0s - 22ms/step - accuracy: 0.6932 - loss: 0.8978
Epoch 19/43
17/17 - 0s - 22ms/step - accuracy: 0.6936 - loss: 0.8953
Epoch 20/43
17/17 - 0s - 22ms/step - accuracy: 0.6977 - loss: 0.8912
Epoch 21/43
17/17 - 0s - 22ms/step - accuracy: 0.6990 - loss: 0.8803
Epoch 22/43
17/17 - 0s - 22ms/step - accuracy: 0.7001 - loss: 0.8798
Epoch 23/43
17/17 - 0s - 22ms/step - accuracy: 0.7017 - loss: 0.8757
Epoch 24/43
17/17 - 0s - 22ms/step - accuracy: 0.7040 - loss: 0.8703
Epoch 25/43
17/17 - 0s - 22ms/step - accuracy: 0.7036 - loss: 0.8670
Epoch 26/43
17/17 - 0s - 22ms/step - accuracy: 0.7052 - loss: 0.8653
Epoch 27/43
17/17 - 0s - 22ms/step - accuracy: 0.7081 - loss: 0.8615
Epoch 28/43
17/17 - 0s - 22ms/step - accuracy: 0.7095 - loss: 0.8557
Epoch 29/43
17/17 - 0s - 22ms/step - accuracy: 0.7102 - loss: 0.8500
Epoch 30/43
17/17 - 0s - 22ms/step - accuracy: 0.7093 - loss: 0.8499
Epoch 31/43
17/17 - 0s - 22ms/step - accuracy: 0.7089 - loss: 0.8498
Epoch 32/43
17/17 - 0s - 22ms/step - accuracy: 0.7113 - loss: 0.8456
Epoch 33/43
17/17 - 0s - 22ms/step - accuracy: 0.7123 - loss: 0.8445
Epoch 34/43
17/17 - 0s - 22ms/step - accuracy: 0.7148 - loss: 0.8359
Epoch 35/43
17/17 - 0s - 22ms/step - accuracy: 0.7105 - loss: 0.8373
Epoch 36/43
17/17 - 0s - 22ms/step - accuracy: 0.7153 - loss: 0.8292
Epoch 37/43
17/17 - 0s - 22ms/step - accuracy: 0.7164 - loss: 0.8323
Epoch 38/43
17/17 - 0s - 22ms/step - accuracy: 0.7147 - loss: 0.8282
Epoch 39/43
17/17 - 0s - 22ms/step - accuracy: 0.7139 - loss: 0.8254
Epoch 40/43
17/17 - 0s - 22ms/step - accuracy: 0.7219 - loss: 0.8195
Epoch 41/43
17/17 - 0s - 22ms/step - accuracy: 0.7156 - loss: 0.8248
Epoch 42/43
17/17 - 0s - 22ms/step - accuracy: 0.7178 - loss: 0.8212
Epoch 43/43
17/17 - 0s - 22ms/step - accuracy: 0.7160 - loss: 0.8223
5/5 - 0s - 15ms/step
| 7         | 0.7289    | 0.0497    | 852.4     | 0.7069    | 0.2187    | 43.14     | 1.148     | 1.717     | 1.232     | 0.8645    | 66.1      | 0.3309    | 0.4449    |
Epoch 1/47

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 27ms/step - accuracy: 0.0260 - loss: 2.8107
Epoch 2/47
30/30 - 0s - 13ms/step - accuracy: 0.0257 - loss: 2.8049
Epoch 3/47
30/30 - 0s - 13ms/step - accuracy: 0.0257 - loss: 2.7953
Epoch 4/47
30/30 - 0s - 13ms/step - accuracy: 0.0312 - loss: 2.7886
Epoch 5/47
30/30 - 0s - 13ms/step - accuracy: 0.0306 - loss: 2.7823
Epoch 6/47
30/30 - 0s - 13ms/step - accuracy: 0.0322 - loss: 2.7754
Epoch 7/47
30/30 - 0s - 13ms/step - accuracy: 0.0338 - loss: 2.7683
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.0352 - loss: 2.7601
Epoch 9/47
30/30 - 0s - 13ms/step - accuracy: 0.0394 - loss: 2.7517
Epoch 10/47
30/30 - 0s - 13ms/step - accuracy: 0.0434 - loss: 2.7437
Epoch 11/47
30/30 - 0s - 13ms/step - accuracy: 0.0450 - loss: 2.7378
Epoch 12/47
30/30 - 0s - 14ms/step - accuracy: 0.0487 - loss: 2.7277
Epoch 13/47
30/30 - 0s - 14ms/step - accuracy: 0.0525 - loss: 2.7219
Epoch 14/47
30/30 - 0s - 13ms/step - accuracy: 0.0553 - loss: 2.7109
Epoch 15/47
30/30 - 0s - 13ms/step - accuracy: 0.0613 - loss: 2.7021
Epoch 16/47
30/30 - 0s - 13ms/step - accuracy: 0.0641 - loss: 2.6959
Epoch 17/47
30/30 - 0s - 13ms/step - accuracy: 0.0699 - loss: 2.6864
Epoch 18/47
30/30 - 0s - 13ms/step - accuracy: 0.0741 - loss: 2.6767
Epoch 19/47
30/30 - 0s - 13ms/step - accuracy: 0.0834 - loss: 2.6676
Epoch 20/47
30/30 - 0s - 13ms/step - accuracy: 0.0876 - loss: 2.6608
Epoch 21/47
30/30 - 0s - 13ms/step - accuracy: 0.0931 - loss: 2.6485
Epoch 22/47
30/30 - 0s - 13ms/step - accuracy: 0.1011 - loss: 2.6421
Epoch 23/47
30/30 - 0s - 13ms/step - accuracy: 0.1074 - loss: 2.6342
Epoch 24/47
30/30 - 0s - 13ms/step - accuracy: 0.1181 - loss: 2.6242
Epoch 25/47
30/30 - 0s - 13ms/step - accuracy: 0.1305 - loss: 2.6139
Epoch 26/47
30/30 - 0s - 13ms/step - accuracy: 0.1340 - loss: 2.6054
Epoch 27/47
30/30 - 0s - 13ms/step - accuracy: 0.1477 - loss: 2.5944
Epoch 28/47
30/30 - 0s - 13ms/step - accuracy: 0.1599 - loss: 2.5843
Epoch 29/47
30/30 - 0s - 13ms/step - accuracy: 0.1659 - loss: 2.5767
Epoch 30/47
30/30 - 0s - 13ms/step - accuracy: 0.1809 - loss: 2.5666
Epoch 31/47
30/30 - 0s - 13ms/step - accuracy: 0.1896 - loss: 2.5566
Epoch 32/47
30/30 - 0s - 13ms/step - accuracy: 0.2034 - loss: 2.5468
Epoch 33/47
30/30 - 0s - 13ms/step - accuracy: 0.2153 - loss: 2.5368
Epoch 34/47
30/30 - 0s - 13ms/step - accuracy: 0.2238 - loss: 2.5260
Epoch 35/47
30/30 - 0s - 13ms/step - accuracy: 0.2445 - loss: 2.5177
Epoch 36/47
30/30 - 0s - 13ms/step - accuracy: 0.2516 - loss: 2.5076
Epoch 37/47
30/30 - 0s - 13ms/step - accuracy: 0.2610 - loss: 2.4983
Epoch 38/47
30/30 - 0s - 13ms/step - accuracy: 0.2766 - loss: 2.4883
Epoch 39/47
30/30 - 0s - 12ms/step - accuracy: 0.2875 - loss: 2.4773
Epoch 40/47
30/30 - 0s - 12ms/step - accuracy: 0.3014 - loss: 2.4658
Epoch 41/47
30/30 - 0s - 12ms/step - accuracy: 0.3183 - loss: 2.4574
Epoch 42/47
30/30 - 0s - 12ms/step - accuracy: 0.3273 - loss: 2.4471
Epoch 43/47
30/30 - 0s - 12ms/step - accuracy: 0.3410 - loss: 2.4370
Epoch 44/47
30/30 - 0s - 12ms/step - accuracy: 0.3530 - loss: 2.4255
Epoch 45/47
30/30 - 0s - 12ms/step - accuracy: 0.3675 - loss: 2.4152
Epoch 46/47
30/30 - 0s - 12ms/step - accuracy: 0.3786 - loss: 2.4049
Epoch 47/47
30/30 - 0s - 12ms/step - accuracy: 0.3901 - loss: 2.3937
8/8 - 0s - 9ms/step
Epoch 1/47

/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/utils/transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 25ms/step - accuracy: 0.0170 - loss: 2.9023
Epoch 2/47
30/30 - 0s - 12ms/step - accuracy: 0.0165 - loss: 2.8962
Epoch 3/47
30/30 - 0s - 12ms/step - accuracy: 0.0174 - loss: 2.8898
Epoch 4/47
30/30 - 0s - 12ms/step - accuracy: 0.0168 - loss: 2.8840
Epoch 5/47
30/30 - 0s - 13ms/step - accuracy: 0.0171 - loss: 2.8771
Epoch 6/47
30/30 - 0s - 14ms/step - accuracy: 0.0175 - loss: 2.8696
Epoch 7/47
30/30 - 0s - 12ms/step - accuracy: 0.0179 - loss: 2.8627
Epoch 8/47
30/30 - 0s - 12ms/step - accuracy: 0.0198 - loss: 2.8566
Epoch 9/47
30/30 - 0s - 12ms/step - accuracy: 0.0207 - loss: 2.8477
Epoch 10/47
30/30 - 0s - 12ms/step - accuracy: 0.0208 - loss: 2.8411
Epoch 11/47
30/30 - 0s - 12ms/step - accuracy: 0.0214 - loss: 2.8337
Epoch 12/47
30/30 - 0s - 12ms/step - accuracy: 0.0221 - loss: 2.8262
Epoch 13/47
30/30 - 0s - 12ms/step - accuracy: 0.0221 - loss: 2.8187
Epoch 14/47
30/30 - 0s - 12ms/step - accuracy: 0.0244 - loss: 2.8100
Epoch 15/47
30/30 - 0s - 13ms/step - accuracy: 0.0259 - loss: 2.8032
Epoch 16/47
30/30 - 0s - 12ms/step - accuracy: 0.0251 - loss: 2.7936
Epoch 17/47
30/30 - 0s - 12ms/step - accuracy: 0.0285 - loss: 2.7858
Epoch 18/47
30/30 - 0s - 12ms/step - accuracy: 0.0312 - loss: 2.7782
Epoch 19/47
30/30 - 0s - 12ms/step - accuracy: 0.0311 - loss: 2.7695
Epoch 20/47
30/30 - 0s - 12ms/step - accuracy: 0.0346 - loss: 2.7617
Epoch 21/47
30/30 - 0s - 12ms/step - accuracy: 0.0352 - loss: 2.7549
Epoch 22/47
30/30 - 0s - 12ms/step - accuracy: 0.0406 - loss: 2.7450
Epoch 23/47
30/30 - 0s - 12ms/step - accuracy: 0.0433 - loss: 2.7354
Epoch 24/47
30/30 - 0s - 12ms/step - accuracy: 0.0447 - loss: 2.7277
Epoch 25/47
30/30 - 0s - 12ms/step - accuracy: 0.0458 - loss: 2.7203
Epoch 26/47
30/30 - 0s - 13ms/step - accuracy: 0.0532 - loss: 2.7098
Epoch 27/47
30/30 - 0s - 13ms/step - accuracy: 0.0581 - loss: 2.7007
Epoch 28/47
30/30 - 0s - 12ms/step - accuracy: 0.0579 - loss: 2.6937
Epoch 29/47
30/30 - 0s - 12ms/step - accuracy: 0.0682 - loss: 2.6835
Epoch 30/47
30/30 - 0s - 12ms/step - accuracy: 0.0771 - loss: 2.6746
Epoch 31/47
30/30 - 0s - 12ms/step - accuracy: 0.0854 - loss: 2.6652
Epoch 32/47
30/30 - 0s - 12ms/step - accuracy: 0.0901 - loss: 2.6561
Epoch 33/47
30/30 - 0s - 12ms/step - accuracy: 0.0986 - loss: 2.6460
Epoch 34/47
30/30 - 0s - 12ms/step - accuracy: 0.1137 - loss: 2.6371
Epoch 35/47
30/30 - 0s - 12ms/step - accuracy: 0.1169 - loss: 2.6275
Epoch 36/47
30/30 - 0s - 12ms/step - accuracy: 0.1230 - loss: 2.6198
Epoch 37/47
30/30 - 0s - 12ms/step - accuracy: 0.1378 - loss: 2.6094
Epoch 38/47
30/30 - 0s - 12ms/step - accuracy: 0.1471 - loss: 2.6014
Epoch 39/47
30/30 - 1s - 18ms/step - accuracy: 0.1571 - loss: 2.5909
Epoch 40/47
30/30 - 0s - 13ms/step - accuracy: 0.1766 - loss: 2.5805
Epoch 41/47
30/30 - 0s - 12ms/step - accuracy: 0.1817 - loss: 2.5718
Epoch 42/47
30/30 - 0s - 12ms/step - accuracy: 0.1956 - loss: 2.5615
Epoch 43/47
30/30 - 0s - 12ms/step - accuracy: 0.2122 - loss: 2.5516
Epoch 44/47
30/30 - 0s - 12ms/step - accuracy: 0.2296 - loss: 2.5407
Epoch 45/47
30/30 - 0s - 12ms/step - accuracy: 0.2402 - loss: 2.5312
Epoch 46/47
30/30 - 0s - 12ms/step - accuracy: 0.2547 - loss: 2.5220
Epoch 47/47
30/30 - 0s - 12ms/step - accuracy: 0.2753 - loss: 2.5105
8/8 - 0s - 9ms/step
Epoch 1/47

/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/utils/transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 26ms/step - accuracy: 0.2219 - loss: 2.5526
Epoch 2/47
30/30 - 0s - 12ms/step - accuracy: 0.2263 - loss: 2.5456
Epoch 3/47
30/30 - 0s - 12ms/step - accuracy: 0.2369 - loss: 2.5387
Epoch 4/47
30/30 - 0s - 12ms/step - accuracy: 0.2421 - loss: 2.5340
Epoch 5/47
30/30 - 0s - 12ms/step - accuracy: 0.2503 - loss: 2.5277
Epoch 6/47
30/30 - 0s - 12ms/step - accuracy: 0.2577 - loss: 2.5209
Epoch 7/47
30/30 - 0s - 12ms/step - accuracy: 0.2704 - loss: 2.5133
Epoch 8/47
30/30 - 0s - 12ms/step - accuracy: 0.2747 - loss: 2.5059
Epoch 9/47
30/30 - 0s - 12ms/step - accuracy: 0.2879 - loss: 2.4992
Epoch 10/47
30/30 - 0s - 12ms/step - accuracy: 0.2922 - loss: 2.4936
Epoch 11/47
30/30 - 0s - 12ms/step - accuracy: 0.3005 - loss: 2.4880
Epoch 12/47
30/30 - 0s - 12ms/step - accuracy: 0.3084 - loss: 2.4802
Epoch 13/47
30/30 - 0s - 12ms/step - accuracy: 0.3206 - loss: 2.4719
Epoch 14/47
30/30 - 0s - 13ms/step - accuracy: 0.3308 - loss: 2.4636
Epoch 15/47
30/30 - 0s - 13ms/step - accuracy: 0.3469 - loss: 2.4545
Epoch 16/47
30/30 - 0s - 12ms/step - accuracy: 0.3500 - loss: 2.4490
Epoch 17/47
30/30 - 0s - 12ms/step - accuracy: 0.3609 - loss: 2.4420
Epoch 18/47
30/30 - 0s - 12ms/step - accuracy: 0.3699 - loss: 2.4326
Epoch 19/47
30/30 - 0s - 13ms/step - accuracy: 0.3796 - loss: 2.4262
Epoch 20/47
30/30 - 0s - 12ms/step - accuracy: 0.3911 - loss: 2.4181
Epoch 21/47
30/30 - 0s - 13ms/step - accuracy: 0.4010 - loss: 2.4104
Epoch 22/47
30/30 - 0s - 13ms/step - accuracy: 0.4141 - loss: 2.4006
Epoch 23/47
30/30 - 0s - 12ms/step - accuracy: 0.4195 - loss: 2.3923
Epoch 24/47
30/30 - 0s - 12ms/step - accuracy: 0.4333 - loss: 2.3838
Epoch 25/47
30/30 - 0s - 12ms/step - accuracy: 0.4447 - loss: 2.3757
Epoch 26/47
30/30 - 0s - 12ms/step - accuracy: 0.4492 - loss: 2.3667
Epoch 27/47
30/30 - 0s - 12ms/step - accuracy: 0.4588 - loss: 2.3594
Epoch 28/47
30/30 - 0s - 12ms/step - accuracy: 0.4712 - loss: 2.3502
Epoch 29/47
30/30 - 0s - 12ms/step - accuracy: 0.4813 - loss: 2.3423
Epoch 30/47
30/30 - 0s - 12ms/step - accuracy: 0.4900 - loss: 2.3331
Epoch 31/47
30/30 - 0s - 12ms/step - accuracy: 0.4948 - loss: 2.3249
Epoch 32/47
30/30 - 0s - 13ms/step - accuracy: 0.5050 - loss: 2.3164
Epoch 33/47
30/30 - 0s - 12ms/step - accuracy: 0.5123 - loss: 2.3061
Epoch 34/47
30/30 - 0s - 13ms/step - accuracy: 0.5227 - loss: 2.2967
Epoch 35/47
30/30 - 0s - 12ms/step - accuracy: 0.5289 - loss: 2.2883
Epoch 36/47
30/30 - 0s - 12ms/step - accuracy: 0.5391 - loss: 2.2790
Epoch 37/47
30/30 - 0s - 12ms/step - accuracy: 0.5488 - loss: 2.2698
Epoch 38/47
30/30 - 0s - 12ms/step - accuracy: 0.5519 - loss: 2.2610
Epoch 39/47
30/30 - 0s - 13ms/step - accuracy: 0.5612 - loss: 2.2510
Epoch 40/47
30/30 - 0s - 13ms/step - accuracy: 0.5662 - loss: 2.2426
Epoch 41/47
30/30 - 0s - 13ms/step - accuracy: 0.5707 - loss: 2.2331
Epoch 42/47
30/30 - 0s - 12ms/step - accuracy: 0.5786 - loss: 2.2253
Epoch 43/47
30/30 - 0s - 14ms/step - accuracy: 0.5794 - loss: 2.2151
Epoch 44/47
30/30 - 0s - 12ms/step - accuracy: 0.5878 - loss: 2.2055
Epoch 45/47
30/30 - 0s - 12ms/step - accuracy: 0.5884 - loss: 2.1967
Epoch 46/47
30/30 - 0s - 12ms/step - accuracy: 0.5986 - loss: 2.1844
Epoch 47/47
30/30 - 0s - 13ms/step - accuracy: 0.6051 - loss: 2.1771
8/8 - 0s - 9ms/step
Epoch 1/47

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 26ms/step - accuracy: 0.0033 - loss: 2.9341
Epoch 2/47
30/30 - 0s - 13ms/step - accuracy: 0.0038 - loss: 2.9267
Epoch 3/47
30/30 - 0s - 12ms/step - accuracy: 0.0041 - loss: 2.9194
Epoch 4/47
30/30 - 0s - 12ms/step - accuracy: 0.0038 - loss: 2.9140
Epoch 5/47
30/30 - 0s - 13ms/step - accuracy: 0.0041 - loss: 2.9061
Epoch 6/47
30/30 - 0s - 12ms/step - accuracy: 0.0044 - loss: 2.8992
Epoch 7/47
30/30 - 0s - 12ms/step - accuracy: 0.0039 - loss: 2.8909
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.0041 - loss: 2.8827
Epoch 9/47
30/30 - 0s - 13ms/step - accuracy: 0.0055 - loss: 2.8734
Epoch 10/47
30/30 - 0s - 13ms/step - accuracy: 0.0049 - loss: 2.8690
Epoch 11/47
30/30 - 0s - 12ms/step - accuracy: 0.0060 - loss: 2.8607
Epoch 12/47
30/30 - 0s - 13ms/step - accuracy: 0.0049 - loss: 2.8511
Epoch 13/47
30/30 - 0s - 13ms/step - accuracy: 0.0057 - loss: 2.8429
Epoch 14/47
30/30 - 0s - 13ms/step - accuracy: 0.0056 - loss: 2.8330
Epoch 15/47
30/30 - 0s - 13ms/step - accuracy: 0.0062 - loss: 2.8253
Epoch 16/47
30/30 - 0s - 12ms/step - accuracy: 0.0074 - loss: 2.8163
Epoch 17/47
30/30 - 0s - 13ms/step - accuracy: 0.0082 - loss: 2.8081
Epoch 18/47
30/30 - 0s - 13ms/step - accuracy: 0.0080 - loss: 2.8000
Epoch 19/47
30/30 - 0s - 13ms/step - accuracy: 0.0090 - loss: 2.7907
Epoch 20/47
30/30 - 0s - 13ms/step - accuracy: 0.0092 - loss: 2.7812
Epoch 21/47
30/30 - 0s - 13ms/step - accuracy: 0.0105 - loss: 2.7741
Epoch 22/47
30/30 - 0s - 13ms/step - accuracy: 0.0128 - loss: 2.7654
Epoch 23/47
30/30 - 0s - 13ms/step - accuracy: 0.0164 - loss: 2.7547
Epoch 24/47
30/30 - 0s - 13ms/step - accuracy: 0.0148 - loss: 2.7460
Epoch 25/47
30/30 - 0s - 13ms/step - accuracy: 0.0163 - loss: 2.7352
Epoch 26/47
30/30 - 0s - 13ms/step - accuracy: 0.0214 - loss: 2.7264
Epoch 27/47
30/30 - 0s - 13ms/step - accuracy: 0.0232 - loss: 2.7188
Epoch 28/47
30/30 - 0s - 13ms/step - accuracy: 0.0259 - loss: 2.7064
Epoch 29/47
30/30 - 0s - 13ms/step - accuracy: 0.0301 - loss: 2.6980
Epoch 30/47
30/30 - 0s - 12ms/step - accuracy: 0.0354 - loss: 2.6869
Epoch 31/47
30/30 - 0s - 13ms/step - accuracy: 0.0420 - loss: 2.6777
Epoch 32/47
30/30 - 0s - 13ms/step - accuracy: 0.0483 - loss: 2.6666
Epoch 33/47
30/30 - 0s - 14ms/step - accuracy: 0.0524 - loss: 2.6581
Epoch 34/47
30/30 - 0s - 14ms/step - accuracy: 0.0607 - loss: 2.6492
Epoch 35/47
30/30 - 0s - 13ms/step - accuracy: 0.0693 - loss: 2.6393
Epoch 36/47
30/30 - 0s - 13ms/step - accuracy: 0.0754 - loss: 2.6281
Epoch 37/47
30/30 - 0s - 14ms/step - accuracy: 0.0873 - loss: 2.6172
Epoch 38/47
30/30 - 0s - 12ms/step - accuracy: 0.0972 - loss: 2.6073
Epoch 39/47
30/30 - 0s - 13ms/step - accuracy: 0.1076 - loss: 2.5972
Epoch 40/47
30/30 - 0s - 13ms/step - accuracy: 0.1207 - loss: 2.5868
Epoch 41/47
30/30 - 0s - 13ms/step - accuracy: 0.1342 - loss: 2.5777
Epoch 42/47
30/30 - 0s - 13ms/step - accuracy: 0.1484 - loss: 2.5658
Epoch 43/47
30/30 - 0s - 13ms/step - accuracy: 0.1615 - loss: 2.5564
Epoch 44/47
30/30 - 0s - 13ms/step - accuracy: 0.1818 - loss: 2.5456
Epoch 45/47
30/30 - 0s - 14ms/step - accuracy: 0.1910 - loss: 2.5345
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.2121 - loss: 2.5239
Epoch 47/47
30/30 - 0s - 16ms/step - accuracy: 0.2293 - loss: 2.5132
8/8 - 0s - 9ms/step
Epoch 1/47

/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/utils/transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 26ms/step - accuracy: 0.0220 - loss: 2.7745
Epoch 2/47
30/30 - 0s - 12ms/step - accuracy: 0.0244 - loss: 2.7686
Epoch 3/47
30/30 - 0s - 12ms/step - accuracy: 0.0265 - loss: 2.7602
Epoch 4/47
30/30 - 0s - 12ms/step - accuracy: 0.0266 - loss: 2.7539
Epoch 5/47
30/30 - 0s - 12ms/step - accuracy: 0.0291 - loss: 2.7483
Epoch 6/47
30/30 - 0s - 12ms/step - accuracy: 0.0328 - loss: 2.7389
Epoch 7/47
30/30 - 0s - 14ms/step - accuracy: 0.0369 - loss: 2.7317
Epoch 8/47
30/30 - 0s - 13ms/step - accuracy: 0.0386 - loss: 2.7242
Epoch 9/47
30/30 - 0s - 16ms/step - accuracy: 0.0439 - loss: 2.7170
Epoch 10/47
30/30 - 1s - 19ms/step - accuracy: 0.0447 - loss: 2.7093
Epoch 11/47
30/30 - 0s - 15ms/step - accuracy: 0.0495 - loss: 2.7006
Epoch 12/47
30/30 - 0s - 13ms/step - accuracy: 0.0519 - loss: 2.6945
Epoch 13/47
30/30 - 0s - 13ms/step - accuracy: 0.0548 - loss: 2.6867
Epoch 14/47
30/30 - 0s - 13ms/step - accuracy: 0.0592 - loss: 2.6782
Epoch 15/47
30/30 - 0s - 16ms/step - accuracy: 0.0670 - loss: 2.6689
Epoch 16/47
30/30 - 1s - 17ms/step - accuracy: 0.0712 - loss: 2.6615
Epoch 17/47
30/30 - 1s - 18ms/step - accuracy: 0.0748 - loss: 2.6525
Epoch 18/47
30/30 - 0s - 13ms/step - accuracy: 0.0867 - loss: 2.6459
Epoch 19/47
30/30 - 0s - 13ms/step - accuracy: 0.0882 - loss: 2.6361
Epoch 20/47
30/30 - 0s - 13ms/step - accuracy: 0.0988 - loss: 2.6263
Epoch 21/47
30/30 - 0s - 13ms/step - accuracy: 0.1065 - loss: 2.6184
Epoch 22/47
30/30 - 0s - 13ms/step - accuracy: 0.1166 - loss: 2.6093
Epoch 23/47
30/30 - 0s - 13ms/step - accuracy: 0.1204 - loss: 2.5999
Epoch 24/47
30/30 - 0s - 13ms/step - accuracy: 0.1301 - loss: 2.5921
Epoch 25/47
30/30 - 0s - 12ms/step - accuracy: 0.1505 - loss: 2.5801
Epoch 26/47
30/30 - 0s - 12ms/step - accuracy: 0.1481 - loss: 2.5741
Epoch 27/47
30/30 - 0s - 14ms/step - accuracy: 0.1644 - loss: 2.5633
Epoch 28/47
30/30 - 0s - 14ms/step - accuracy: 0.1733 - loss: 2.5544
Epoch 29/47
30/30 - 0s - 12ms/step - accuracy: 0.1838 - loss: 2.5446
Epoch 30/47
30/30 - 0s - 12ms/step - accuracy: 0.1994 - loss: 2.5350
Epoch 31/47
30/30 - 0s - 12ms/step - accuracy: 0.2093 - loss: 2.5249
Epoch 32/47
30/30 - 0s - 12ms/step - accuracy: 0.2232 - loss: 2.5151
Epoch 33/47
30/30 - 0s - 13ms/step - accuracy: 0.2330 - loss: 2.5068
Epoch 34/47
30/30 - 0s - 12ms/step - accuracy: 0.2462 - loss: 2.4972
Epoch 35/47
30/30 - 0s - 12ms/step - accuracy: 0.2605 - loss: 2.4872
Epoch 36/47
30/30 - 0s - 12ms/step - accuracy: 0.2655 - loss: 2.4774
Epoch 37/47
30/30 - 0s - 12ms/step - accuracy: 0.2796 - loss: 2.4684
Epoch 38/47
30/30 - 0s - 12ms/step - accuracy: 0.2950 - loss: 2.4581
Epoch 39/47
30/30 - 0s - 12ms/step - accuracy: 0.3029 - loss: 2.4493
Epoch 40/47
30/30 - 0s - 12ms/step - accuracy: 0.3220 - loss: 2.4376
Epoch 41/47
30/30 - 0s - 12ms/step - accuracy: 0.3386 - loss: 2.4258
Epoch 42/47
30/30 - 0s - 13ms/step - accuracy: 0.3415 - loss: 2.4182
Epoch 43/47
30/30 - 0s - 13ms/step - accuracy: 0.3558 - loss: 2.4080
Epoch 44/47
30/30 - 0s - 13ms/step - accuracy: 0.3613 - loss: 2.3970
Epoch 45/47
30/30 - 0s - 13ms/step - accuracy: 0.3833 - loss: 2.3865
Epoch 46/47
30/30 - 0s - 13ms/step - accuracy: 0.3921 - loss: 2.3754
Epoch 47/47
30/30 - 0s - 12ms/step - accuracy: 0.3984 - loss: 2.3663
8/8 - 0s - 10ms/step
| 8         | nan       | 2.799     | 460.1     | 0.7296    | 0.1913    | 46.62     | 1.944     | 1.239     | 2.426     | 0.7632    | 60.51     | 0.771     | 3.457     |
Epoch 1/21

/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:1011: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 137, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 345, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_scorer.py", line 87, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/_response.py", line 210, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scikeras/utils/transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/pipeline.py", line 948, in inverse_transform
    Xt = transform.inverse_transform(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py", line 1664, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 0s - 18ms/step - accuracy: 0.5135 - loss: 2.0432
Epoch 2/21
26/26 - 0s - 5ms/step - accuracy: 0.6762 - loss: 1.0396
Epoch 3/21
26/26 - 0s - 5ms/step - accuracy: 0.6902 - loss: 0.9600
Epoch 4/21
26/26 - 0s - 5ms/step - accuracy: 0.7012 - loss: 0.9263
Epoch 5/21
26/26 - 0s - 5ms/step - accuracy: 0.7070 - loss: 0.9012
Epoch 6/21
26/26 - 0s - 6ms/step - accuracy: 0.7116 - loss: 0.8810
Epoch 7/21
26/26 - 0s - 5ms/step - accuracy: 0.7142 - loss: 0.8654
Epoch 8/21
26/26 - 0s - 5ms/step - accuracy: 0.7189 - loss: 0.8505
Epoch 9/21
26/26 - 0s - 6ms/step - accuracy: 0.7239 - loss: 0.8370
Epoch 10/21
26/26 - 0s - 6ms/step - accuracy: 0.7269 - loss: 0.8249
Epoch 11/21
26/26 - 0s - 5ms/step - accuracy: 0.7287 - loss: 0.8143
Epoch 12/21
26/26 - 0s - 5ms/step - accuracy: 0.7311 - loss: 0.8036
Epoch 13/21
26/26 - 0s - 6ms/step - accuracy: 0.7351 - loss: 0.7929
Epoch 14/21
26/26 - 0s - 6ms/step - accuracy: 0.7364 - loss: 0.7850
Epoch 15/21
26/26 - 0s - 5ms/step - accuracy: 0.7392 - loss: 0.7749
Epoch 16/21
26/26 - 0s - 6ms/step - accuracy: 0.7405 - loss: 0.7663
Epoch 17/21
26/26 - 0s - 5ms/step - accuracy: 0.7460 - loss: 0.7581
Epoch 18/21
26/26 - 0s - 5ms/step - accuracy: 0.7451 - loss: 0.7499
Epoch 19/21
26/26 - 0s - 6ms/step - accuracy: 0.7492 - loss: 0.7450
Epoch 20/21
26/26 - 0s - 5ms/step - accuracy: 0.7505 - loss: 0.7374
Epoch 21/21
26/26 - 0s - 6ms/step - accuracy: 0.7531 - loss: 0.7283
7/7 - 0s - 8ms/step
Epoch 1/21

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 0s - 18ms/step - accuracy: 0.5366 - loss: 1.8544
Epoch 2/21
26/26 - 0s - 5ms/step - accuracy: 0.6446 - loss: 1.0359
Epoch 3/21
26/26 - 0s - 5ms/step - accuracy: 0.6694 - loss: 0.9447
Epoch 4/21
26/26 - 0s - 5ms/step - accuracy: 0.6759 - loss: 0.9048
Epoch 5/21
26/26 - 0s - 5ms/step - accuracy: 0.6865 - loss: 0.8785
Epoch 6/21
26/26 - 0s - 5ms/step - accuracy: 0.6942 - loss: 0.8580
Epoch 7/21
26/26 - 0s - 5ms/step - accuracy: 0.7019 - loss: 0.8417
Epoch 8/21
26/26 - 0s - 5ms/step - accuracy: 0.7031 - loss: 0.8280
Epoch 9/21
26/26 - 0s - 5ms/step - accuracy: 0.7083 - loss: 0.8157
Epoch 10/21
26/26 - 0s - 5ms/step - accuracy: 0.7120 - loss: 0.8046
Epoch 11/21
26/26 - 0s - 5ms/step - accuracy: 0.7166 - loss: 0.7937
Epoch 12/21
26/26 - 0s - 5ms/step - accuracy: 0.7221 - loss: 0.7845
Epoch 13/21
26/26 - 0s - 5ms/step - accuracy: 0.7238 - loss: 0.7747
Epoch 14/21
26/26 - 0s - 5ms/step - accuracy: 0.7290 - loss: 0.7640
Epoch 15/21
26/26 - 0s - 5ms/step - accuracy: 0.7306 - loss: 0.7566
Epoch 16/21
26/26 - 0s - 5ms/step - accuracy: 0.7341 - loss: 0.7479
Epoch 17/21
26/26 - 0s - 5ms/step - accuracy: 0.7393 - loss: 0.7393
Epoch 18/21
26/26 - 0s - 5ms/step - accuracy: 0.7412 - loss: 0.7329
Epoch 19/21
26/26 - 0s - 5ms/step - accuracy: 0.7446 - loss: 0.7247
Epoch 20/21
26/26 - 0s - 5ms/step - accuracy: 0.7473 - loss: 0.7176
Epoch 21/21
26/26 - 0s - 5ms/step - accuracy: 0.7492 - loss: 0.7110
7/7 - 0s - 8ms/step
Epoch 1/21

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 0s - 18ms/step - accuracy: 0.4919 - loss: 1.8458
Epoch 2/21
26/26 - 0s - 5ms/step - accuracy: 0.6456 - loss: 1.0587
Epoch 3/21
26/26 - 0s - 5ms/step - accuracy: 0.6693 - loss: 1.0001
Epoch 4/21
26/26 - 0s - 5ms/step - accuracy: 0.6792 - loss: 0.9684
Epoch 5/21
26/26 - 0s - 6ms/step - accuracy: 0.6895 - loss: 0.9449
Epoch 6/21
26/26 - 0s - 6ms/step - accuracy: 0.6932 - loss: 0.9242
Epoch 7/21
26/26 - 0s - 5ms/step - accuracy: 0.7004 - loss: 0.9060
Epoch 8/21
26/26 - 0s - 5ms/step - accuracy: 0.7062 - loss: 0.8896
Epoch 9/21
26/26 - 0s - 6ms/step - accuracy: 0.7145 - loss: 0.8718
Epoch 10/21
26/26 - 0s - 7ms/step - accuracy: 0.7198 - loss: 0.8571
Epoch 11/21
26/26 - 0s - 7ms/step - accuracy: 0.7249 - loss: 0.8419
Epoch 12/21
26/26 - 0s - 6ms/step - accuracy: 0.7300 - loss: 0.8260
Epoch 13/21
26/26 - 0s - 6ms/step - accuracy: 0.7356 - loss: 0.8135
Epoch 14/21
26/26 - 0s - 6ms/step - accuracy: 0.7388 - loss: 0.7984
Epoch 15/21
26/26 - 0s - 6ms/step - accuracy: 0.7458 - loss: 0.7855
Epoch 16/21
26/26 - 0s - 6ms/step - accuracy: 0.7479 - loss: 0.7747
Epoch 17/21
26/26 - 0s - 6ms/step - accuracy: 0.7507 - loss: 0.7649
Epoch 18/21
26/26 - 0s - 6ms/step - accuracy: 0.7550 - loss: 0.7529
Epoch 19/21
26/26 - 0s - 6ms/step - accuracy: 0.7573 - loss: 0.7437
Epoch 20/21
26/26 - 0s - 7ms/step - accuracy: 0.7588 - loss: 0.7355
Epoch 21/21
26/26 - 0s - 6ms/step - accuracy: 0.7614 - loss: 0.7255
7/7 - 0s - 8ms/step
Epoch 1/21

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 0s - 19ms/step - accuracy: 0.5376 - loss: 1.7424
Epoch 2/21
26/26 - 0s - 5ms/step - accuracy: 0.6663 - loss: 1.0698
Epoch 3/21
26/26 - 0s - 5ms/step - accuracy: 0.6744 - loss: 0.9817
Epoch 4/21
26/26 - 0s - 5ms/step - accuracy: 0.6826 - loss: 0.9401
Epoch 5/21
26/26 - 0s - 6ms/step - accuracy: 0.6915 - loss: 0.9126
Epoch 6/21
26/26 - 0s - 6ms/step - accuracy: 0.6992 - loss: 0.8887
Epoch 7/21
26/26 - 0s - 6ms/step - accuracy: 0.7042 - loss: 0.8688
Epoch 8/21
26/26 - 0s - 6ms/step - accuracy: 0.7098 - loss: 0.8527
Epoch 9/21
26/26 - 0s - 5ms/step - accuracy: 0.7140 - loss: 0.8370
Epoch 10/21
26/26 - 0s - 5ms/step - accuracy: 0.7184 - loss: 0.8235
Epoch 11/21
26/26 - 0s - 6ms/step - accuracy: 0.7242 - loss: 0.8111
Epoch 12/21
26/26 - 0s - 6ms/step - accuracy: 0.7277 - loss: 0.7986
Epoch 13/21
26/26 - 0s - 6ms/step - accuracy: 0.7309 - loss: 0.7893
Epoch 14/21
26/26 - 0s - 6ms/step - accuracy: 0.7374 - loss: 0.7775
Epoch 15/21
26/26 - 0s - 6ms/step - accuracy: 0.7386 - loss: 0.7675
Epoch 16/21
26/26 - 0s - 6ms/step - accuracy: 0.7429 - loss: 0.7591
Epoch 17/21
26/26 - 0s - 5ms/step - accuracy: 0.7447 - loss: 0.7506
Epoch 18/21
26/26 - 0s - 6ms/step - accuracy: 0.7495 - loss: 0.7415
Epoch 19/21
26/26 - 0s - 6ms/step - accuracy: 0.7516 - loss: 0.7333
Epoch 20/21
26/26 - 0s - 6ms/step - accuracy: 0.7536 - loss: 0.7259
Epoch 21/21
26/26 - 0s - 8ms/step - accuracy: 0.7570 - loss: 0.7181
7/7 - 0s - 9ms/step
Epoch 1/21

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 1s - 29ms/step - accuracy: 0.5421 - loss: 1.5594
Epoch 2/21
26/26 - 0s - 6ms/step - accuracy: 0.6653 - loss: 1.0041
Epoch 3/21
26/26 - 0s - 5ms/step - accuracy: 0.6808 - loss: 0.9400
Epoch 4/21
26/26 - 0s - 5ms/step - accuracy: 0.6919 - loss: 0.9001
Epoch 5/21
26/26 - 0s - 6ms/step - accuracy: 0.7031 - loss: 0.8691
Epoch 6/21
26/26 - 0s - 6ms/step - accuracy: 0.7134 - loss: 0.8407
Epoch 7/21
26/26 - 0s - 6ms/step - accuracy: 0.7235 - loss: 0.8177
Epoch 8/21
26/26 - 0s - 5ms/step - accuracy: 0.7280 - loss: 0.7958
Epoch 9/21
26/26 - 0s - 5ms/step - accuracy: 0.7354 - loss: 0.7761
Epoch 10/21
26/26 - 0s - 6ms/step - accuracy: 0.7416 - loss: 0.7596
Epoch 11/21
26/26 - 0s - 5ms/step - accuracy: 0.7473 - loss: 0.7438
Epoch 12/21
26/26 - 0s - 5ms/step - accuracy: 0.7511 - loss: 0.7297
Epoch 13/21
26/26 - 0s - 6ms/step - accuracy: 0.7553 - loss: 0.7181
Epoch 14/21
26/26 - 0s - 6ms/step - accuracy: 0.7583 - loss: 0.7062
Epoch 15/21
26/26 - 0s - 6ms/step - accuracy: 0.7634 - loss: 0.6957
Epoch 16/21
26/26 - 0s - 6ms/step - accuracy: 0.7664 - loss: 0.6861
Epoch 17/21
26/26 - 0s - 6ms/step - accuracy: 0.7664 - loss: 0.6773
Epoch 18/21
26/26 - 0s - 6ms/step - accuracy: 0.7722 - loss: 0.6689
Epoch 19/21
26/26 - 0s - 6ms/step - accuracy: 0.7732 - loss: 0.6603
Epoch 20/21
26/26 - 0s - 5ms/step - accuracy: 0.7773 - loss: 0.6523
Epoch 21/21
26/26 - 0s - 6ms/step - accuracy: 0.7772 - loss: 0.6449
7/7 - 0s - 8ms/step
| 9         | 0.7569    | 4.705     | 542.0     | 0.02542   | 0.03237   | 20.94     | 2.273     | 1.629     | 2.017     | 0.9085    | 32.44     | 0.4104    | 5.289     |
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 1s - 10ms/step - accuracy: 0.2718 - loss: 2.2911
Epoch 2/48
53/53 - 0s - 3ms/step - accuracy: 0.6441 - loss: 1.3931
Epoch 3/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.2480
Epoch 4/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.2007
Epoch 5/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1724
Epoch 6/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1523
Epoch 7/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1370
Epoch 8/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1252
Epoch 9/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1153
Epoch 10/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1071
Epoch 11/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1003
Epoch 12/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0944
Epoch 13/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0890
Epoch 14/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0843
Epoch 15/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0800
Epoch 16/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0766
Epoch 17/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0727
Epoch 18/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0700
Epoch 19/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0672
Epoch 20/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0646
Epoch 21/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0622
Epoch 22/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0598
Epoch 23/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0579
Epoch 24/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0566
Epoch 25/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0546
Epoch 26/48
53/53 - 0s - 4ms/step - accuracy: 0.6437 - loss: 1.0535
Epoch 27/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0521
Epoch 28/48
53/53 - 0s - 4ms/step - accuracy: 0.6436 - loss: 1.0508
Epoch 29/48
53/53 - 0s - 4ms/step - accuracy: 0.6437 - loss: 1.0493
Epoch 30/48
53/53 - 0s - 4ms/step - accuracy: 0.6437 - loss: 1.0480
Epoch 31/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0476
Epoch 32/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0460
Epoch 33/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0452
Epoch 34/48
53/53 - 0s - 4ms/step - accuracy: 0.6443 - loss: 1.0438
Epoch 35/48
53/53 - 0s - 4ms/step - accuracy: 0.6442 - loss: 1.0431
Epoch 36/48
53/53 - 0s - 4ms/step - accuracy: 0.6446 - loss: 1.0416
Epoch 37/48
53/53 - 0s - 4ms/step - accuracy: 0.6449 - loss: 1.0411
Epoch 38/48
53/53 - 0s - 4ms/step - accuracy: 0.6449 - loss: 1.0403
Epoch 39/48
53/53 - 0s - 4ms/step - accuracy: 0.6453 - loss: 1.0383
Epoch 40/48
53/53 - 0s - 4ms/step - accuracy: 0.6452 - loss: 1.0375
Epoch 41/48
53/53 - 0s - 4ms/step - accuracy: 0.6450 - loss: 1.0366
Epoch 42/48
53/53 - 0s - 4ms/step - accuracy: 0.6454 - loss: 1.0360
Epoch 43/48
53/53 - 0s - 4ms/step - accuracy: 0.6457 - loss: 1.0356
Epoch 44/48
53/53 - 0s - 4ms/step - accuracy: 0.6460 - loss: 1.0341
Epoch 45/48
53/53 - 0s - 4ms/step - accuracy: 0.6458 - loss: 1.0331
Epoch 46/48
53/53 - 0s - 4ms/step - accuracy: 0.6467 - loss: 1.0320
Epoch 47/48
53/53 - 0s - 4ms/step - accuracy: 0.6475 - loss: 1.0316
Epoch 48/48
53/53 - 0s - 4ms/step - accuracy: 0.6470 - loss: 1.0304
14/14 - 0s - 5ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 0s - 9ms/step - accuracy: 0.4575 - loss: 2.0660
Epoch 2/48
53/53 - 0s - 3ms/step - accuracy: 0.6440 - loss: 1.3738
Epoch 3/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.2570
Epoch 4/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.2118
Epoch 5/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1864
Epoch 6/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1695
Epoch 7/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1568
Epoch 8/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1469
Epoch 9/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1383
Epoch 10/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1307
Epoch 11/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1241
Epoch 12/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1177
Epoch 13/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1119
Epoch 14/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1065
Epoch 15/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1014
Epoch 16/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0965
Epoch 17/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0917
Epoch 18/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0875
Epoch 19/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0836
Epoch 20/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0797
Epoch 21/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0760
Epoch 22/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0724
Epoch 23/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0692
Epoch 24/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0663
Epoch 25/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0636
Epoch 26/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0608
Epoch 27/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0582
Epoch 28/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0558
Epoch 29/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0535
Epoch 30/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0516
Epoch 31/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0494
Epoch 32/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0471
Epoch 33/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0452
Epoch 34/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0435
Epoch 35/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0415
Epoch 36/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0403
Epoch 37/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0382
Epoch 38/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0365
Epoch 39/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0350
Epoch 40/48
53/53 - 0s - 4ms/step - accuracy: 0.6442 - loss: 1.0333
Epoch 41/48
53/53 - 0s - 4ms/step - accuracy: 0.6444 - loss: 1.0318
Epoch 42/48
53/53 - 0s - 4ms/step - accuracy: 0.6451 - loss: 1.0300
Epoch 43/48
53/53 - 0s - 4ms/step - accuracy: 0.6445 - loss: 1.0288
Epoch 44/48
53/53 - 0s - 4ms/step - accuracy: 0.6459 - loss: 1.0273
Epoch 45/48
53/53 - 0s - 4ms/step - accuracy: 0.6460 - loss: 1.0259
Epoch 46/48
53/53 - 0s - 4ms/step - accuracy: 0.6470 - loss: 1.0244
Epoch 47/48
53/53 - 0s - 4ms/step - accuracy: 0.6462 - loss: 1.0231
Epoch 48/48
53/53 - 0s - 4ms/step - accuracy: 0.6482 - loss: 1.0219
14/14 - 0s - 5ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 0s - 9ms/step - accuracy: 0.5415 - loss: 1.9571
Epoch 2/48
53/53 - 0s - 3ms/step - accuracy: 0.6439 - loss: 1.3449
Epoch 3/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.2275
Epoch 4/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1812
Epoch 5/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1558
Epoch 6/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1388
Epoch 7/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1262
Epoch 8/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1159
Epoch 9/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1079
Epoch 10/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1004
Epoch 11/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0940
Epoch 12/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0886
Epoch 13/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0839
Epoch 14/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0797
Epoch 15/48
53/53 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0757
Epoch 16/48
53/53 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0722
Epoch 17/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0691
Epoch 18/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0664
Epoch 19/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0641
Epoch 20/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0623
Epoch 21/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0598
Epoch 22/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0573
Epoch 23/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0557
Epoch 24/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0539
Epoch 25/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0520
Epoch 26/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0506
Epoch 27/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0491
Epoch 28/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0472
Epoch 29/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0451
Epoch 30/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0438
Epoch 31/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0419
Epoch 32/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0409
Epoch 33/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0389
Epoch 34/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0379
Epoch 35/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0362
Epoch 36/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0343
Epoch 37/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0325
Epoch 38/48
53/53 - 0s - 4ms/step - accuracy: 0.6442 - loss: 1.0311
Epoch 39/48
53/53 - 0s - 4ms/step - accuracy: 0.6447 - loss: 1.0292
Epoch 40/48
53/53 - 0s - 4ms/step - accuracy: 0.6450 - loss: 1.0279
Epoch 41/48
53/53 - 0s - 4ms/step - accuracy: 0.6455 - loss: 1.0258
Epoch 42/48
53/53 - 0s - 4ms/step - accuracy: 0.6460 - loss: 1.0243
Epoch 43/48
53/53 - 0s - 4ms/step - accuracy: 0.6476 - loss: 1.0223
Epoch 44/48
53/53 - 0s - 4ms/step - accuracy: 0.6479 - loss: 1.0212
Epoch 45/48
53/53 - 0s - 4ms/step - accuracy: 0.6492 - loss: 1.0192
Epoch 46/48
53/53 - 0s - 4ms/step - accuracy: 0.6500 - loss: 1.0168
Epoch 47/48
53/53 - 0s - 4ms/step - accuracy: 0.6519 - loss: 1.0148
Epoch 48/48
53/53 - 0s - 4ms/step - accuracy: 0.6524 - loss: 1.0135
14/14 - 0s - 5ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 0s - 9ms/step - accuracy: 0.6440 - loss: 1.6072
Epoch 2/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.2544
Epoch 3/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1841
Epoch 4/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1657
Epoch 5/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1563
Epoch 6/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1498
Epoch 7/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1441
Epoch 8/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1391
Epoch 9/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1341
Epoch 10/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1294
Epoch 11/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1247
Epoch 12/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1201
Epoch 13/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1151
Epoch 14/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1102
Epoch 15/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1051
Epoch 16/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0999
Epoch 17/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0950
Epoch 18/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0899
Epoch 19/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0846
Epoch 20/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0798
Epoch 21/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0750
Epoch 22/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0701
Epoch 23/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0658
Epoch 24/48
53/53 - 0s - 4ms/step - accuracy: 0.6437 - loss: 1.0612
Epoch 25/48
53/53 - 0s - 4ms/step - accuracy: 0.6434 - loss: 1.0571
Epoch 26/48
53/53 - 0s - 4ms/step - accuracy: 0.6436 - loss: 1.0529
Epoch 27/48
53/53 - 0s - 4ms/step - accuracy: 0.6428 - loss: 1.0493
Epoch 28/48
53/53 - 0s - 4ms/step - accuracy: 0.6426 - loss: 1.0454
Epoch 29/48
53/53 - 0s - 4ms/step - accuracy: 0.6428 - loss: 1.0415
Epoch 30/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0378
Epoch 31/48
53/53 - 0s - 4ms/step - accuracy: 0.6442 - loss: 1.0346
Epoch 32/48
53/53 - 0s - 4ms/step - accuracy: 0.6434 - loss: 1.0310
Epoch 33/48
53/53 - 0s - 4ms/step - accuracy: 0.6468 - loss: 1.0275
Epoch 34/48
53/53 - 0s - 4ms/step - accuracy: 0.6464 - loss: 1.0243
Epoch 35/48
53/53 - 0s - 4ms/step - accuracy: 0.6458 - loss: 1.0205
Epoch 36/48
53/53 - 0s - 4ms/step - accuracy: 0.6468 - loss: 1.0176
Epoch 37/48
53/53 - 0s - 4ms/step - accuracy: 0.6476 - loss: 1.0146
Epoch 38/48
53/53 - 0s - 4ms/step - accuracy: 0.6479 - loss: 1.0110
Epoch 39/48
53/53 - 0s - 4ms/step - accuracy: 0.6484 - loss: 1.0077
Epoch 40/48
53/53 - 0s - 4ms/step - accuracy: 0.6483 - loss: 1.0041
Epoch 41/48
53/53 - 0s - 4ms/step - accuracy: 0.6505 - loss: 1.0008
Epoch 42/48
53/53 - 0s - 4ms/step - accuracy: 0.6493 - loss: 0.9982
Epoch 43/48
53/53 - 0s - 4ms/step - accuracy: 0.6513 - loss: 0.9953
Epoch 44/48
53/53 - 0s - 5ms/step - accuracy: 0.6512 - loss: 0.9923
Epoch 45/48
53/53 - 0s - 4ms/step - accuracy: 0.6519 - loss: 0.9893
Epoch 46/48
53/53 - 0s - 4ms/step - accuracy: 0.6507 - loss: 0.9869
Epoch 47/48
53/53 - 0s - 4ms/step - accuracy: 0.6521 - loss: 0.9835
Epoch 48/48
53/53 - 0s - 4ms/step - accuracy: 0.6529 - loss: 0.9806
14/14 - 0s - 5ms/step
Epoch 1/48

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

53/53 - 0s - 9ms/step - accuracy: 0.4637 - loss: 2.0021
Epoch 2/48
53/53 - 0s - 3ms/step - accuracy: 0.6439 - loss: 1.3251
Epoch 3/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.2271
Epoch 4/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1949
Epoch 5/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1783
Epoch 6/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1675
Epoch 7/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1592
Epoch 8/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1525
Epoch 9/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1463
Epoch 10/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1407
Epoch 11/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1355
Epoch 12/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1304
Epoch 13/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1254
Epoch 14/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1204
Epoch 15/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1155
Epoch 16/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1112
Epoch 17/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1068
Epoch 18/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1024
Epoch 19/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0985
Epoch 20/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0946
Epoch 21/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0909
Epoch 22/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0873
Epoch 23/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0845
Epoch 24/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0813
Epoch 25/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0786
Epoch 26/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0762
Epoch 27/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0739
Epoch 28/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0714
Epoch 29/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0693
Epoch 30/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0677
Epoch 31/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0659
Epoch 32/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0648
Epoch 33/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0630
Epoch 34/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0620
Epoch 35/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0602
Epoch 36/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0596
Epoch 37/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0576
Epoch 38/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0563
Epoch 39/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0552
Epoch 40/48
53/53 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.0547
Epoch 41/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0536
Epoch 42/48
53/53 - 0s - 4ms/step - accuracy: 0.6438 - loss: 1.0523
Epoch 43/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0511
Epoch 44/48
53/53 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.0502
Epoch 45/48
53/53 - 0s - 4ms/step - accuracy: 0.6441 - loss: 1.0491
Epoch 46/48
53/53 - 0s - 4ms/step - accuracy: 0.6443 - loss: 1.0482
Epoch 47/48
53/53 - 0s - 4ms/step - accuracy: 0.6442 - loss: 1.0473
Epoch 48/48
53/53 - 0s - 4ms/step - accuracy: 0.6437 - loss: 1.0466
14/14 - 0s - 5ms/step
| 10        | 0.6509    | 2.059     | 261.6     | 0.2898    | 0.04837   | 47.89     | 2.616     | 2.267     | 2.743     | 0.8056    | 26.79     | 0.8926    | 3.775     |
Epoch 1/27

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 47ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 28ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 29ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 28ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 24ms/step
Epoch 1/27

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 46ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 28ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 23ms/step
Epoch 1/27

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 47ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
4/4 - 0s - 25ms/step
Epoch 1/27

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 48ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 25/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 26/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
Epoch 27/27
16/16 - 0s - 27ms/step - accuracy: 0.6440 - loss: nan
4/4 - 0s - 24ms/step
Epoch 1/27

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 1s - 46ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/27
16/16 - 0s - 26ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/27
16/16 - 1s - 37ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/27
16/16 - 0s - 29ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 25/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
Epoch 26/27
16/16 - 0s - 27ms/step - accuracy: 0.6439 - loss: nan
Epoch 27/27
16/16 - 0s - 28ms/step - accuracy: 0.6439 - loss: nan
4/4 - 0s - 27ms/step
| 11        | 0.644     | 7.267     | 916.9     | 0.318     | 0.03302   | 26.84     | 1.854     | 2.636     | 2.721     | 0.01688   | 55.97     | 0.4174    | 1.555     |
Epoch 1/36

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 0s - 14ms/step - accuracy: 0.5990 - loss: 1.4032
Epoch 2/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1698
Epoch 3/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1661
Epoch 4/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 5/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1648
Epoch 6/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1644
Epoch 7/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1653
Epoch 8/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1661
Epoch 9/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1651
Epoch 10/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1648
Epoch 11/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 12/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1639
Epoch 13/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1659
Epoch 14/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1653
Epoch 15/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1639
Epoch 16/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1639
Epoch 17/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1654
Epoch 18/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1650
Epoch 19/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1644
Epoch 20/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1646
Epoch 21/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1635
Epoch 22/36
30/30 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.1640
Epoch 23/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 24/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1633
Epoch 25/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1626
Epoch 26/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1628
Epoch 27/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1621
Epoch 28/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1615
Epoch 29/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1605
Epoch 30/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1571
Epoch 31/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1522
Epoch 32/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1392
Epoch 33/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1084
Epoch 34/36
30/30 - 0s - 5ms/step - accuracy: 0.6438 - loss: 1.0705
Epoch 35/36
30/30 - 0s - 5ms/step - accuracy: 0.6428 - loss: 1.0478
Epoch 36/36
30/30 - 0s - 5ms/step - accuracy: 0.6400 - loss: 1.0359
8/8 - 0s - 7ms/step
Epoch 1/36

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 0s - 14ms/step - accuracy: 0.5505 - loss: 1.5760
Epoch 2/36
30/30 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1732
Epoch 3/36
30/30 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1648
Epoch 4/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1662
Epoch 5/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 6/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 7/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1644
Epoch 8/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1662
Epoch 9/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 10/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1654
Epoch 11/36
30/30 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.1654
Epoch 12/36
30/30 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 13/36
30/30 - 0s - 6ms/step - accuracy: 0.6440 - loss: 1.1649
Epoch 14/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1636
Epoch 15/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1656
Epoch 16/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 17/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 18/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1640
Epoch 19/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1655
Epoch 20/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1647
Epoch 21/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 22/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 23/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 24/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1632
Epoch 25/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1639
Epoch 26/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1624
Epoch 27/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1630
Epoch 28/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1618
Epoch 29/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1589
Epoch 30/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1554
Epoch 31/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1466
Epoch 32/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1238
Epoch 33/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.0944
Epoch 34/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0663
Epoch 35/36
30/30 - 0s - 5ms/step - accuracy: 0.6441 - loss: 1.0515
Epoch 36/36
30/30 - 0s - 5ms/step - accuracy: 0.6438 - loss: 1.0418
8/8 - 0s - 7ms/step
Epoch 1/36

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 0s - 14ms/step - accuracy: 0.6439 - loss: 1.2515
Epoch 2/36
30/30 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1688
Epoch 3/36
30/30 - 0s - 4ms/step - accuracy: 0.6439 - loss: 1.1675
Epoch 4/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 5/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 6/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 7/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 8/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1667
Epoch 9/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1651
Epoch 10/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 11/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1652
Epoch 12/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1646
Epoch 13/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1654
Epoch 14/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1654
Epoch 15/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1641
Epoch 16/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1637
Epoch 17/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1637
Epoch 18/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1651
Epoch 19/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1643
Epoch 20/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1639
Epoch 21/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1625
Epoch 22/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1631
Epoch 23/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1617
Epoch 24/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1599
Epoch 25/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1554
Epoch 26/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1458
Epoch 27/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1229
Epoch 28/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0875
Epoch 29/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0560
Epoch 30/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.0377
Epoch 31/36
30/30 - 0s - 5ms/step - accuracy: 0.6381 - loss: 1.0252
Epoch 32/36
30/30 - 0s - 5ms/step - accuracy: 0.6405 - loss: 1.0159
Epoch 33/36
30/30 - 0s - 5ms/step - accuracy: 0.6401 - loss: 1.0057
Epoch 34/36
30/30 - 0s - 5ms/step - accuracy: 0.6405 - loss: 0.9964
Epoch 35/36
30/30 - 0s - 5ms/step - accuracy: 0.6412 - loss: 0.9867
Epoch 36/36
30/30 - 0s - 5ms/step - accuracy: 0.6402 - loss: 0.9787
8/8 - 0s - 7ms/step
Epoch 1/36

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 1s - 37ms/step - accuracy: 0.5994 - loss: 1.3474
Epoch 2/36
30/30 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1699
Epoch 3/36
30/30 - 0s - 4ms/step - accuracy: 0.6440 - loss: 1.1667
Epoch 4/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1665
Epoch 5/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1642
Epoch 6/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1667
Epoch 7/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1652
Epoch 8/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1671
Epoch 9/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1659
Epoch 10/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1650
Epoch 11/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1661
Epoch 12/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1645
Epoch 13/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1653
Epoch 14/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1644
Epoch 15/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1646
Epoch 16/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1643
Epoch 17/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1645
Epoch 18/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1640
Epoch 19/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1636
Epoch 20/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1629
Epoch 21/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1640
Epoch 22/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1623
Epoch 23/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1615
Epoch 24/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1591
Epoch 25/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1554
Epoch 26/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1464
Epoch 27/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.1271
Epoch 28/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.0955
Epoch 29/36
30/30 - 0s - 5ms/step - accuracy: 0.6432 - loss: 1.0693
Epoch 30/36
30/30 - 0s - 5ms/step - accuracy: 0.6420 - loss: 1.0520
Epoch 31/36
30/30 - 0s - 5ms/step - accuracy: 0.6415 - loss: 1.0422
Epoch 32/36
30/30 - 0s - 5ms/step - accuracy: 0.6400 - loss: 1.0330
Epoch 33/36
30/30 - 0s - 5ms/step - accuracy: 0.6383 - loss: 1.0272
Epoch 34/36
30/30 - 0s - 5ms/step - accuracy: 0.6372 - loss: 1.0198
Epoch 35/36
30/30 - 0s - 5ms/step - accuracy: 0.6365 - loss: 1.0122
Epoch 36/36
30/30 - 0s - 5ms/step - accuracy: 0.6405 - loss: 1.0043
8/8 - 0s - 7ms/step
Epoch 1/36

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

30/30 - 0s - 16ms/step - accuracy: 0.6219 - loss: 1.3416
Epoch 2/36
30/30 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.1705
Epoch 3/36
30/30 - 0s - 6ms/step - accuracy: 0.6439 - loss: 1.1662
Epoch 4/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1666
Epoch 5/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1659
Epoch 6/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1649
Epoch 7/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1664
Epoch 8/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1648
Epoch 9/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1661
Epoch 10/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1646
Epoch 11/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1657
Epoch 12/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1644
Epoch 13/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1650
Epoch 14/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1641
Epoch 15/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1642
Epoch 16/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1633
Epoch 17/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1630
Epoch 18/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1613
Epoch 19/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1590
Epoch 20/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1557
Epoch 21/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1474
Epoch 22/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.1278
Epoch 23/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 1.0958
Epoch 24/36
30/30 - 0s - 5ms/step - accuracy: 0.6440 - loss: 1.0644
Epoch 25/36
30/30 - 0s - 5ms/step - accuracy: 0.6378 - loss: 1.0446
Epoch 26/36
30/30 - 0s - 5ms/step - accuracy: 0.6339 - loss: 1.0359
Epoch 27/36
30/30 - 0s - 5ms/step - accuracy: 0.6306 - loss: 1.0270
Epoch 28/36
30/30 - 0s - 5ms/step - accuracy: 0.6354 - loss: 1.0185
Epoch 29/36
30/30 - 0s - 5ms/step - accuracy: 0.6321 - loss: 1.0107
Epoch 30/36
30/30 - 0s - 5ms/step - accuracy: 0.6366 - loss: 1.0008
Epoch 31/36
30/30 - 0s - 5ms/step - accuracy: 0.6385 - loss: 0.9917
Epoch 32/36
30/30 - 0s - 5ms/step - accuracy: 0.6439 - loss: 0.9820
Epoch 33/36
30/30 - 0s - 5ms/step - accuracy: 0.6436 - loss: 0.9714
Epoch 34/36
30/30 - 0s - 5ms/step - accuracy: 0.6397 - loss: 0.9643
Epoch 35/36
30/30 - 0s - 5ms/step - accuracy: 0.6438 - loss: 0.9526
Epoch 36/36
30/30 - 0s - 5ms/step - accuracy: 0.6418 - loss: 0.9455
8/8 - 0s - 7ms/step
| 12        | 0.6279    | 1.079     | 470.1     | 0.9429    | 0.09696   | 35.56     | 2.406     | 1.727     | 2.944     | 0.9628    | 32.66     | 0.4972    | 2.106     |
Epoch 1/22

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 12ms/step - accuracy: 0.6517 - loss: 1.1454
Epoch 2/22
60/60 - 0s - 7ms/step - accuracy: 0.7253 - loss: 0.7915
Epoch 3/22
60/60 - 0s - 7ms/step - accuracy: 0.7590 - loss: 0.6936
Epoch 4/22
60/60 - 0s - 7ms/step - accuracy: 0.7813 - loss: 0.6345
Epoch 5/22
60/60 - 0s - 7ms/step - accuracy: 0.7961 - loss: 0.5891
Epoch 6/22
60/60 - 0s - 7ms/step - accuracy: 0.8035 - loss: 0.5623
Epoch 7/22
60/60 - 0s - 7ms/step - accuracy: 0.8126 - loss: 0.5386
Epoch 8/22
60/60 - 0s - 7ms/step - accuracy: 0.8187 - loss: 0.5199
Epoch 9/22
60/60 - 0s - 7ms/step - accuracy: 0.8234 - loss: 0.5000
Epoch 10/22
60/60 - 0s - 7ms/step - accuracy: 0.8317 - loss: 0.4774
Epoch 11/22
60/60 - 0s - 7ms/step - accuracy: 0.8365 - loss: 0.4579
Epoch 12/22
60/60 - 0s - 7ms/step - accuracy: 0.8420 - loss: 0.4406
Epoch 13/22
60/60 - 0s - 7ms/step - accuracy: 0.8481 - loss: 0.4246
Epoch 14/22
60/60 - 0s - 7ms/step - accuracy: 0.8573 - loss: 0.4070
Epoch 15/22
60/60 - 0s - 7ms/step - accuracy: 0.8583 - loss: 0.4023
Epoch 16/22
60/60 - 0s - 7ms/step - accuracy: 0.8695 - loss: 0.3812
Epoch 17/22
60/60 - 0s - 7ms/step - accuracy: 0.8669 - loss: 0.3759
Epoch 18/22
60/60 - 0s - 7ms/step - accuracy: 0.8718 - loss: 0.3648
Epoch 19/22
60/60 - 0s - 7ms/step - accuracy: 0.8745 - loss: 0.3579
Epoch 20/22
60/60 - 0s - 7ms/step - accuracy: 0.8764 - loss: 0.3503
Epoch 21/22
60/60 - 0s - 7ms/step - accuracy: 0.8803 - loss: 0.3394
Epoch 22/22
60/60 - 0s - 7ms/step - accuracy: 0.8847 - loss: 0.3310
15/15 - 0s - 6ms/step
Epoch 1/22

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 12ms/step - accuracy: 0.6633 - loss: 1.0857
Epoch 2/22
60/60 - 0s - 8ms/step - accuracy: 0.7265 - loss: 0.7888
Epoch 3/22
60/60 - 0s - 7ms/step - accuracy: 0.7573 - loss: 0.7025
Epoch 4/22
60/60 - 0s - 7ms/step - accuracy: 0.7754 - loss: 0.6479
Epoch 5/22
60/60 - 0s - 7ms/step - accuracy: 0.7919 - loss: 0.5998
Epoch 6/22
60/60 - 0s - 7ms/step - accuracy: 0.8018 - loss: 0.5640
Epoch 7/22
60/60 - 0s - 7ms/step - accuracy: 0.8104 - loss: 0.5408
Epoch 8/22
60/60 - 0s - 7ms/step - accuracy: 0.8197 - loss: 0.5104
Epoch 9/22
60/60 - 0s - 7ms/step - accuracy: 0.8287 - loss: 0.4901
Epoch 10/22
60/60 - 0s - 7ms/step - accuracy: 0.8317 - loss: 0.4747
Epoch 11/22
60/60 - 0s - 7ms/step - accuracy: 0.8355 - loss: 0.4640
Epoch 12/22
60/60 - 0s - 7ms/step - accuracy: 0.8417 - loss: 0.4435
Epoch 13/22
60/60 - 0s - 7ms/step - accuracy: 0.8487 - loss: 0.4276
Epoch 14/22
60/60 - 0s - 7ms/step - accuracy: 0.8577 - loss: 0.4138
Epoch 15/22
60/60 - 0s - 7ms/step - accuracy: 0.8541 - loss: 0.4125
Epoch 16/22
60/60 - 0s - 7ms/step - accuracy: 0.8603 - loss: 0.3999
Epoch 17/22
60/60 - 0s - 7ms/step - accuracy: 0.8632 - loss: 0.3858
Epoch 18/22
60/60 - 0s - 7ms/step - accuracy: 0.8673 - loss: 0.3798
Epoch 19/22
60/60 - 0s - 7ms/step - accuracy: 0.8696 - loss: 0.3717
Epoch 20/22
60/60 - 0s - 7ms/step - accuracy: 0.8698 - loss: 0.3711
Epoch 21/22
60/60 - 0s - 7ms/step - accuracy: 0.8757 - loss: 0.3532
Epoch 22/22
60/60 - 0s - 7ms/step - accuracy: 0.8768 - loss: 0.3533
15/15 - 0s - 5ms/step
Epoch 1/22

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 12ms/step - accuracy: 0.6506 - loss: 1.1243
Epoch 2/22
60/60 - 0s - 7ms/step - accuracy: 0.7282 - loss: 0.7885
Epoch 3/22
60/60 - 0s - 7ms/step - accuracy: 0.7574 - loss: 0.7062
Epoch 4/22
60/60 - 0s - 7ms/step - accuracy: 0.7770 - loss: 0.6511
Epoch 5/22
60/60 - 0s - 7ms/step - accuracy: 0.7871 - loss: 0.6146
Epoch 6/22
60/60 - 0s - 7ms/step - accuracy: 0.7952 - loss: 0.5823
Epoch 7/22
60/60 - 0s - 7ms/step - accuracy: 0.8041 - loss: 0.5584
Epoch 8/22
60/60 - 0s - 7ms/step - accuracy: 0.8090 - loss: 0.5403
Epoch 9/22
60/60 - 0s - 7ms/step - accuracy: 0.8124 - loss: 0.5261
Epoch 10/22
60/60 - 0s - 7ms/step - accuracy: 0.8201 - loss: 0.5068
Epoch 11/22
60/60 - 0s - 7ms/step - accuracy: 0.8288 - loss: 0.4904
Epoch 12/22
60/60 - 0s - 7ms/step - accuracy: 0.8320 - loss: 0.4801
Epoch 13/22
60/60 - 0s - 7ms/step - accuracy: 0.8392 - loss: 0.4596
Epoch 14/22
60/60 - 0s - 7ms/step - accuracy: 0.8463 - loss: 0.4394
Epoch 15/22
60/60 - 0s - 7ms/step - accuracy: 0.8468 - loss: 0.4339
Epoch 16/22
60/60 - 0s - 7ms/step - accuracy: 0.8523 - loss: 0.4157
Epoch 17/22
60/60 - 0s - 7ms/step - accuracy: 0.8593 - loss: 0.4073
Epoch 18/22
60/60 - 0s - 8ms/step - accuracy: 0.8588 - loss: 0.4033
Epoch 19/22
60/60 - 0s - 7ms/step - accuracy: 0.8637 - loss: 0.3826
Epoch 20/22
60/60 - 0s - 7ms/step - accuracy: 0.8714 - loss: 0.3671
Epoch 21/22
60/60 - 0s - 7ms/step - accuracy: 0.8717 - loss: 0.3679
Epoch 22/22
60/60 - 0s - 7ms/step - accuracy: 0.8771 - loss: 0.3496
15/15 - 0s - 5ms/step
Epoch 1/22

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 12ms/step - accuracy: 0.6543 - loss: 1.1362
Epoch 2/22
60/60 - 0s - 7ms/step - accuracy: 0.7255 - loss: 0.8075
Epoch 3/22
60/60 - 0s - 7ms/step - accuracy: 0.7527 - loss: 0.7326
Epoch 4/22
60/60 - 0s - 7ms/step - accuracy: 0.7662 - loss: 0.6839
Epoch 5/22
60/60 - 0s - 7ms/step - accuracy: 0.7798 - loss: 0.6394
Epoch 6/22
60/60 - 0s - 7ms/step - accuracy: 0.7866 - loss: 0.6131
Epoch 7/22
60/60 - 0s - 7ms/step - accuracy: 0.7978 - loss: 0.5889
Epoch 8/22
60/60 - 0s - 7ms/step - accuracy: 0.8004 - loss: 0.5636
Epoch 9/22
60/60 - 0s - 7ms/step - accuracy: 0.8096 - loss: 0.5427
Epoch 10/22
60/60 - 0s - 7ms/step - accuracy: 0.8145 - loss: 0.5252
Epoch 11/22
60/60 - 0s - 7ms/step - accuracy: 0.8158 - loss: 0.5150
Epoch 12/22
60/60 - 0s - 7ms/step - accuracy: 0.8237 - loss: 0.4994
Epoch 13/22
60/60 - 0s - 7ms/step - accuracy: 0.8259 - loss: 0.4890
Epoch 14/22
60/60 - 0s - 7ms/step - accuracy: 0.8322 - loss: 0.4680
Epoch 15/22
60/60 - 0s - 7ms/step - accuracy: 0.8357 - loss: 0.4558
Epoch 16/22
60/60 - 0s - 7ms/step - accuracy: 0.8376 - loss: 0.4507
Epoch 17/22
60/60 - 0s - 7ms/step - accuracy: 0.8452 - loss: 0.4319
Epoch 18/22
60/60 - 0s - 7ms/step - accuracy: 0.8498 - loss: 0.4218
Epoch 19/22
60/60 - 0s - 7ms/step - accuracy: 0.8519 - loss: 0.4141
Epoch 20/22
60/60 - 0s - 7ms/step - accuracy: 0.8538 - loss: 0.4041
Epoch 21/22
60/60 - 0s - 7ms/step - accuracy: 0.8585 - loss: 0.3986
Epoch 22/22
60/60 - 0s - 7ms/step - accuracy: 0.8635 - loss: 0.3806
15/15 - 0s - 5ms/step
Epoch 1/22

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

60/60 - 1s - 12ms/step - accuracy: 0.6651 - loss: 1.1171
Epoch 2/22
60/60 - 0s - 7ms/step - accuracy: 0.7269 - loss: 0.8100
Epoch 3/22
60/60 - 0s - 7ms/step - accuracy: 0.7465 - loss: 0.7336
Epoch 4/22
60/60 - 0s - 7ms/step - accuracy: 0.7608 - loss: 0.6881
Epoch 5/22
60/60 - 0s - 7ms/step - accuracy: 0.7727 - loss: 0.6510
Epoch 6/22
60/60 - 0s - 7ms/step - accuracy: 0.7780 - loss: 0.6287
Epoch 7/22
60/60 - 0s - 7ms/step - accuracy: 0.7892 - loss: 0.5972
Epoch 8/22
60/60 - 0s - 7ms/step - accuracy: 0.7973 - loss: 0.5742
Epoch 9/22
60/60 - 0s - 7ms/step - accuracy: 0.8021 - loss: 0.5563
Epoch 10/22
60/60 - 0s - 8ms/step - accuracy: 0.8132 - loss: 0.5319
Epoch 11/22
60/60 - 0s - 7ms/step - accuracy: 0.8171 - loss: 0.5144
Epoch 12/22
60/60 - 0s - 7ms/step - accuracy: 0.8216 - loss: 0.5006
Epoch 13/22
60/60 - 0s - 7ms/step - accuracy: 0.8280 - loss: 0.4816
Epoch 14/22
60/60 - 0s - 7ms/step - accuracy: 0.8329 - loss: 0.4680
Epoch 15/22
60/60 - 0s - 7ms/step - accuracy: 0.8338 - loss: 0.4584
Epoch 16/22
60/60 - 0s - 7ms/step - accuracy: 0.8414 - loss: 0.4425
Epoch 17/22
60/60 - 0s - 7ms/step - accuracy: 0.8429 - loss: 0.4395
Epoch 18/22
60/60 - 0s - 7ms/step - accuracy: 0.8497 - loss: 0.4224
Epoch 19/22
60/60 - 0s - 7ms/step - accuracy: 0.8516 - loss: 0.4166
Epoch 20/22
60/60 - 0s - 7ms/step - accuracy: 0.8558 - loss: 0.4008
Epoch 21/22
60/60 - 0s - 7ms/step - accuracy: 0.8607 - loss: 0.3937
Epoch 22/22
60/60 - 0s - 7ms/step - accuracy: 0.8597 - loss: 0.3874
15/15 - 0s - 6ms/step
| 13        | 0.843     | 2.564     | 229.5     | 0.6096    | 0.1508    | 21.54     | 1.557     | 2.817     | 1.479     | 0.1534    | 54.05     | 0.9857    | 1.694     |
Epoch 1/31

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 1s - 58ms/step - accuracy: 0.6516 - loss: 1.1216
Epoch 2/31
18/18 - 1s - 36ms/step - accuracy: 0.7099 - loss: 0.8645
Epoch 3/31
18/18 - 1s - 37ms/step - accuracy: 0.7412 - loss: 0.7820
Epoch 4/31
18/18 - 1s - 37ms/step - accuracy: 0.7215 - loss: 0.8002
Epoch 5/31
18/18 - 1s - 37ms/step - accuracy: 0.7543 - loss: 0.7223
Epoch 6/31
18/18 - 1s - 37ms/step - accuracy: 0.7635 - loss: 0.6924
Epoch 7/31
18/18 - 1s - 37ms/step - accuracy: 0.7670 - loss: 0.6838
Epoch 8/31
18/18 - 1s - 37ms/step - accuracy: 0.7725 - loss: 0.6566
Epoch 9/31
18/18 - 1s - 37ms/step - accuracy: 0.7800 - loss: 0.6322
Epoch 10/31
18/18 - 1s - 37ms/step - accuracy: 0.7791 - loss: 0.6389
Epoch 11/31
18/18 - 1s - 38ms/step - accuracy: 0.7862 - loss: 0.6036
Epoch 12/31
18/18 - 1s - 37ms/step - accuracy: 0.7933 - loss: 0.5814
Epoch 13/31
18/18 - 1s - 38ms/step - accuracy: 0.8030 - loss: 0.5663
Epoch 14/31
18/18 - 1s - 37ms/step - accuracy: 0.7945 - loss: 0.5776
Epoch 15/31
18/18 - 1s - 37ms/step - accuracy: 0.8069 - loss: 0.5438
Epoch 16/31
18/18 - 1s - 40ms/step - accuracy: 0.8059 - loss: 0.5416
Epoch 17/31
18/18 - 1s - 38ms/step - accuracy: 0.8141 - loss: 0.5232
Epoch 18/31
18/18 - 1s - 38ms/step - accuracy: 0.8114 - loss: 0.5269
Epoch 19/31
18/18 - 1s - 38ms/step - accuracy: 0.8160 - loss: 0.5153
Epoch 20/31
18/18 - 1s - 37ms/step - accuracy: 0.8180 - loss: 0.5063
Epoch 21/31
18/18 - 1s - 37ms/step - accuracy: 0.8200 - loss: 0.4976
Epoch 22/31
18/18 - 1s - 37ms/step - accuracy: 0.8119 - loss: 0.5103
Epoch 23/31
18/18 - 1s - 37ms/step - accuracy: 0.8292 - loss: 0.4671
Epoch 24/31
18/18 - 1s - 37ms/step - accuracy: 0.8285 - loss: 0.4684
Epoch 25/31
18/18 - 1s - 38ms/step - accuracy: 0.8176 - loss: 0.5018
Epoch 26/31
18/18 - 1s - 38ms/step - accuracy: 0.8345 - loss: 0.4526
Epoch 27/31
18/18 - 1s - 38ms/step - accuracy: 0.8432 - loss: 0.4276
Epoch 28/31
18/18 - 1s - 37ms/step - accuracy: 0.8497 - loss: 0.4176
Epoch 29/31
18/18 - 1s - 38ms/step - accuracy: 0.8526 - loss: 0.4096
Epoch 30/31
18/18 - 1s - 37ms/step - accuracy: 0.8489 - loss: 0.4125
Epoch 31/31
18/18 - 1s - 37ms/step - accuracy: 0.8497 - loss: 0.4106
5/5 - 0s - 23ms/step
Epoch 1/31

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 1s - 57ms/step - accuracy: 0.5816 - loss: 1.3480
Epoch 2/31
18/18 - 1s - 37ms/step - accuracy: 0.6892 - loss: 0.9276
Epoch 3/31
18/18 - 1s - 37ms/step - accuracy: 0.7180 - loss: 0.8403
Epoch 4/31
18/18 - 1s - 37ms/step - accuracy: 0.7426 - loss: 0.7670
Epoch 5/31
18/18 - 1s - 37ms/step - accuracy: 0.7551 - loss: 0.7255
Epoch 6/31
18/18 - 1s - 37ms/step - accuracy: 0.7604 - loss: 0.7042
Epoch 7/31
18/18 - 1s - 38ms/step - accuracy: 0.7679 - loss: 0.6731
Epoch 8/31
18/18 - 1s - 40ms/step - accuracy: 0.7773 - loss: 0.6550
Epoch 9/31
18/18 - 1s - 38ms/step - accuracy: 0.7827 - loss: 0.6307
Epoch 10/31
18/18 - 1s - 38ms/step - accuracy: 0.7794 - loss: 0.6334
Epoch 11/31
18/18 - 1s - 38ms/step - accuracy: 0.7842 - loss: 0.6093
Epoch 12/31
18/18 - 1s - 38ms/step - accuracy: 0.7932 - loss: 0.5833
Epoch 13/31
18/18 - 1s - 38ms/step - accuracy: 0.7861 - loss: 0.5964
Epoch 14/31
18/18 - 1s - 38ms/step - accuracy: 0.7914 - loss: 0.5709
Epoch 15/31
18/18 - 1s - 38ms/step - accuracy: 0.8046 - loss: 0.5460
Epoch 16/31
18/18 - 1s - 38ms/step - accuracy: 0.8064 - loss: 0.5458
Epoch 17/31
18/18 - 1s - 38ms/step - accuracy: 0.8062 - loss: 0.5374
Epoch 18/31
18/18 - 1s - 38ms/step - accuracy: 0.8152 - loss: 0.5112
Epoch 19/31
18/18 - 1s - 38ms/step - accuracy: 0.7922 - loss: 0.5730
Epoch 20/31
18/18 - 1s - 38ms/step - accuracy: 0.8196 - loss: 0.5085
Epoch 21/31
18/18 - 1s - 38ms/step - accuracy: 0.8183 - loss: 0.5037
Epoch 22/31
18/18 - 1s - 38ms/step - accuracy: 0.8236 - loss: 0.4805
Epoch 23/31
18/18 - 1s - 38ms/step - accuracy: 0.8265 - loss: 0.4745
Epoch 24/31
18/18 - 1s - 38ms/step - accuracy: 0.8284 - loss: 0.4676
Epoch 25/31
18/18 - 1s - 38ms/step - accuracy: 0.8258 - loss: 0.4684
Epoch 26/31
18/18 - 1s - 38ms/step - accuracy: 0.8312 - loss: 0.4649
Epoch 27/31
18/18 - 1s - 38ms/step - accuracy: 0.8276 - loss: 0.4662
Epoch 28/31
18/18 - 1s - 38ms/step - accuracy: 0.8404 - loss: 0.4352
Epoch 29/31
18/18 - 1s - 38ms/step - accuracy: 0.8283 - loss: 0.4691
Epoch 30/31
18/18 - 1s - 38ms/step - accuracy: 0.8406 - loss: 0.4238
Epoch 31/31
18/18 - 1s - 40ms/step - accuracy: 0.8410 - loss: 0.4318
5/5 - 0s - 24ms/step
Epoch 1/31

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 1s - 57ms/step - accuracy: 0.5843 - loss: 1.3804
Epoch 2/31
18/18 - 1s - 36ms/step - accuracy: 0.6860 - loss: 0.9373
Epoch 3/31
18/18 - 1s - 36ms/step - accuracy: 0.7121 - loss: 0.8578
Epoch 4/31
18/18 - 1s - 36ms/step - accuracy: 0.7312 - loss: 0.8035
Epoch 5/31
18/18 - 1s - 37ms/step - accuracy: 0.7475 - loss: 0.7630
Epoch 6/31
18/18 - 1s - 37ms/step - accuracy: 0.7531 - loss: 0.7397
Epoch 7/31
18/18 - 1s - 37ms/step - accuracy: 0.7603 - loss: 0.7034
Epoch 8/31
18/18 - 1s - 37ms/step - accuracy: 0.7712 - loss: 0.6767
Epoch 9/31
18/18 - 1s - 37ms/step - accuracy: 0.7693 - loss: 0.6632
Epoch 10/31
18/18 - 1s - 37ms/step - accuracy: 0.7784 - loss: 0.6375
Epoch 11/31
18/18 - 1s - 37ms/step - accuracy: 0.7815 - loss: 0.6396
Epoch 12/31
18/18 - 1s - 37ms/step - accuracy: 0.7874 - loss: 0.6113
Epoch 13/31
18/18 - 1s - 37ms/step - accuracy: 0.7873 - loss: 0.5977
Epoch 14/31
18/18 - 1s - 37ms/step - accuracy: 0.7977 - loss: 0.5706
Epoch 15/31
18/18 - 1s - 37ms/step - accuracy: 0.8017 - loss: 0.5606
Epoch 16/31
18/18 - 1s - 37ms/step - accuracy: 0.7960 - loss: 0.5673
Epoch 17/31
18/18 - 1s - 37ms/step - accuracy: 0.8081 - loss: 0.5386
Epoch 18/31
18/18 - 1s - 37ms/step - accuracy: 0.8058 - loss: 0.5369
Epoch 19/31
18/18 - 1s - 37ms/step - accuracy: 0.7922 - loss: 0.5934
Epoch 20/31
18/18 - 1s - 37ms/step - accuracy: 0.8157 - loss: 0.5194
Epoch 21/31
18/18 - 1s - 39ms/step - accuracy: 0.8141 - loss: 0.5135
Epoch 22/31
18/18 - 1s - 43ms/step - accuracy: 0.8207 - loss: 0.4989
Epoch 23/31
18/18 - 1s - 41ms/step - accuracy: 0.8244 - loss: 0.4964
Epoch 24/31
18/18 - 1s - 42ms/step - accuracy: 0.8275 - loss: 0.4817
Epoch 25/31
18/18 - 1s - 41ms/step - accuracy: 0.8341 - loss: 0.4615
Epoch 26/31
18/18 - 1s - 41ms/step - accuracy: 0.8281 - loss: 0.4635
Epoch 27/31
18/18 - 1s - 40ms/step - accuracy: 0.8399 - loss: 0.4460
Epoch 28/31
18/18 - 1s - 40ms/step - accuracy: 0.8324 - loss: 0.4677
Epoch 29/31
18/18 - 1s - 40ms/step - accuracy: 0.8390 - loss: 0.4469
Epoch 30/31
18/18 - 1s - 39ms/step - accuracy: 0.8402 - loss: 0.4437
Epoch 31/31
18/18 - 1s - 39ms/step - accuracy: 0.8375 - loss: 0.4512
5/5 - 0s - 23ms/step
Epoch 1/31

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 1s - 57ms/step - accuracy: 0.6402 - loss: 1.1223
Epoch 2/31
18/18 - 1s - 37ms/step - accuracy: 0.7011 - loss: 0.9030
Epoch 3/31
18/18 - 1s - 37ms/step - accuracy: 0.7301 - loss: 0.8144
Epoch 4/31
18/18 - 1s - 39ms/step - accuracy: 0.7470 - loss: 0.7567
Epoch 5/31
18/18 - 1s - 39ms/step - accuracy: 0.7455 - loss: 0.7368
Epoch 6/31
18/18 - 1s - 40ms/step - accuracy: 0.7677 - loss: 0.7001
Epoch 7/31
18/18 - 1s - 40ms/step - accuracy: 0.7720 - loss: 0.6702
Epoch 8/31
18/18 - 1s - 40ms/step - accuracy: 0.7710 - loss: 0.6621
Epoch 9/31
18/18 - 1s - 40ms/step - accuracy: 0.7850 - loss: 0.6273
Epoch 10/31
18/18 - 1s - 40ms/step - accuracy: 0.7737 - loss: 0.6438
Epoch 11/31
18/18 - 1s - 40ms/step - accuracy: 0.7929 - loss: 0.5959
Epoch 12/31
18/18 - 1s - 40ms/step - accuracy: 0.7964 - loss: 0.5891
Epoch 13/31
18/18 - 1s - 40ms/step - accuracy: 0.8024 - loss: 0.5578
Epoch 14/31
18/18 - 1s - 43ms/step - accuracy: 0.7976 - loss: 0.5641
Epoch 15/31
18/18 - 1s - 41ms/step - accuracy: 0.7999 - loss: 0.5457
Epoch 16/31
18/18 - 1s - 40ms/step - accuracy: 0.8126 - loss: 0.5254
Epoch 17/31
18/18 - 1s - 40ms/step - accuracy: 0.8156 - loss: 0.5119
Epoch 18/31
18/18 - 1s - 40ms/step - accuracy: 0.8140 - loss: 0.5177
Epoch 19/31
18/18 - 1s - 40ms/step - accuracy: 0.8160 - loss: 0.5052
Epoch 20/31
18/18 - 1s - 40ms/step - accuracy: 0.8194 - loss: 0.5004
Epoch 21/31
18/18 - 1s - 40ms/step - accuracy: 0.8283 - loss: 0.4765
Epoch 22/31
18/18 - 1s - 40ms/step - accuracy: 0.8303 - loss: 0.4639
Epoch 23/31
18/18 - 1s - 40ms/step - accuracy: 0.8237 - loss: 0.4821
Epoch 24/31
18/18 - 1s - 40ms/step - accuracy: 0.8298 - loss: 0.4710
Epoch 25/31
18/18 - 1s - 41ms/step - accuracy: 0.8255 - loss: 0.4745
Epoch 26/31
18/18 - 1s - 40ms/step - accuracy: 0.8439 - loss: 0.4305
Epoch 27/31
18/18 - 1s - 40ms/step - accuracy: 0.8512 - loss: 0.4101
Epoch 28/31
18/18 - 1s - 40ms/step - accuracy: 0.8461 - loss: 0.4195
Epoch 29/31
18/18 - 1s - 41ms/step - accuracy: 0.8444 - loss: 0.4224
Epoch 30/31
18/18 - 1s - 41ms/step - accuracy: 0.8555 - loss: 0.3936
Epoch 31/31
18/18 - 1s - 41ms/step - accuracy: 0.8587 - loss: 0.3900
5/5 - 0s - 24ms/step
Epoch 1/31

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 - 1s - 58ms/step - accuracy: 0.5810 - loss: 1.3645
Epoch 2/31
18/18 - 1s - 39ms/step - accuracy: 0.6878 - loss: 0.9349
Epoch 3/31
18/18 - 1s - 40ms/step - accuracy: 0.7180 - loss: 0.8485
Epoch 4/31
18/18 - 1s - 42ms/step - accuracy: 0.7340 - loss: 0.7881
Epoch 5/31
18/18 - 1s - 44ms/step - accuracy: 0.7399 - loss: 0.7723
Epoch 6/31
18/18 - 1s - 48ms/step - accuracy: 0.7436 - loss: 0.7481
Epoch 7/31
18/18 - 1s - 46ms/step - accuracy: 0.7546 - loss: 0.7166
Epoch 8/31
18/18 - 1s - 43ms/step - accuracy: 0.7680 - loss: 0.6836
Epoch 9/31
18/18 - 1s - 42ms/step - accuracy: 0.7675 - loss: 0.6771
Epoch 10/31
18/18 - 1s - 41ms/step - accuracy: 0.7732 - loss: 0.6577
Epoch 11/31
18/18 - 1s - 42ms/step - accuracy: 0.7841 - loss: 0.6206
Epoch 12/31
18/18 - 1s - 42ms/step - accuracy: 0.7780 - loss: 0.6250
Epoch 13/31
18/18 - 1s - 42ms/step - accuracy: 0.7916 - loss: 0.5930
Epoch 14/31
18/18 - 1s - 42ms/step - accuracy: 0.7944 - loss: 0.5799
Epoch 15/31
18/18 - 1s - 42ms/step - accuracy: 0.7971 - loss: 0.5709
Epoch 16/31
18/18 - 1s - 42ms/step - accuracy: 0.7978 - loss: 0.5665
Epoch 17/31
18/18 - 1s - 42ms/step - accuracy: 0.8047 - loss: 0.5440
Epoch 18/31
18/18 - 1s - 42ms/step - accuracy: 0.8070 - loss: 0.5361
Epoch 19/31
18/18 - 1s - 43ms/step - accuracy: 0.8132 - loss: 0.5188
Epoch 20/31
18/18 - 1s - 42ms/step - accuracy: 0.8057 - loss: 0.5396
Epoch 21/31
18/18 - 1s - 42ms/step - accuracy: 0.8200 - loss: 0.5032
Epoch 22/31
18/18 - 1s - 42ms/step - accuracy: 0.8268 - loss: 0.4796
Epoch 23/31
18/18 - 1s - 43ms/step - accuracy: 0.8298 - loss: 0.4692
Epoch 24/31
18/18 - 1s - 44ms/step - accuracy: 0.8344 - loss: 0.4587
Epoch 25/31
18/18 - 1s - 45ms/step - accuracy: 0.8264 - loss: 0.4756
Epoch 26/31
18/18 - 1s - 43ms/step - accuracy: 0.8301 - loss: 0.4591
Epoch 27/31
18/18 - 1s - 42ms/step - accuracy: 0.8275 - loss: 0.4812
Epoch 28/31
18/18 - 1s - 42ms/step - accuracy: 0.8359 - loss: 0.4539
Epoch 29/31
18/18 - 1s - 42ms/step - accuracy: 0.8402 - loss: 0.4367
Epoch 30/31
18/18 - 1s - 42ms/step - accuracy: 0.8405 - loss: 0.4357
Epoch 31/31
18/18 - 1s - 42ms/step - accuracy: 0.8487 - loss: 0.4144
5/5 - 0s - 24ms/step
| 14        | 0.8101    | 6.049     | 809.3     | 0.2376    | 0.2185    | 31.03     | 2.265     | 2.267     | 2.072     | 0.09939   | 85.18     | 0.3208    | 1.306     |
Epoch 1/35

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 1s - 32ms/step - accuracy: 0.5821 - loss: 1.5155
Epoch 2/35
21/21 - 0s - 12ms/step - accuracy: 0.6382 - loss: 1.0231
Epoch 3/35
21/21 - 0s - 12ms/step - accuracy: 0.6768 - loss: 0.9244
Epoch 4/35
21/21 - 0s - 14ms/step - accuracy: 0.7056 - loss: 0.8480
Epoch 5/35
21/21 - 0s - 14ms/step - accuracy: 0.7245 - loss: 0.7877
Epoch 6/35
21/21 - 0s - 14ms/step - accuracy: 0.7363 - loss: 0.7457
Epoch 7/35
21/21 - 0s - 13ms/step - accuracy: 0.7505 - loss: 0.7074
Epoch 8/35
21/21 - 0s - 14ms/step - accuracy: 0.7624 - loss: 0.6756
Epoch 9/35
21/21 - 0s - 14ms/step - accuracy: 0.7749 - loss: 0.6423
Epoch 10/35
21/21 - 0s - 13ms/step - accuracy: 0.7830 - loss: 0.6103
Epoch 11/35
21/21 - 0s - 13ms/step - accuracy: 0.7953 - loss: 0.5739
Epoch 12/35
21/21 - 0s - 15ms/step - accuracy: 0.8046 - loss: 0.5414
Epoch 13/35
21/21 - 0s - 15ms/step - accuracy: 0.8155 - loss: 0.5108
Epoch 14/35
21/21 - 0s - 14ms/step - accuracy: 0.8284 - loss: 0.4772
Epoch 15/35
21/21 - 0s - 14ms/step - accuracy: 0.8378 - loss: 0.4479
Epoch 16/35
21/21 - 0s - 13ms/step - accuracy: 0.8511 - loss: 0.4200
Epoch 17/35
21/21 - 0s - 14ms/step - accuracy: 0.8585 - loss: 0.4016
Epoch 18/35
21/21 - 0s - 14ms/step - accuracy: 0.8682 - loss: 0.3787
Epoch 19/35
21/21 - 0s - 19ms/step - accuracy: 0.8728 - loss: 0.3628
Epoch 20/35
21/21 - 0s - 14ms/step - accuracy: 0.8720 - loss: 0.3601
Epoch 21/35
21/21 - 0s - 14ms/step - accuracy: 0.8852 - loss: 0.3328
Epoch 22/35
21/21 - 0s - 14ms/step - accuracy: 0.8886 - loss: 0.3217
Epoch 23/35
21/21 - 0s - 13ms/step - accuracy: 0.8953 - loss: 0.3066
Epoch 24/35
21/21 - 0s - 13ms/step - accuracy: 0.9017 - loss: 0.2866
Epoch 25/35
21/21 - 0s - 16ms/step - accuracy: 0.9014 - loss: 0.2795
Epoch 26/35
21/21 - 0s - 15ms/step - accuracy: 0.9021 - loss: 0.2794
Epoch 27/35
21/21 - 0s - 14ms/step - accuracy: 0.9058 - loss: 0.2685
Epoch 28/35
21/21 - 0s - 18ms/step - accuracy: 0.9102 - loss: 0.2583
Epoch 29/35
21/21 - 0s - 15ms/step - accuracy: 0.9157 - loss: 0.2451
Epoch 30/35
21/21 - 0s - 14ms/step - accuracy: 0.9197 - loss: 0.2352
Epoch 31/35
21/21 - 0s - 13ms/step - accuracy: 0.9228 - loss: 0.2260
Epoch 32/35
21/21 - 0s - 14ms/step - accuracy: 0.9265 - loss: 0.2117
Epoch 33/35
21/21 - 0s - 17ms/step - accuracy: 0.9269 - loss: 0.2088
Epoch 34/35
21/21 - 0s - 13ms/step - accuracy: 0.9293 - loss: 0.2066
Epoch 35/35
21/21 - 0s - 15ms/step - accuracy: 0.9270 - loss: 0.2119
6/6 - 0s - 13ms/step
Epoch 1/35

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 1s - 33ms/step - accuracy: 0.5007 - loss: 1.6824
Epoch 2/35
21/21 - 0s - 12ms/step - accuracy: 0.6532 - loss: 1.0173
Epoch 3/35
21/21 - 0s - 12ms/step - accuracy: 0.6848 - loss: 0.9049
Epoch 4/35
21/21 - 0s - 12ms/step - accuracy: 0.7067 - loss: 0.8394
Epoch 5/35
21/21 - 0s - 13ms/step - accuracy: 0.7248 - loss: 0.7935
Epoch 6/35
21/21 - 0s - 13ms/step - accuracy: 0.7356 - loss: 0.7588
Epoch 7/35
21/21 - 0s - 13ms/step - accuracy: 0.7473 - loss: 0.7245
Epoch 8/35
21/21 - 0s - 15ms/step - accuracy: 0.7574 - loss: 0.6938
Epoch 9/35
21/21 - 0s - 15ms/step - accuracy: 0.7677 - loss: 0.6667
Epoch 10/35
21/21 - 0s - 13ms/step - accuracy: 0.7789 - loss: 0.6364
Epoch 11/35
21/21 - 0s - 13ms/step - accuracy: 0.7892 - loss: 0.6046
Epoch 12/35
21/21 - 0s - 14ms/step - accuracy: 0.8009 - loss: 0.5696
Epoch 13/35
21/21 - 0s - 13ms/step - accuracy: 0.8112 - loss: 0.5424
Epoch 14/35
21/21 - 0s - 13ms/step - accuracy: 0.8210 - loss: 0.5140
Epoch 15/35
21/21 - 0s - 21ms/step - accuracy: 0.8294 - loss: 0.4865
Epoch 16/35
21/21 - 0s - 15ms/step - accuracy: 0.8381 - loss: 0.4571
Epoch 17/35
21/21 - 0s - 14ms/step - accuracy: 0.8438 - loss: 0.4353
Epoch 18/35
21/21 - 0s - 14ms/step - accuracy: 0.8523 - loss: 0.4188
Epoch 19/35
21/21 - 0s - 13ms/step - accuracy: 0.8587 - loss: 0.3990
Epoch 20/35
21/21 - 0s - 13ms/step - accuracy: 0.8628 - loss: 0.3852
Epoch 21/35
21/21 - 0s - 13ms/step - accuracy: 0.8686 - loss: 0.3708
Epoch 22/35
21/21 - 0s - 15ms/step - accuracy: 0.8700 - loss: 0.3682
Epoch 23/35
21/21 - 0s - 14ms/step - accuracy: 0.8720 - loss: 0.3598
Epoch 24/35
21/21 - 0s - 15ms/step - accuracy: 0.8782 - loss: 0.3453
Epoch 25/35
21/21 - 0s - 21ms/step - accuracy: 0.8824 - loss: 0.3322
Epoch 26/35
21/21 - 0s - 24ms/step - accuracy: 0.8854 - loss: 0.3257
Epoch 27/35
21/21 - 0s - 15ms/step - accuracy: 0.8882 - loss: 0.3220
Epoch 28/35
21/21 - 0s - 18ms/step - accuracy: 0.8890 - loss: 0.3180
Epoch 29/35
21/21 - 1s - 31ms/step - accuracy: 0.8948 - loss: 0.3000
Epoch 30/35
21/21 - 0s - 23ms/step - accuracy: 0.8907 - loss: 0.3081
Epoch 31/35
21/21 - 0s - 17ms/step - accuracy: 0.8969 - loss: 0.2934
Epoch 32/35
21/21 - 0s - 15ms/step - accuracy: 0.8996 - loss: 0.2866
Epoch 33/35
21/21 - 0s - 15ms/step - accuracy: 0.9004 - loss: 0.2809
Epoch 34/35
21/21 - 0s - 14ms/step - accuracy: 0.9074 - loss: 0.2729
Epoch 35/35
21/21 - 0s - 14ms/step - accuracy: 0.9051 - loss: 0.2673
6/6 - 0s - 12ms/step
Epoch 1/35

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 1s - 32ms/step - accuracy: 0.5525 - loss: 1.4200
Epoch 2/35
21/21 - 0s - 14ms/step - accuracy: 0.6557 - loss: 0.9725
Epoch 3/35
21/21 - 0s - 15ms/step - accuracy: 0.6829 - loss: 0.9069
Epoch 4/35
21/21 - 0s - 13ms/step - accuracy: 0.7076 - loss: 0.8511
Epoch 5/35
21/21 - 0s - 13ms/step - accuracy: 0.7224 - loss: 0.8038
Epoch 6/35
21/21 - 0s - 13ms/step - accuracy: 0.7340 - loss: 0.7611
Epoch 7/35
21/21 - 0s - 14ms/step - accuracy: 0.7437 - loss: 0.7255
Epoch 8/35
21/21 - 0s - 14ms/step - accuracy: 0.7565 - loss: 0.6901
Epoch 9/35
21/21 - 0s - 13ms/step - accuracy: 0.7675 - loss: 0.6559
Epoch 10/35
21/21 - 0s - 14ms/step - accuracy: 0.7775 - loss: 0.6227
Epoch 11/35
21/21 - 0s - 13ms/step - accuracy: 0.7878 - loss: 0.5893
Epoch 12/35
21/21 - 0s - 13ms/step - accuracy: 0.8029 - loss: 0.5596
Epoch 13/35
21/21 - 0s - 15ms/step - accuracy: 0.8113 - loss: 0.5313
Epoch 14/35
21/21 - 0s - 17ms/step - accuracy: 0.8203 - loss: 0.5070
Epoch 15/35
21/21 - 0s - 17ms/step - accuracy: 0.8293 - loss: 0.4794
Epoch 16/35
21/21 - 0s - 14ms/step - accuracy: 0.8344 - loss: 0.4648
Epoch 17/35
21/21 - 0s - 15ms/step - accuracy: 0.8448 - loss: 0.4351
Epoch 18/35
21/21 - 0s - 16ms/step - accuracy: 0.8482 - loss: 0.4269
Epoch 19/35
21/21 - 0s - 18ms/step - accuracy: 0.8566 - loss: 0.4054
Epoch 20/35
21/21 - 0s - 14ms/step - accuracy: 0.8619 - loss: 0.3861
Epoch 21/35
21/21 - 0s - 14ms/step - accuracy: 0.8684 - loss: 0.3754
Epoch 22/35
21/21 - 0s - 14ms/step - accuracy: 0.8707 - loss: 0.3660
Epoch 23/35
21/21 - 0s - 13ms/step - accuracy: 0.8781 - loss: 0.3480
Epoch 24/35
21/21 - 0s - 13ms/step - accuracy: 0.8818 - loss: 0.3346
Epoch 25/35
21/21 - 0s - 13ms/step - accuracy: 0.8833 - loss: 0.3308
Epoch 26/35
21/21 - 0s - 13ms/step - accuracy: 0.8899 - loss: 0.3188
Epoch 27/35
21/21 - 0s - 13ms/step - accuracy: 0.8930 - loss: 0.3068
Epoch 28/35
21/21 - 0s - 13ms/step - accuracy: 0.8946 - loss: 0.3014
Epoch 29/35
21/21 - 0s - 13ms/step - accuracy: 0.9006 - loss: 0.2868
Epoch 30/35
21/21 - 0s - 15ms/step - accuracy: 0.9019 - loss: 0.2805
Epoch 31/35
21/21 - 0s - 13ms/step - accuracy: 0.9035 - loss: 0.2788
Epoch 32/35
21/21 - 0s - 14ms/step - accuracy: 0.9025 - loss: 0.2809
Epoch 33/35
21/21 - 0s - 14ms/step - accuracy: 0.9053 - loss: 0.2710
Epoch 34/35
21/21 - 0s - 13ms/step - accuracy: 0.9070 - loss: 0.2655
Epoch 35/35
21/21 - 0s - 15ms/step - accuracy: 0.9117 - loss: 0.2555
6/6 - 0s - 13ms/step
Epoch 1/35

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 1s - 32ms/step - accuracy: 0.5052 - loss: 1.6640
Epoch 2/35
21/21 - 0s - 12ms/step - accuracy: 0.6535 - loss: 1.0219
Epoch 3/35
21/21 - 0s - 12ms/step - accuracy: 0.6887 - loss: 0.9172
Epoch 4/35
21/21 - 0s - 13ms/step - accuracy: 0.7129 - loss: 0.8528
Epoch 5/35
21/21 - 0s - 13ms/step - accuracy: 0.7322 - loss: 0.7988
Epoch 6/35
21/21 - 0s - 13ms/step - accuracy: 0.7422 - loss: 0.7578
Epoch 7/35
21/21 - 0s - 16ms/step - accuracy: 0.7545 - loss: 0.7218
Epoch 8/35
21/21 - 0s - 15ms/step - accuracy: 0.7625 - loss: 0.6923
Epoch 9/35
21/21 - 0s - 15ms/step - accuracy: 0.7729 - loss: 0.6632
Epoch 10/35
21/21 - 0s - 13ms/step - accuracy: 0.7826 - loss: 0.6340
Epoch 11/35
21/21 - 0s - 13ms/step - accuracy: 0.7950 - loss: 0.6023
Epoch 12/35
21/21 - 0s - 17ms/step - accuracy: 0.8010 - loss: 0.5714
Epoch 13/35
21/21 - 0s - 14ms/step - accuracy: 0.8140 - loss: 0.5398
Epoch 14/35
21/21 - 0s - 15ms/step - accuracy: 0.8170 - loss: 0.5195
Epoch 15/35
21/21 - 0s - 17ms/step - accuracy: 0.8235 - loss: 0.4912
Epoch 16/35
21/21 - 0s - 15ms/step - accuracy: 0.8325 - loss: 0.4739
Epoch 17/35
21/21 - 0s - 14ms/step - accuracy: 0.8383 - loss: 0.4572
Epoch 18/35
21/21 - 0s - 13ms/step - accuracy: 0.8439 - loss: 0.4351
Epoch 19/35
21/21 - 0s - 13ms/step - accuracy: 0.8474 - loss: 0.4204
Epoch 20/35
21/21 - 0s - 13ms/step - accuracy: 0.8554 - loss: 0.4094
Epoch 21/35
21/21 - 0s - 13ms/step - accuracy: 0.8577 - loss: 0.3938
Epoch 22/35
21/21 - 0s - 13ms/step - accuracy: 0.8622 - loss: 0.3821
Epoch 23/35
21/21 - 0s - 13ms/step - accuracy: 0.8646 - loss: 0.3735
Epoch 24/35
21/21 - 0s - 13ms/step - accuracy: 0.8691 - loss: 0.3621
Epoch 25/35
21/21 - 0s - 13ms/step - accuracy: 0.8712 - loss: 0.3572
Epoch 26/35
21/21 - 0s - 13ms/step - accuracy: 0.8767 - loss: 0.3471
Epoch 27/35
21/21 - 0s - 13ms/step - accuracy: 0.8760 - loss: 0.3473
Epoch 28/35
21/21 - 0s - 13ms/step - accuracy: 0.8813 - loss: 0.3348
Epoch 29/35
21/21 - 0s - 13ms/step - accuracy: 0.8879 - loss: 0.3161
Epoch 30/35
21/21 - 0s - 13ms/step - accuracy: 0.8916 - loss: 0.3118
Epoch 31/35
21/21 - 0s - 14ms/step - accuracy: 0.8895 - loss: 0.3148
Epoch 32/35
21/21 - 0s - 15ms/step - accuracy: 0.8922 - loss: 0.3014
Epoch 33/35
21/21 - 0s - 15ms/step - accuracy: 0.8948 - loss: 0.2980
Epoch 34/35
21/21 - 0s - 18ms/step - accuracy: 0.8940 - loss: 0.3016
Epoch 35/35
21/21 - 0s - 14ms/step - accuracy: 0.8993 - loss: 0.2851
6/6 - 0s - 12ms/step
Epoch 1/35

/opt/anaconda3/lib/python3.12/site-packages/scikeras/wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

21/21 - 1s - 31ms/step - accuracy: 0.5877 - loss: 1.3897
Epoch 2/35
21/21 - 0s - 12ms/step - accuracy: 0.6544 - loss: 0.9669
Epoch 3/35
21/21 - 0s - 12ms/step - accuracy: 0.7002 - loss: 0.8679
Epoch 4/35
21/21 - 0s - 13ms/step - accuracy: 0.7177 - loss: 0.8089
Epoch 5/35
21/21 - 0s - 14ms/step - accuracy: 0.7365 - loss: 0.7672
Epoch 6/35
21/21 - 0s - 14ms/step - accuracy: 0.7438 - loss: 0.7363
Epoch 7/35
21/21 - 0s - 14ms/step - accuracy: 0.7552 - loss: 0.7046
Epoch 8/35
21/21 - 0s - 14ms/step - accuracy: 0.7665 - loss: 0.6745
Epoch 9/35
21/21 - 0s - 15ms/step - accuracy: 0.7756 - loss: 0.6472
Epoch 10/35
21/21 - 0s - 17ms/step - accuracy: 0.7867 - loss: 0.6140
Epoch 11/35
21/21 - 0s - 14ms/step - accuracy: 0.7968 - loss: 0.5842
Epoch 12/35
21/21 - 0s - 14ms/step - accuracy: 0.8042 - loss: 0.5556
Epoch 13/35
21/21 - 0s - 13ms/step - accuracy: 0.8150 - loss: 0.5231
Epoch 14/35
21/21 - 0s - 12ms/step - accuracy: 0.8272 - loss: 0.4847
Epoch 15/35
21/21 - 0s - 13ms/step - accuracy: 0.8340 - loss: 0.4635
Epoch 16/35
21/21 - 0s - 13ms/step - accuracy: 0.8450 - loss: 0.4390
Epoch 17/35
21/21 - 0s - 13ms/step - accuracy: 0.8508 - loss: 0.4198
Epoch 18/35
21/21 - 0s - 13ms/step - accuracy: 0.8576 - loss: 0.3999
Epoch 19/35
21/21 - 0s - 14ms/step - accuracy: 0.8637 - loss: 0.3832
Epoch 20/35
21/21 - 1s - 26ms/step - accuracy: 0.8672 - loss: 0.3778
Epoch 21/35
21/21 - 1s - 25ms/step - accuracy: 0.8734 - loss: 0.3532
Epoch 22/35
21/21 - 0s - 17ms/step - accuracy: 0.8807 - loss: 0.3386
Epoch 23/35
21/21 - 0s - 13ms/step - accuracy: 0.8853 - loss: 0.3257
Epoch 24/35
21/21 - 0s - 13ms/step - accuracy: 0.8839 - loss: 0.3314
Epoch 25/35
21/21 - 0s - 13ms/step - accuracy: 0.8866 - loss: 0.3183
Epoch 26/35
21/21 - 0s - 12ms/step - accuracy: 0.8959 - loss: 0.2991
Epoch 27/35
21/21 - 0s - 12ms/step - accuracy: 0.8998 - loss: 0.2867
Epoch 28/35
21/21 - 0s - 13ms/step - accuracy: 0.9021 - loss: 0.2789
Epoch 29/35
21/21 - 0s - 12ms/step - accuracy: 0.9000 - loss: 0.2793
Epoch 30/35
21/21 - 0s - 12ms/step - accuracy: 0.8943 - loss: 0.2949
Epoch 31/35
21/21 - 0s - 12ms/step - accuracy: 0.9065 - loss: 0.2699
Epoch 32/35
21/21 - 0s - 12ms/step - accuracy: 0.9094 - loss: 0.2581
Epoch 33/35
21/21 - 0s - 12ms/step - accuracy: 0.9121 - loss: 0.2535
Epoch 34/35
21/21 - 0s - 12ms/step - accuracy: 0.9195 - loss: 0.2355
Epoch 35/35
21/21 - 0s - 12ms/step - accuracy: 0.9154 - loss: 0.2357
6/6 - 0s - 12ms/step
| 15        | 0.8626    | 0.367     | 672.7     | 0.6776    | 0.004976  | 35.36     | 1.453     | 2.29      | 1.349     | 0.694     | 44.81     | 0.9367    | 0.9626    |

ValueError: Input y contains NaN.

In [58]:
print("NaNs in y:", np.isnan(y).sum())  # if y is a NumPy array

NaNs in y: 0

In [62]:
# Convert y to DataFrame if needed
y_df = pd.DataFrame(y)

print("NaNs per column in y:\n", y_df.isna().sum())
print("Any NaNs in y?:", y_df.isna().any().any())
print("Data types:\n", y_df.dtypes)

NaNs per column in y:
 0    0
dtype: int64
Any NaNs in y?: False
Data types:
 0    int64
dtype: object

In [60]:
optimum = nn_opt.max['params']
learning_rate = optimum['learning_rate']

activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu', 'elu', 'exponential', LeakyReLU, 'relu']
optimum['activation'] = activationL[round(optimum['activation'])]

optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])

optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl', 'Adam']
optimizerD = {
    'Adam': Adam(learning_rate=learning_rate),
    'SGD': SGD(learning_rate=learning_rate),
    'RMSprop': RMSprop(learning_rate=learning_rate),
    'Adadelta': Adadelta(learning_rate=learning_rate),
    'Adagrad': Adagrad(learning_rate=learning_rate),
    'Adamax': Adamax(learning_rate=learning_rate),
    'Nadam': Nadam(learning_rate=learning_rate),
    'Ftrl': Ftrl(learning_rate=learning_rate)
}
optimum['optimizer'] = optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'activation': 'softsign',
 'batch_size': 460,
 'dropout': 0.7296061783380641,
 'dropout_rate': 0.19126724140656393,
 'epochs': 47,
 'kernel': 1.9444298503238986,
 'layers1': 1,
 'layers2': 2,
 'learning_rate': 0.7631771981307285,
 'neurons': 61,
 'normalization': 0.770967179954561,
 'optimizer': <keras.src.optimizers.adadelta.Adadelta at 0x387bdb890>}

# 6. Running CNN with Optimized Search Parameters

In [65]:
# Set the model with optimized hyperparameters

epochs = 47
batch_size = 460

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15

layers1 = 1
layers2 = 2
activation = 'softsign'
kernel = int(round(1.9444298503238986))  # Rounded kernel size for Conv1D
neurons = 61
normalization = 0.770967179954561
dropout = 0.7296061783380641
dropout_rate = 0.19126724140656393
optimizer = Adadelta(learning_rate=0.7631771981307285)  # Instantiate RMSprop with learning rate

model = Sequential()
model.add(Conv1D(neurons, kernel_size=kernel, activation=activation, input_shape=(timesteps, input_dim)))

if normalization > 0.5:
    model.add(BatchNormalization())

for i in range(layers1):
    model.add(Dense(neurons, activation=activation))

if dropout > 0.5:
    model.add(Dropout(dropout_rate))

for i in range(layers2):
    model.add(Dense(neurons, activation=activation))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) 

model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.summary()

Model: "sequential_150"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_150 (Conv1D)             │ (None, 14, 61)         │         1,159 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_60          │ (None, 14, 61)         │           244 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_760 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_90 (Dropout)            │ (None, 14, 61)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_761 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_762 (Dense)               │ (None, 14, 61)         │         3,782 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_150               │ (None, 7, 61)          │             0 │
│ (MaxPooling1D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_150 (Flatten)           │ (None, 427)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_763 (Dense)               │ (None, 15)             │         6,420 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,169 (74.88 KB)

 Trainable params: 19,047 (74.40 KB)

 Non-trainable params: 122 (488.00 B)

In [69]:
# Put the y_test set back into a one-hot configuration

y_train_one_hot = to_categorical(y_train, num_classes=15)

In [71]:
# Check shapes

print(f'X_train shape: {X_train.shape}')
print(f'y_train_one_hot shape: {y_train_one_hot.shape}')

X_train shape: (17212, 15, 9)
y_train_one_hot shape: (17212, 15)

In [73]:
# Compile the model with categorical_crossentropy

model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [75]:
# Fit the model to the data

model.fit(X_train, y_train_one_hot, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/47
38/38 - 1s - 23ms/step - accuracy: 0.6268 - loss: 1.3436
Epoch 2/47
38/38 - 0s - 12ms/step - accuracy: 0.6997 - loss: 0.8959
Epoch 3/47
38/38 - 0s - 12ms/step - accuracy: 0.7277 - loss: 0.8021
Epoch 4/47
38/38 - 0s - 12ms/step - accuracy: 0.7458 - loss: 0.7455
Epoch 5/47
38/38 - 0s - 12ms/step - accuracy: 0.7641 - loss: 0.6958
Epoch 6/47
38/38 - 0s - 12ms/step - accuracy: 0.7747 - loss: 0.6602
Epoch 7/47
38/38 - 0s - 12ms/step - accuracy: 0.7838 - loss: 0.6232
Epoch 8/47
38/38 - 0s - 12ms/step - accuracy: 0.7950 - loss: 0.5935
Epoch 9/47
38/38 - 0s - 12ms/step - accuracy: 0.8075 - loss: 0.5620
Epoch 10/47
38/38 - 0s - 12ms/step - accuracy: 0.8122 - loss: 0.5416
Epoch 11/47
38/38 - 0s - 12ms/step - accuracy: 0.8226 - loss: 0.5162
Epoch 12/47
38/38 - 0s - 12ms/step - accuracy: 0.8279 - loss: 0.4983
Epoch 13/47
38/38 - 0s - 12ms/step - accuracy: 0.8328 - loss: 0.4803
Epoch 14/47
38/38 - 0s - 12ms/step - accuracy: 0.8368 - loss: 0.4659
Epoch 15/47
38/38 - 0s - 12ms/step - accuracy: 0.8441 - loss: 0.4467
Epoch 16/47
38/38 - 0s - 12ms/step - accuracy: 0.8480 - loss: 0.4326
Epoch 17/47
38/38 - 0s - 12ms/step - accuracy: 0.8539 - loss: 0.4242
Epoch 18/47
38/38 - 0s - 12ms/step - accuracy: 0.8586 - loss: 0.4104
Epoch 19/47
38/38 - 0s - 12ms/step - accuracy: 0.8596 - loss: 0.3988
Epoch 20/47
38/38 - 0s - 12ms/step - accuracy: 0.8644 - loss: 0.3935
Epoch 21/47
38/38 - 0s - 12ms/step - accuracy: 0.8677 - loss: 0.3797
Epoch 22/47
38/38 - 0s - 12ms/step - accuracy: 0.8719 - loss: 0.3671
Epoch 23/47
38/38 - 0s - 12ms/step - accuracy: 0.8736 - loss: 0.3629
Epoch 24/47
38/38 - 0s - 12ms/step - accuracy: 0.8770 - loss: 0.3565
Epoch 25/47
38/38 - 0s - 12ms/step - accuracy: 0.8820 - loss: 0.3405
Epoch 26/47
38/38 - 0s - 13ms/step - accuracy: 0.8857 - loss: 0.3329
Epoch 27/47
38/38 - 0s - 12ms/step - accuracy: 0.8865 - loss: 0.3268
Epoch 28/47
38/38 - 0s - 12ms/step - accuracy: 0.8918 - loss: 0.3120
Epoch 29/47
38/38 - 0s - 12ms/step - accuracy: 0.8934 - loss: 0.3073
Epoch 30/47
38/38 - 0s - 12ms/step - accuracy: 0.8962 - loss: 0.3017
Epoch 31/47
38/38 - 0s - 12ms/step - accuracy: 0.8986 - loss: 0.2976
Epoch 32/47
38/38 - 0s - 12ms/step - accuracy: 0.9037 - loss: 0.2854
Epoch 33/47
38/38 - 0s - 12ms/step - accuracy: 0.9069 - loss: 0.2788
Epoch 34/47
38/38 - 0s - 12ms/step - accuracy: 0.9018 - loss: 0.2857
Epoch 35/47
38/38 - 0s - 12ms/step - accuracy: 0.9056 - loss: 0.2691
Epoch 36/47
38/38 - 0s - 12ms/step - accuracy: 0.9097 - loss: 0.2579
Epoch 37/47
38/38 - 0s - 12ms/step - accuracy: 0.9127 - loss: 0.2518
Epoch 38/47
38/38 - 0s - 12ms/step - accuracy: 0.9135 - loss: 0.2586
Epoch 39/47
38/38 - 1s - 13ms/step - accuracy: 0.9176 - loss: 0.2413
Epoch 40/47
38/38 - 1s - 14ms/step - accuracy: 0.9175 - loss: 0.2448
Epoch 41/47
38/38 - 0s - 13ms/step - accuracy: 0.9191 - loss: 0.2387
Epoch 42/47
38/38 - 0s - 12ms/step - accuracy: 0.9202 - loss: 0.2337
Epoch 43/47
38/38 - 0s - 12ms/step - accuracy: 0.9219 - loss: 0.2237
Epoch 44/47
38/38 - 0s - 12ms/step - accuracy: 0.9217 - loss: 0.2298
Epoch 45/47
38/38 - 0s - 12ms/step - accuracy: 0.9240 - loss: 0.2200
Epoch 46/47
38/38 - 0s - 12ms/step - accuracy: 0.9261 - loss: 0.2195
Epoch 47/47
38/38 - 0s - 12ms/step - accuracy: 0.9257 - loss: 0.2138

# 7. Creating Confusion Matrix

In [78]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'
}

In [80]:
def confusion_matrix(y_true, y_pred, stations):
    # Check if y_true and y_pred are one-hot encoded or already class indices
    if y_true.ndim == 1:
        y_true_labels = y_true
    else:
        y_true_labels = np.argmax(y_true, axis=1)
    
    if y_pred.ndim == 1:
        y_pred_labels = y_pred
    else:
        y_pred_labels = np.argmax(y_pred, axis=1)
        
    # Map numeric labels to activity names
    y_true_series = pd.Series([stations[y] for y in y_true_labels])
    y_pred_series = pd.Series([stations[y] for y in y_pred_labels])
    
    return pd.crosstab(y_true_series, y_pred_series, rownames=['True'], colnames=['Pred'])

In [82]:
y_pred = model.predict(X_test)

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step

In [84]:
# Evaluate

print(confusion_matrix(y_test, y_pred, stations))

Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  KASSEL  \
True
BASEL        3587        60         9       6           6         3       0
BELGRADE       76       990         3       5           1         1       0
BUDAPEST       27         9       157       6           0         2       0
DEBILT          9         0         7      61           2         1       0
DUSSELDORF      5         0         0       1           8         8       0
HEATHROW       14         1         0       1           4        46       0
KASSEL          2         1         1       0           1         0       4
LJUBLJANA       8         2         0       0           0         0       0
MAASTRICHT      7         0         0       0           0         1       0
MADRID         79         3         4       1           0         2       1
MUNCHENB        8         0         0       0           0         0       0
OSLO            1         0         0       0           0         0       0
STOCKHOLM       3         0         0       0           0         0       0
VALENTIA        1         0         0       0           0         0       0

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO
True
BASEL               4           0       7         0     0
BELGRADE            7           0       9         0     0
BUDAPEST            6           0       7         0     0
DEBILT              1           0       1         0     0
DUSSELDORF          3           0       4         0     0
HEATHROW            2           0      13         0     1
KASSEL              1           0       1         0     0
LJUBLJANA          40           0      10         0     1
MAASTRICHT          0           1       0         0     0
MADRID              1           0     366         0     1
MUNCHENB            0           0       0         0     0
OSLO                0           0       0         0     4
STOCKHOLM           0           0       0         1     0
VALENTIA            0           0       0         0     0