## Complex Machine Learning Models and Keras Part 1

#### This script follows the structure below

## 1.Importing libraries
## 2.Data Wrangling
## 3.Reshape Data for the RNN Algorithm
## 4.Spliting the Data
## 5. Create a Keras Model for RNN Algorithm and Compile & Run the RNN Model
### 5.1 First Apporach
### 5.2 Second Apporach
### 5.3 Third Apporach
### 5.4 Final Apporach

# 1. Importing libraries

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout, LSTM
from keras.utils import to_categorical
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
# Creating a path for importing the climate data set

path = r'/Users/daniel/Desktop/Ordner/Data Analyst/Data Analytics Course/Data Specialization/Data Sets'

In [6]:
# Import the data set

df_weather = pd.read_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-processed.csv'),index_col = False)

df_answer = pd.read_csv(os.path.join(path, 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'),index_col = False)

# 2. Data Wrangling

In [8]:
# Show all the columns in the data set
pd.set_option('display.max_columns', 200)

# Show all the rows in the data set
pd.set_option('display.max_rows', None)

#### Dataset Weather

In [10]:
# Check for correct import 

df_weather.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,7.7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,5.4,0.83,1.0161,0.12,0.08,0,0.0,10.0,7.0,11.5,8,0.91,0.00,0,0.8,-0.3,1.6,7,0.91,1.0010,0.13,0.22,0,0.0,10.6,9.4,8.3,2.9,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.4,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,8.7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.0,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,0.20,0.10,0,0.0,6.9,1.1,10.4,8,4.0,0.98,0.9978,0.04,1.14,0,0.0,4.9,3.8,5.9,3,2.6,0.73,1.0152,7.1,7.8,4,4.5,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,3.8,0.76,1.0169,1.54,0.44,10.0,7.8,12.2,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,4.1,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,3.6,0.89,1.0161,0.18,0.66,0,0.5,8.2,7.4,11.0,8,0.93,0.08,0,1.6,0.9,2.2,7,0.98,1.0051,0.13,0.23,0,0.0,6.1,3.9,10.6,1.9,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,1.4,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,5.7,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.8,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,0.61,0.30,0,5.1,6.2,4.2,10.2,8,5.1,0.62,1.0139,0.04,0.00,0,0.0,3.4,2.8,4.9,3,2.6,0.73,1.0152,7.1,12.2,6,6.7,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,3.8,0.76,1.0169,1.54,0.71,9.5,7.0,12.0,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,3.1,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,3.1,0.95,1.0161,0.12,0.07,0,0.0,7.1,6.9,9.1,8,0.94,0.15,0,0.7,0.4,1.7,8,0.96,1.0166,0.15,0.07,0,0.1,8.4,6.1,12.2,1.3,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,1.4,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,3.6,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,1.9,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,0.20,0.30,0,0.0,5.8,4.0,8.0,8,2.3,0.69,1.0234,0.04,0.08,0,0.0,1.9,0.6,3.1,3,2.6,0.73,1.0152,7.1,10.2,8,7.5,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,3.8,0.76,1.0169,1.54,0.10,10.3,9.0,11.6,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,5.7,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,2.7,0.86,1.0161,0.12,0.02,0,0.0,6.8,3.6,8.0,7,0.91,0.00,0,-0.1,-0.9,2.0,8,0.98,1.0230,0.13,0.00,0,0.0,9.4,6.7,8.9,1.4,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,1.4,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,5.1,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,1.1,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,0.20,0.01,0,0.0,3.9,3.2,5.4,8,3.9,0.98,1.0244,0.04,0.35,0,0.0,3.0,0.4,4.9,3,2.6,0.73,1.0152,7.1,10.8,5,7.5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,3.8,0.76,1.0169,1.54,0.10,11.2,9.9,12.6,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,6.7,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,4.5,0.92,1.0161,0.12,0.62,0,0.0,7.7,6.2,11.0,7,0.94,0.17,0,0.4,-1.7,1.5,5,0.84,1.0275,0.30,0.00,0,2.1,8.9,8.9,7.2,2.9,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,1.4,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,6.2,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,1.1,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,0.65,0.96,0,5.6,1.8,-3.0,6.0,8,1.5,0.96,1.0092,0.05,0.26,0,0.0,3.7,2.9,4.9,3,2.6,0.73,1.0152,7.1,9.9,2,10.2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3.8,0.76,1.0169,1.54,0.00,11.4,10.7,12.0,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [11]:
# Check for data frame shape

df_weather.shape

(22950, 170)

In [12]:
# Check for duplicate values

duplicate_value = df_weather.duplicated()

print(f"Total duplicate value: {duplicate_value.sum()}")

Total duplicate value: 0

In [13]:
# Check the basic statistic values
df_weather.describe()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_wind_speed,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_wind_speed,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_snow_depth,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,GDANSK_cloud_cover,GDANSK_humidity,GDANSK_precipitation,GDANSK_snow_depth,GDANSK_temp_mean,GDANSK_temp_min,GDANSK_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_snow_depth,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_wind_speed,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_wind_speed,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_wind_speed,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_wind_speed,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_snow_depth,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_wind_speed,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_snow_depth,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,ROMA_cloud_cover,ROMA_wind_speed,ROMA_humidity,ROMA_pressure,ROMA_sunshine,ROMA_temp_mean,SONNBLICK_cloud_cover,SONNBLICK_wind_speed,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
count,2.295000e+04,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.00000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000
mean,1.990984e+07,6.509630,5.410763,2.120462,0.758554,1.018013,1.345244,0.222305,0.359564,4.592222,10.392471,6.317015,15.076322,4.244357,0.683002,1.017073,1.573360,0.189349,5.770780,12.659935,8.521094,17.421516,4.516383,0.671107,1.017037,1.417872,0.149238,5.416889,11.743922,7.971168,16.225569,5.455948,3.412349,0.814856,1.015293,1.138020,0.227380,4.398658,10.022754,5.875198,13.999904,5.241786,3.918022,0.757502,1.016148,1.135907,0.207578,0.170109,4.186519,10.718671,6.626824,14.754052,4.793115,0.707963,0.129617,1.485054,8.053481,4.663150,11.665163,5.304096,0.771252,1.015389,1.182957,0.166267,0.043529,4.250440,11.209394,7.305730,15.110401,2.400200,0.771186,1.016101,1.143839,0.193428,4.026928,9.138636,5.411198,13.116192,5.109237,1.419752,0.759420,1.017367,1.355344,0.377832,5.046667,10.720702,6.366423,15.619508,5.410109,4.197538,0.800047,1.016009,1.171199,0.208844,4.284170,10.147098,6.205342,14.110597,3.691460,2.233839,0.585625,1.017486,1.894844,0.120644,7.710410,14.931952,10.052318,19.812536,5.227451,0.762837,1.374096,0.262379,1.208192,4.906118,9.014540,4.751996,13.613843,5.410588,2.733556,0.733657,1.011602,1.067922,0.218228,5.657211,4.692235,6.437512,3.061041,10.297634,3.090588,2.617346,0.731188,1.015203,7.110601,15.404431,5.101046,7.128392,0.841363,1.026306,1.568325,0.476219,4.720449,-5.049882,-7.311686,-2.767651,5.170719,1.011493,1.116964,0.149542,5.056972,7.343521,4.374980,10.720227,3.85051,0.765129,1.016905,1.544676,0.185527,11.640279,7.319233,15.962784,5.723355,0.825824,1.014242,1.134490,0.414698,0.001220,3.460989,10.724257,7.901904,13.515752
std,1.813833e+05,3.443672,2.406115,0.732625,0.110699,0.006543,0.931158,0.498995,2.006231,4.310808,7.363575,6.524121,8.730759,2.689274,0.140290,0.007543,0.933023,0.509952,4.328599,8.811427,7.721044,10.031285,2.023171,0.109650,0.006254,0.874261,0.432604,4.030315,8.501127,7.478217,9.786618,2.163247,1.541611,0.098213,0.009812,0.892257,0.455877,4.083084,6.320359,5.790673,7.298353,2.237902,1.817540,0.115862,0.008530,0.877636,0.417016,1.295166,4.125114,6.790568,6.162739,7.928710,2.433263,0.305789,0.371517,5.525070,7.819785,7.431544,8.687360,2.034997,0.104123,0.010453,0.886817,0.381006,0.589519,3.992156,5.723807,5.322685,6.558114,1.188282,0.108510,0.008359,0.807578,0.383457,3.747028,6.772219,5.999503,7.966240,2.398047,0.832357,0.129023,0.007706,0.959996,0.929656,4.391513,8.258498,7.347372,9.579308,2.259805,1.927422,0.111872,0.009301,0.903829,0.440237,4.050447,6.665457,5.992980,7.760105,2.699564,1.574226,0.177192,0.007410,0.958658,0.382177,4.146869,7.419060,6.439893,8.626836,2.424283,0.124359,0.943718,0.573925,3.942367,4.468089,7.957285,7.221321,9.160389,2.329198,1.550512,0.159550,0.012082,0.962612,0.478747,12.034542,4.606306,8.240906,7.782100,9.261002,0.934629,1.448022,0.051115,0.002809,1.666990,5.939003,2.567581,3.962556,0.176930,0.042988,0.874569,0.717434,4.398295,6.837712,6.985092,6.827926,2.840534,0.026884,0.988751,0.355772,4.990732,8.038386,7.488771,9.100872,1.69488,0.173448,0.007986,1.381986,0.410645,6.374588,5.632276,7.595673,1.630313,0.071121,0.010727,0.848813,0.844943,0.049383,3.329432,3.328727,3.659393,3.477373
min,1.960010e+07,1.000000,0.000000,0.000000,0.350000,0.974700,0.010000,0.000000,-2.000000,0.000000,-18.500000,-23.300000,-14.000000,0.000000,0.230000,0.978700,0.120000,0.000000,0.000000,-17.300000,-21.000000,-14.300000,0.000000,0.240000,0.976500,0.120000,0.000000,0.000000,-16.500000,-18.100000,-13.200000,0.000000,0.000000,0.310000,0.962100,0.010000,0.000000,0.000000,-13.200000,-18.900000,-10.600000,0.000000,0.200000,0.260000,0.964700,0.000000,0.000000,0.000000,0.000000,-14.600000,-20.800000,-10.900000,0.000000,0.000000,0.000000,0.000000,-23.800000,-27.400000,-19.000000,0.000000,0.330000,0.959600,0.020000,0.000000,0.000000,0.000000,-8.900000,-13.200000,-6.200000,0.000000,0.310000,0.966400,0.120000,0.000000,0.000000,-15.800000,-19.900000,-12.900000,0.000000,0.000000,0.270000,0.972800,0.000000,0.000000,0.000000,-15.500000,-20.300000,-12.100000,0.000000,0.000000,0.290000,0.966100,0.060000,0.000000,0.000000,-14.900000,-19.300000,-12.300000,0.000000,0.000000,0.140000,0.984200,0.120000,0.000000,0.000000,-4.500000,-9.200000,-0.800000,0.000000,0.200000,0.170000,0.000000,0.000000,0.000000,-22.500000,-27.600000,-17.800000,0.000000,0.000000,0.190000,0.954500,-0.100000,0.000000,0.000000,0.000000,-22.000000,-24.900000,-20.500000,0.000000,0.000000,0.180000,0.982900,0.000000,-5.600000,0.000000,0.000000,0.070000,0.669800,-0.120000,0.000000,0.000000,-31.800000,-34.300000,-31.200000,-99.000000,-0.099000,0.020000,0.000000,-1.700000,-23.900000,-25.500000,-22.100000,0.00000,0.000000,0.965700,0.000000,0.000000,-12.600000,-18.500000,-10.700000,0.000000,0.380000,0.955100,0.020000,0.000000,0.000000,0.000000,-3.500000,-7.300000,-1.500000
25%,1.975092e+07,4.000000,4.000000,2.100000,0.680000,1.015800,0.540000,0.000000,0.000000,0.400000,4.700000,1.400000,8.300000,2.000000,0.580000,1.012400,0.750000,0.000000,1.300000,5.700000,2.500000,9.500000,4.000000,0.630000,1.015000,0.640000,0.000000,1.600000,4.900000,2.100000,8.000000,4.000000,2.300000,0.760000,1.009400,0.370000,0.000000,0.500000,5.500000,1.800000,8.600000,4.000000,2.500000,0.690000,1.011800,0.370000,0.000000,0.000000,0.300000,5.700000,2.300000,8.700000,3.000000,0.720000,0.000000,0.000000,2.200000,-0.100000,4.700000,4.000000,0.700000,1.009100,0.410000,0.000000,0.000000,0.400000,6.800000,3.300000,10.200000,1.600000,0.710000,1.011700,0.430000,0.000000,0.500000,4.600000,1.600000,7.500000,3.000000,0.900000,0.660000,1.012700,0.470000,0.000000,0.300000,3.900000,0.500000,7.900000,4.000000,2.700000,0.730000,1.010400,0.390000,0.000000,0.500000,5.300000,2.000000,8.300000,1.000000,1.100000,0.440000,1.012800,1.090000,0.000000,4.700000,8.700000,5.000000,12.400000,4.000000,0.680000,0.560000,0.000000,0.000000,0.400000,2.900000,-0.300000,6.500000,4.000000,1.700000,0.620000,1.004100,0.200000,0.000000,0.000000,0.000000,0.400000,-2.100000,2.800000,3.000000,1.800000,0.730000,1.015200,7.100000,11.100000,3.000000,4.500000,0.800000,1.026300,0.850000,0.000000,0.000000,-9.800000,-12.000000,-7.400000,4.000000,1.005100,0.210000,0.000000,0.100000,1.300000,-0.700000,3.400000,2.60000,0.710000,1.013000,0.580000,0.000000,7.100000,3.225000,10.500000,5.000000,0.790000,1.009400,0.400000,0.010000,0.000000,0.500000,8.800000,6.100000,11.300000
50%,1.991060e+07,7.000000,6.000000,2.100000,0.770000,1.018000,1.130000,0.000000,0.000000,3.600000,10.700000,6.500000,15.400000,4.000000,0.680000,1.016600,1.570000,0.000000,5.700000,13.400000,9.200000,18.500000,4.000000,0.670000,1.017000,1.410000,0.000000,5.400000,11.800000,8.000000,16.400000,6.000000,3.100000,0.830000,1.015900,0.930000,0.010000,3.500000,10.200000,6.100000,14.000000,6.000000,3.600000,0.770000,1.016100,0.910000,0.010000,0.000000,3.100000,10.900000,6.900000,14.800000,5.000000,0.820000,0.000000,0.000000,8.000000,4.800000,11.600000,6.000000,0.780000,1.016300,0.950000,0.000000,0.000000,3.400000,11.200000,7.500000,14.800000,2.400000,0.770000,1.016100,1.140000,0.040000,4.000000,9.100000,5.400000,13.100000,6.000000,1.300000,0.770000,1.017200,1.150000,0.000000,4.700000,11.200000,7.000000,16.300000,6.000000,3.700000,0.810000,1.016400,0.970000,0.010000,3.300000,10.300000,6.500000,14.200000,4.000000,1.900000,0.570000,1.016700,1.890000,0.000000,8.600000,14.000000,9.400000,18.800000,6.000000,0.780000,1.180000,0.010000,0.000000,4.000000,9.400000,5.000000,14.100000,6.000000,2.400000,0.760000,1.012100,0.800000,0.000000,0.000000,4.000000,6.400000,3.000000,10.200000,3.000000,2.600000,0.730000,1.015200,7.100000,15.400000,6.000000,5.900000,0.910000,1.031500,1.460000,0.120000,4.000000,-4.700000,-6.800000,-2.600000,5.000000,1.012100,0.850000,0.000000,3.900000,7.000000,4.200000,10.200000,3.60000,0.800000,1.016900,1.330000,0.000000,11.600000,7.400000,15.900000,6.000000,0.820000,1.014200,0.970000,0.280000,0.000000,3.400000,10.700000,7.900000,13.500000
75%,2.007021e+07,9.000000,7.000000,2.100000,0.840000,1.020100,2.070000,0.220000,0.000000,7.900000,16.200000,11.500000,21.900000,7.000000,0.790000,1.021400,2.360000,0.100000,9.500000,19.800000,14.800000,25.600000,6.000000,0.710000,1.018300,2.050000,0.080000,8.400000,18.600000,14.100000,24.300000,7.000000,4.100000,0.890000,1.021800,1.760000,0.250000,7.300000,14.900000,10.300000,19.400000,7.000000,5.000000,0.840000,1.021100,1.770000,0.240000,0.000000,7.100000,15.900000,11.400000,20.700000,7.000000,0.890000,0.080000,0.000000,14.600000,10.500000,18.800000,7.000000,0.850000,1.022500,1.840000,0.160000,0.000000,7.100000,15.800000,11.500000,20.000000,2.800000,0.850000,1.020800,1.630000,0.190000,6.100000,13.975000,9.700000,18.800000,7.000000,1.900000,0.860000,1.021800,2.160000,0.240000,8.600000,17.400000,12.400000,23.500000,7.000000,5.100000,0.880000,1.022100,1.800000,0.220000,7.200000,15.200000,10.900000,19.875000,6.000000,2.800000,0.730000,1.021600,2.780000,0.010000,11.000000,21.200000,15.400000,27.200000,7.000000,0.860000,2.090000,0.270000,0.000000,8.500000,15.300000,10.500000,20.800000,8.000000,3.600000,0.860000,1.019700,1.760000,0.200000,4.000000,8.000000,13.400000,9.600000,18.000000,3.000000,2.900000,0.730000,1.015200,7.100000,19.700000,7.000000,9.200000,0.960000,1.036700,2.170000,0.710000,8.500000,0.100000,-1.900000,2.100000,7.000000,1.019500,1.850000,0.130000,8.800000,14.100000,10.600000,18.300000,4.80000,0.870000,1.021400,2.210000,0.180000,16.500000,11.600000,21.700000,7.000000,0.870000,1.020900,1.700000,0.410000,0.000000,4.800000,13.000000,10.300000,15.700000
max,2.022103e+07,12.000000,8.000000,16.300000,1.000000,1.045200,4.560000,8.500000,49.000000,16.800000,29.200000,22.400000,38.600000,10.000000,0.990000,1.046000,3.810000,10.980000,14.300000,34.600000,27.700000,43.600000,8.000000,1.000000,1.045400,3.790000,11.540000,15.200000,33.100000,26.000000,40.100000,8.000000,12.900000,1.000000,1.046700,10.400000,6.390000,15.800000,29.700000,22.400000,37.500000,8.000000,29.500000,1.000000,1.047300,4.190000,5.740000,27.000000,16.000000,31.200000,24.900000,40.700000,8.000000,1.000000,8.130000,95.000000,27.600000,24.200000,36.000000,9.000000,1.000000,1.047700,4.020000,6.180000,22.000000,15.800000,30.900000,22.300000,40.200000,33.000000,1.000000,1.046100,3.540000,8.230000,15.500000,28.400000,21.400000,36.700000,8.000000,10.300000,1.000000,1.050400,4.300000,13.960000,15.000000,30.400000,23.800000,40.200000,8.000000,13.400000,1.000000,1.047200,10.390000,8.720000,15.500000,30.900000,23.200000,39.600000,8.000000,15.300000,0.990000,1.076000,3.730000,8.700000,14.600000,33.400000,26.200000,40.700000,8.000000,1.000000,3.730000,9.790000,50.000000,15.700000,29.500000,22.000000,37.000000,8.000000,14.100000,1.000000,1.053400,4.460000,7.280000,79.000000,24.000000,26.400000,21.700000,34.600000,8.000000,16.400000,0.990000,1.039100,13.800000,31.500000,9.000000,29.600000,1.000000,1.062000,4.620000,10.220000,15.900000,12.700000,10.400000,15.300000,9.000000,1.054300,3.540000,5.980000,17.900000,28.300000,22.800000,35.400000,13.90000,1.000000,1.045000,14.240000,6.200000,31.200000,23.500000,40.800000,8.000000,1.000000,1.046300,3.980000,90.000000,3.000000,15.800000,23.600000,19.500000,28.400000

#### Dataset Answers

In [15]:
# Check for correct import 

df_answer.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
# Check for data frame shape

df_answer.shape

(22950, 16)

In [17]:
# Check for missing values

df_answer.isnull().sum()

DATE                           0
BASEL_pleasant_weather         0
BELGRADE_pleasant_weather      0
BUDAPEST_pleasant_weather      0
DEBILT_pleasant_weather        0
DUSSELDORF_pleasant_weather    0
HEATHROW_pleasant_weather      0
KASSEL_pleasant_weather        0
LJUBLJANA_pleasant_weather     0
MAASTRICHT_pleasant_weather    0
MADRID_pleasant_weather        0
MUNCHENB_pleasant_weather      0
OSLO_pleasant_weather          0
SONNBLICK_pleasant_weather     0
STOCKHOLM_pleasant_weather     0
VALENTIA_pleasant_weather      0
dtype: int64

In [18]:
# Check for duplicate values

duplicate_value = df_answer.duplicated()

print(f"Total duplicate value: {duplicate_value.sum()}")

Total duplicate value: 0

In [19]:
# Check the basic statistic values
df_answer.describe()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
count,2.295000e+04,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.000000,22950.0,22950.000000,22950.000000
mean,1.990984e+07,0.246797,0.348235,0.323791,0.194292,0.214989,0.216078,0.164444,0.277821,0.207669,0.446492,0.207712,0.155948,0.0,0.169673,0.051155
std,1.813833e+05,0.431157,0.476421,0.467931,0.395663,0.410824,0.411577,0.370686,0.447935,0.405647,0.497140,0.405679,0.362814,0.0,0.375354,0.220318
min,1.960010e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,1.975092e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
50%,1.991060e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
75%,2.007021e+07,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
max,2.022103e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000

#### Prepare Data for Deep Learning

In [21]:
# Drop Columns from the original without enough pertinent data

df_weather_drop = df_weather.drop(columns=[col for col in df_weather.columns if col.startswith(("GDANSK", "TOURS", "ROMA"))])

In [22]:
# Check on the new dataframe

df_weather_drop.shape

(22950, 149)

In [23]:
# Trying to find out all the different measurement types for each location

# Extract location names 
locations = set([col.split('_')[0] for col in df_weather_drop.columns])

# Create a dictionary to store measurement counts for each location
measurement_counts = {location: {} for location in locations}

# Count occurrences of each measurement type for each location
for col in df_weather_drop.columns:
    parts = col.split('_') 
    location = parts[0] 
    measurement = '_'.join(parts[1:])  # Join remaining parts if there are more than two

    if measurement not in measurement_counts[location]:
        measurement_counts[location][measurement] = 1
    else:
        measurement_counts[location][measurement] += 1

# Print the measurement counts for each location
for location, measurements in measurement_counts.items():
    print(f"Location: {location}")
    for measurement, count in measurements.items():
        print(f"  - {measurement}: {count}")
    print()

Location: BASEL
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: DUSSELDORF
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MADRID
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: VALENTIA
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: SONNBLICK
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MAASTRICHT
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: DEBILT
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: OSLO
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: DATE
  - : 1

Location: STOCKHOLM
  - cloud_cover: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MUNCHENB
  - cloud_cover: 1
  - humidity: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: LJUBLJANA
  - cloud_cover: 1
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: KASSEL
  - wind_speed: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: BELGRADE
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: BUDAPEST
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

Location: MONTH
  - : 1

Location: HEATHROW
  - cloud_cover: 1
  - humidity: 1
  - pressure: 1
  - global_radiation: 1
  - precipitation: 1
  - snow_depth: 1
  - sunshine: 1
  - temp_mean: 1
  - temp_min: 1
  - temp_max: 1

__Missing Values:__ Most missing values per weather stations seems to be the snow and wind speed variable. Therefore, I am going to drop them from the data set for further analysis.

In [25]:
# Drop columns for wind_speed and snow_depth measurements since they are missing so often

# Create a list of columns to drop
cols_to_drop = [col for col in df_weather_drop.columns if col.endswith(('wind_speed', 'snow_depth'))]

# Dropping
df_weather_clean = df_weather_drop.drop(columns=cols_to_drop)

In [26]:
df_weather_clean.shape

(22950, 134)

In [27]:
# Define relationships between locations
location_pairs = {
    'KASSEL': 'LJUBLJANA',
    'STOCKHOLM': 'OSLO',
    'MUNCHENB': 'SONNBLICK'
}

# Define the desired order of measurements
measurement_order = ['cloud_cover', 'humidity', 'pressure', 'global_radiation', 
                     'precipitation', 'sunshine', 'temp_mean', 'temp_min', 'temp_max']

# Function to fill missing values and insert in correct position
def fill_missing_values(df_weather_clean, location, measurement, neighbor):
    """
    Fills missing values for a given location and measurement using data from a neighboring location.
    Inserts the new column in the correct position based on the measurement order.
    """
    source_col = f'{neighbor}_{measurement}'
    target_col = f'{location}_{measurement}'

    # Determine the correct position to insert the new column
    if measurement == measurement_order[0]:
        location_columns = [col for col in df_weather_clean.columns if col.startswith(location)]
        insert_index = df_weather_clean.columns.get_loc(location_columns[0]) if location_columns else 0
    else:
        prev_measurement = measurement_order[measurement_order.index(measurement) - 1]
        insert_index = df_weather_clean.columns.get_loc(f'{location}_{prev_measurement}') + 1

    # Insert new column with NaN values
    df_weather_clean.insert(insert_index, target_col, np.nan)

    # Fill missing values from the neighbor column
    df_weather_clean[target_col] = df_weather_clean[target_col].fillna(df_weather_clean[source_col])

    return df_weather_clean

# Apply the function to fill missing measurements
for location, neighbor in location_pairs.items():
    for measurement in measurement_order:
        if f'{location}_{measurement}' not in df_weather_clean.columns:
            df_weather_clean = fill_missing_values(df_weather_clean, location, measurement, neighbor)

# Display a summary of newly added columns
selected_columns = [col for col in df_weather_clean.columns if col.startswith(('KASSEL', 'STOCKHOLM', 'MUNCHENB'))]

# Safe output: show only first few columns and rows to avoid crashing notebook
print("Sample of newly added columns:")
print(df_weather_clean[selected_columns[:5]].head())
print("\nTotal new columns added:", len(selected_columns))

Sample of newly added columns:
   KASSEL_cloud_cover  KASSEL_humidity  KASSEL_pressure  \
0                 8.0             0.82           1.0094
1                 6.0             0.86           1.0086
2                 8.0             0.91           1.0129
3                 6.0             0.87           1.0290
4                 7.0             0.86           1.0262

   KASSEL_global_radiation  KASSEL_precipitation
0                     0.28                  0.48
1                     0.12                  0.27
2                     0.12                  0.60
3                     0.12                  0.00
4                     0.13                  0.71

Total new columns added: 27

In [28]:
df_weather_clean.shape

(22950, 137)

In [29]:
# Drop the date column from the answer set
df_answer_new = df_answer.drop(['DATE'], axis=1)

In [30]:
df_answer_new.shape

(22950, 15)

In [31]:
# Export cleaned weather data
df_weather_clean.to_csv(os.path.join(path, 'weather_clean.csv'), index=False)

In [32]:
# Drop the date column from the unscaled set

df_weather_clean = df_weather_clean.drop(['DATE', 'MONTH'], axis=1)

In [57]:
df_weather_clean.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8.0,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.0304,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,6.0,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.0292,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,8.0,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.0320,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,6.0,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.0443,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7.0,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.0430,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

# 3.Reshape Data for the RNN Algorithm

In [35]:
# Rename df's
X = df_weather_clean
y = df_answer_new

In [36]:
# Convert df's to arrays
X = np.array(X)
y = np.array(y)

In [37]:
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [38]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
# Reshaping X as a 3D object
X = X.reshape(-1,15,9)

In [40]:
X.shape

(22950, 15, 9)

In [41]:
y.shape

(22950, 15)

# 4.Spliting the Data

In [43]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

# 5. Create a Keras Model for RNN Algorithm and Compile & Run the RNN Model

## 5.1 First Approach

In [46]:
epochs = 20
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [47]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 16)             │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 15)             │           255 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,919 (7.50 KB)

 Trainable params: 1,919 (7.50 KB)

 Non-trainable params: 0 (0.00 B)

### First Run

In [49]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [50]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.1015 - loss: 9.6326 - val_accuracy: 0.0434 - val_loss: 9.1601
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 985us/step - accuracy: 0.2097 - loss: 10.5424 - val_accuracy: 0.2672 - val_loss: 9.0554
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.2780 - loss: 10.2669 - val_accuracy: 0.2696 - val_loss: 9.0659
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2762 - loss: 10.2100 - val_accuracy: 0.2720 - val_loss: 9.0965
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2774 - loss: 10.1301 - val_accuracy: 0.2583 - val_loss: 9.2271
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3233 - loss: 10.1997 - val_accuracy: 0.2555 - val_loss: 9.4027
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4122 - loss: 10.1502 - val_accuracy: 0.6330 - val_loss: 9.4625
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5061 - loss: 10.3145 - val_accuracy: 0.6384 - val_loss: 9.6272
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5659 - loss: 10.5272 - val_accuracy: 0.6410 - val_loss: 9.8119
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5780 - loss: 10.5966 - val_accuracy: 0.6417 - val_loss: 9.9668
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1000us/step - accuracy: 0.6127 - loss: 10.6904 - val_accuracy: 0.6413 - val_loss: 10.1984
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 999us/step - accuracy: 0.6227 - loss: 10.7843 - val_accuracy: 0.6422 - val_loss: 10.3018
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6305 - loss: 10.9185 - val_accuracy: 0.6422 - val_loss: 10.5729
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.6315 - loss: 10.9772 - val_accuracy: 0.6396 - val_loss: 10.8581
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6307 - loss: 11.4010 - val_accuracy: 0.6431 - val_loss: 11.0548
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6416 - loss: 11.5892 - val_accuracy: 0.6426 - val_loss: 11.1819
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6409 - loss: 11.7616 - val_accuracy: 0.6412 - val_loss: 11.3096
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6394 - loss: 11.9821 - val_accuracy: 0.6420 - val_loss: 11.5880
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6484 - loss: 11.9862 - val_accuracy: 0.6413 - val_loss: 11.7799
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6431 - loss: 12.4209 - val_accuracy: 0.6429 - val_loss: 11.9303

### Confusion Matrix

In [95]:
# Define list of stations names
stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'
}

In [97]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [99]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step
Pred        BASEL  MADRID
True
BASEL        3679       3
BELGRADE     1092       0
BUDAPEST      214       0
DEBILT         82       0
DUSSELDORF     29       0
HEATHROW       82       0
KASSEL         11       0
LJUBLJANA      60       1
MAASTRICHT      9       0
MADRID        448      10
MUNCHENB        8       0
OSLO            5       0
STOCKHOLM       4       0
VALENTIA        1       0

## 5.2 Second Approach

In [101]:
# Key parameters
epochs = 20
batch_size = 32 # --> INCREASED from 16 to 32
n_hidden = 32  # --> INCREASED from 16 to 32
learning_rate = 0.0005 # --> ADDED Learning Rate

# Shape info
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])


model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', padding='same', 
                 input_shape=(timesteps, input_dim))) # --> ADDED Convolutional Layer
model.add(MaxPooling1D(pool_size=2)) # --> ADDED Convolutional Pooling

# 2. LSTM Layer (Temporal modeling) ## --> ADDED
model.add(LSTM(n_hidden, return_sequences=False))
model.add(Dropout(0.5))

# 3. Dense Output Layer
# Use softmax for multi-class classification
model.add(Dense(n_classes, activation='sigmoid'))
# Summary
model.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 15, 64)         │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │           495 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,703 (57.43 KB)

 Trainable params: 14,703 (57.43 KB)

 Non-trainable params: 0 (0.00 B)

### Second Run

In [103]:
# Compile the model
optimizer = Adam(learning_rate=learning_rate)
model.compile(loss='categorical_crossentropy', 
              optimizer=optimizer, metrics=['accuracy'])

In [104]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1465 - loss: 10.2067 - val_accuracy: 0.1811 - val_loss: 9.2470
Epoch 2/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1324 - loss: 10.6173 - val_accuracy: 0.1826 - val_loss: 9.1003
Epoch 3/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2435 - loss: 10.5957 - val_accuracy: 0.2896 - val_loss: 8.9728
Epoch 4/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3116 - loss: 10.6936 - val_accuracy: 0.2893 - val_loss: 9.0823
Epoch 5/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3134 - loss: 10.5926 - val_accuracy: 0.3113 - val_loss: 9.1511
Epoch 6/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3044 - loss: 10.7443 - val_accuracy: 0.3048 - val_loss: 9.1778
Epoch 7/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3076 - loss: 10.6296 - val_accuracy: 0.3010 - val_loss: 9.2958
Epoch 8/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2996 - loss: 10.8951 - val_accuracy: 0.2771 - val_loss: 8.9153
Epoch 9/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3037 - loss: 10.7546 - val_accuracy: 0.2961 - val_loss: 9.0893
Epoch 10/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3048 - loss: 10.7954 - val_accuracy: 0.2968 - val_loss: 9.2679
Epoch 11/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3304 - loss: 10.9460 - val_accuracy: 0.2743 - val_loss: 8.9898
Epoch 12/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3776 - loss: 10.8423 - val_accuracy: 0.2729 - val_loss: 9.1335
Epoch 13/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4271 - loss: 10.8378 - val_accuracy: 0.6415 - val_loss: 9.1945
Epoch 14/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4765 - loss: 10.9134 - val_accuracy: 0.6492 - val_loss: 9.3133
Epoch 15/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5412 - loss: 10.9298 - val_accuracy: 0.6450 - val_loss: 9.4137
Epoch 16/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5641 - loss: 11.0195 - val_accuracy: 0.6446 - val_loss: 9.5455
Epoch 17/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5872 - loss: 11.0586 - val_accuracy: 0.6417 - val_loss: 9.6213
Epoch 18/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6089 - loss: 11.1674 - val_accuracy: 0.6429 - val_loss: 9.6616
Epoch 19/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6166 - loss: 11.4627 - val_accuracy: 0.6429 - val_loss: 9.7972
Epoch 20/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6242 - loss: 11.5435 - val_accuracy: 0.6450 - val_loss: 9.8932

In [105]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [106]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  MAASTRICHT  MADRID  \
True
BASEL        3671         1         0       4           0           0       5
BELGRADE     1073         6         3       6           2           1       1
BUDAPEST      210         0         1       1           0           0       2
DEBILT         82         0         0       0           0           0       0
DUSSELDORF     29         0         0       0           0           0       0
HEATHROW       80         0         0       1           0           0       1
KASSEL         11         0         0       0           0           0       0
LJUBLJANA      61         0         0       0           0           0       0
MAASTRICHT      8         0         0       1           0           0       0
MADRID        433         0         0       1           0           0      23
MUNCHENB        7         0         0       0           0           0       1
OSLO            5         0         0       0           0           0       0
STOCKHOLM       4         0         0       0           0           0       0
VALENTIA        0         0         0       0           0           0       1

Pred        STOCKHOLM
True
BASEL               1
BELGRADE            0
BUDAPEST            0
DEBILT              0
DUSSELDORF          0
HEATHROW            0
KASSEL              0
LJUBLJANA           0
MAASTRICHT          0
MADRID              1
MUNCHENB            0
OSLO                0
STOCKHOLM           0
VALENTIA            0

## 5.3 Third Approach

In [108]:
# Key parameters
epochs = 20
batch_size = 32
n_hidden = 64  # --> INCREASED from 32 to 64
learning_rate = 0.0005 # 

# Shape info
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])


model = Sequential()
model.add(Conv1D(filters=64, kernel_size=5, activation='relu', padding='same', # --> CHANGED Kernel Size from 3 to 5
                 input_shape=(timesteps, input_dim)))
model.add(MaxPooling1D(pool_size=2))

# 2. LSTM Layer (Temporal modeling) 
model.add(LSTM(n_hidden, return_sequences=False))
model.add(Dropout(0.5))

# 3. Dense Output Layer
# Use softmax for multi-class classification
model.add(Dense(n_classes, activation='sigmoid'))
# Summary
model.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 15, 64)         │         2,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │           975 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36,943 (144.31 KB)

 Trainable params: 36,943 (144.31 KB)

 Non-trainable params: 0 (0.00 B)

### Third Run

In [110]:
# Compile the model
optimizer = Adam(learning_rate=learning_rate)
model.compile(loss='categorical_crossentropy', 
              optimizer=optimizer, metrics=['accuracy'])

In [111]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1123 - loss: 10.6011 - val_accuracy: 0.2729 - val_loss: 8.9325
Epoch 2/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2550 - loss: 11.0685 - val_accuracy: 0.2762 - val_loss: 8.8966
Epoch 3/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2893 - loss: 11.0819 - val_accuracy: 0.2804 - val_loss: 9.0630
Epoch 4/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2894 - loss: 11.1341 - val_accuracy: 0.2768 - val_loss: 9.2639
Epoch 5/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2834 - loss: 11.3878 - val_accuracy: 0.3008 - val_loss: 9.4487
Epoch 6/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3211 - loss: 11.3319 - val_accuracy: 0.2713 - val_loss: 9.7010
Epoch 7/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4726 - loss: 11.6068 - val_accuracy: 0.6431 - val_loss: 9.7583
Epoch 8/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5927 - loss: 11.6398 - val_accuracy: 0.6438 - val_loss: 9.8359
Epoch 9/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6310 - loss: 11.7122 - val_accuracy: 0.6426 - val_loss: 10.0032
Epoch 10/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6414 - loss: 11.8749 - val_accuracy: 0.6413 - val_loss: 10.1888
Epoch 11/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6412 - loss: 11.7942 - val_accuracy: 0.6436 - val_loss: 10.3046
Epoch 12/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6519 - loss: 11.9066 - val_accuracy: 0.6431 - val_loss: 10.5851
Epoch 13/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6462 - loss: 12.2028 - val_accuracy: 0.6419 - val_loss: 10.7155
Epoch 14/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6494 - loss: 12.2516 - val_accuracy: 0.6420 - val_loss: 10.7081
Epoch 15/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6464 - loss: 12.2867 - val_accuracy: 0.6443 - val_loss: 10.8611
Epoch 16/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6351 - loss: 12.4896 - val_accuracy: 0.6413 - val_loss: 10.9817
Epoch 17/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6464 - loss: 12.5753 - val_accuracy: 0.6417 - val_loss: 11.1888
Epoch 18/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6472 - loss: 12.8764 - val_accuracy: 0.6417 - val_loss: 11.3799
Epoch 19/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6493 - loss: 12.7674 - val_accuracy: 0.6429 - val_loss: 11.4305
Epoch 20/20
538/538 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6419 - loss: 12.9399 - val_accuracy: 0.6420 - val_loss: 11.5891

In [112]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [113]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step
Pred        BASEL  BELGRADE  BUDAPEST  MADRID
True
BASEL        3678         2         0       2
BELGRADE     1088         1         0       3
BUDAPEST      214         0         0       0
DEBILT         82         0         0       0
DUSSELDORF     29         0         0       0
HEATHROW       82         0         0       0
KASSEL         11         0         0       0
LJUBLJANA      61         0         0       0
MAASTRICHT      9         0         0       0
MADRID        452         0         1       5
MUNCHENB        8         0         0       0
OSLO            5         0         0       0
STOCKHOLM       4         0         0       0
VALENTIA        1         0         0       0

## 5.4 Final Approach

In [115]:
# Key parameters
epochs = 100 # --> INCREASED from 20 to 100
batch_size = 16
n_hidden = 16  # --> DECREASED from 64 to 16
learning_rate = 0.0005 # 

# Shape info
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])


model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', padding='same', # --> CHANGED Kernel Size from 5 to 3
                 input_shape=(timesteps, input_dim)))
model.add(MaxPooling1D(pool_size=2))

# 2. LSTM Layer (Temporal modeling) 
model.add(LSTM(n_hidden, return_sequences=False))
model.add(Dropout(0.5))

# 3. Dense Output Layer
# Use softmax for multi-class classification
model.add(Dense(n_classes, activation='sigmoid'))
# Summary
model.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 15, 64)         │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 16)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 15)             │           255 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,231 (28.25 KB)

 Trainable params: 7,231 (28.25 KB)

 Non-trainable params: 0 (0.00 B)

### Final Run

In [117]:
# Compile the model
optimizer = Adam(learning_rate=learning_rate)
model.compile(loss='categorical_crossentropy', 
              optimizer=optimizer, metrics=['accuracy'])

In [118]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.0897 - loss: 9.4806 - val_accuracy: 0.0842 - val_loss: 8.4525
Epoch 2/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.1048 - loss: 9.5655 - val_accuracy: 0.0892 - val_loss: 8.3223
Epoch 3/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.1323 - loss: 9.3941 - val_accuracy: 0.0819 - val_loss: 8.4008
Epoch 4/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.2161 - loss: 9.2694 - val_accuracy: 0.3039 - val_loss: 8.4891
Epoch 5/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.2660 - loss: 9.3161 - val_accuracy: 0.3038 - val_loss: 8.6280
Epoch 6/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.2818 - loss: 9.4133 - val_accuracy: 0.3064 - val_loss: 8.5176
Epoch 7/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.2921 - loss: 9.4530 - val_accuracy: 0.3031 - val_loss: 8.6822
Epoch 8/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.2957 - loss: 9.6165 - val_accuracy: 0.2970 - val_loss: 8.9012
Epoch 9/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 0.2898 - loss: 9.8778 - val_accuracy: 0.2973 - val_loss: 9.0637
Epoch 10/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.2962 - loss: 10.0281 - val_accuracy: 0.2964 - val_loss: 9.2687
Epoch 11/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.3329 - loss: 10.2381 - val_accuracy: 0.2984 - val_loss: 9.4848
Epoch 12/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.3586 - loss: 10.4135 - val_accuracy: 0.2942 - val_loss: 9.6776
Epoch 13/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.4007 - loss: 10.6866 - val_accuracy: 0.2907 - val_loss: 9.8848
Epoch 14/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - accuracy: 0.4320 - loss: 10.8657 - val_accuracy: 0.6403 - val_loss: 10.0984
Epoch 15/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.4845 - loss: 11.0958 - val_accuracy: 0.6453 - val_loss: 10.3013
Epoch 16/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4981 - loss: 11.0686 - val_accuracy: 0.6481 - val_loss: 10.4906
Epoch 17/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.5476 - loss: 11.1450 - val_accuracy: 0.6445 - val_loss: 10.6660
Epoch 18/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.5571 - loss: 11.1420 - val_accuracy: 0.6466 - val_loss: 10.1528
Epoch 19/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.5630 - loss: 11.2622 - val_accuracy: 0.6481 - val_loss: 10.4202
Epoch 20/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.5954 - loss: 11.4839 - val_accuracy: 0.6457 - val_loss: 10.6240
Epoch 21/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.6080 - loss: 11.5452 - val_accuracy: 0.6460 - val_loss: 10.8384
Epoch 22/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.6057 - loss: 11.7199 - val_accuracy: 0.6429 - val_loss: 11.0582
Epoch 23/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.6041 - loss: 12.0759 - val_accuracy: 0.6443 - val_loss: 11.1936
Epoch 24/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.6146 - loss: 12.2422 - val_accuracy: 0.6443 - val_loss: 11.3686
Epoch 25/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.6257 - loss: 12.2761 - val_accuracy: 0.6434 - val_loss: 11.5415
Epoch 26/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.6321 - loss: 12.5517 - val_accuracy: 0.6440 - val_loss: 11.7496
Epoch 27/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.6301 - loss: 12.7234 - val_accuracy: 0.6450 - val_loss: 11.9250
Epoch 28/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.6280 - loss: 12.6320 - val_accuracy: 0.6427 - val_loss: 12.0614
Epoch 29/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 981us/step - accuracy: 0.6349 - loss: 12.7979 - val_accuracy: 0.6429 - val_loss: 12.2269
Epoch 30/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.6255 - loss: 13.0000 - val_accuracy: 0.6415 - val_loss: 12.3786
Epoch 31/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.6339 - loss: 13.1804 - val_accuracy: 0.6415 - val_loss: 12.5188
Epoch 32/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6388 - loss: 13.3641 - val_accuracy: 0.6427 - val_loss: 12.6920
Epoch 33/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6368 - loss: 13.5081 - val_accuracy: 0.6431 - val_loss: 12.8502
Epoch 34/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.6405 - loss: 13.8451 - val_accuracy: 0.6429 - val_loss: 12.9676
Epoch 35/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.6379 - loss: 13.8259 - val_accuracy: 0.6446 - val_loss: 13.1479
Epoch 36/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.6387 - loss: 14.1692 - val_accuracy: 0.6427 - val_loss: 13.2644
Epoch 37/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.6352 - loss: 14.0889 - val_accuracy: 0.6429 - val_loss: 13.3671
Epoch 38/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.6401 - loss: 13.9965 - val_accuracy: 0.6419 - val_loss: 13.4799
Epoch 39/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.6510 - loss: 14.3497 - val_accuracy: 0.6441 - val_loss: 13.6562
Epoch 40/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.6379 - loss: 14.7624 - val_accuracy: 0.6429 - val_loss: 13.8405
Epoch 41/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6497 - loss: 14.3450 - val_accuracy: 0.6429 - val_loss: 13.9669
Epoch 42/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.6440 - loss: 14.6518 - val_accuracy: 0.6426 - val_loss: 14.0903
Epoch 43/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.6420 - loss: 15.0858 - val_accuracy: 0.6415 - val_loss: 14.2052
Epoch 44/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.6423 - loss: 14.9693 - val_accuracy: 0.6410 - val_loss: 14.2905
Epoch 45/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6454 - loss: 15.1124 - val_accuracy: 0.6426 - val_loss: 14.3924
Epoch 46/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 915us/step - accuracy: 0.6434 - loss: 15.1804 - val_accuracy: 0.6422 - val_loss: 14.5739
Epoch 47/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6413 - loss: 15.6065 - val_accuracy: 0.6445 - val_loss: 14.6663
Epoch 48/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.6418 - loss: 15.2337 - val_accuracy: 0.6413 - val_loss: 14.8173
Epoch 49/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.6494 - loss: 15.4793 - val_accuracy: 0.6424 - val_loss: 14.8292
Epoch 50/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 975us/step - accuracy: 0.6487 - loss: 15.6466 - val_accuracy: 0.6420 - val_loss: 15.0691
Epoch 51/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.6441 - loss: 15.6337 - val_accuracy: 0.6434 - val_loss: 13.8028
Epoch 52/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.6482 - loss: 14.7673 - val_accuracy: 0.6420 - val_loss: 13.7994
Epoch 53/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.6431 - loss: 15.2885 - val_accuracy: 0.6427 - val_loss: 14.0077
Epoch 54/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.6437 - loss: 15.1941 - val_accuracy: 0.6436 - val_loss: 14.1075
Epoch 55/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.6427 - loss: 15.4902 - val_accuracy: 0.6426 - val_loss: 14.2901
Epoch 56/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6454 - loss: 15.4119 - val_accuracy: 0.6440 - val_loss: 14.4776
Epoch 57/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 950us/step - accuracy: 0.6457 - loss: 15.7919 - val_accuracy: 0.6427 - val_loss: 14.7213
Epoch 58/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 978us/step - accuracy: 0.6457 - loss: 16.0926 - val_accuracy: 0.6426 - val_loss: 14.8733
Epoch 59/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.6433 - loss: 15.9091 - val_accuracy: 0.6424 - val_loss: 15.0472
Epoch 60/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6500 - loss: 16.2278 - val_accuracy: 0.6434 - val_loss: 15.2029
Epoch 61/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.6451 - loss: 16.5568 - val_accuracy: 0.6415 - val_loss: 15.3078
Epoch 62/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.6461 - loss: 16.5313 - val_accuracy: 0.6422 - val_loss: 15.4567
Epoch 63/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.6404 - loss: 16.6151 - val_accuracy: 0.6434 - val_loss: 15.6381
Epoch 64/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.6403 - loss: 16.7485 - val_accuracy: 0.6429 - val_loss: 15.7237
Epoch 65/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.6461 - loss: 17.2023 - val_accuracy: 0.6431 - val_loss: 15.8885
Epoch 66/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 986us/step - accuracy: 0.6387 - loss: 17.0469 - val_accuracy: 0.6417 - val_loss: 15.9365
Epoch 67/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.6470 - loss: 17.0883 - val_accuracy: 0.6426 - val_loss: 16.1157
Epoch 68/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.6399 - loss: 17.3239 - val_accuracy: 0.6426 - val_loss: 16.2354
Epoch 69/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.6432 - loss: 17.4581 - val_accuracy: 0.6420 - val_loss: 16.3638
Epoch 70/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.6438 - loss: 17.6461 - val_accuracy: 0.6420 - val_loss: 16.5709
Epoch 71/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.6426 - loss: 17.4486 - val_accuracy: 0.6424 - val_loss: 16.6035
Epoch 72/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.6450 - loss: 17.6811 - val_accuracy: 0.6424 - val_loss: 16.6852
Epoch 73/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6431 - loss: 17.9004 - val_accuracy: 0.6422 - val_loss: 16.8643
Epoch 74/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.6418 - loss: 17.8513 - val_accuracy: 0.6417 - val_loss: 16.9979
Epoch 75/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 918us/step - accuracy: 0.6466 - loss: 17.9996 - val_accuracy: 0.6426 - val_loss: 17.1057
Epoch 76/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.6391 - loss: 18.2332 - val_accuracy: 0.6422 - val_loss: 17.1940
Epoch 77/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 910us/step - accuracy: 0.6399 - loss: 18.5428 - val_accuracy: 0.6424 - val_loss: 17.3355
Epoch 78/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 921us/step - accuracy: 0.6455 - loss: 17.9986 - val_accuracy: 0.6426 - val_loss: 17.4207
Epoch 79/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 995us/step - accuracy: 0.6464 - loss: 18.9154 - val_accuracy: 0.6415 - val_loss: 17.5617
Epoch 80/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.6504 - loss: 18.9857 - val_accuracy: 0.6422 - val_loss: 17.6898
Epoch 81/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 0.6486 - loss: 18.9731 - val_accuracy: 0.6415 - val_loss: 17.8792
Epoch 82/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.6439 - loss: 18.3936 - val_accuracy: 0.6419 - val_loss: 17.9533
Epoch 83/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 919us/step - accuracy: 0.6389 - loss: 19.1483 - val_accuracy: 0.6420 - val_loss: 18.0548
Epoch 84/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 986us/step - accuracy: 0.6471 - loss: 19.4426 - val_accuracy: 0.6422 - val_loss: 18.2098
Epoch 85/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.6421 - loss: 19.6078 - val_accuracy: 0.6419 - val_loss: 18.2295
Epoch 86/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 920us/step - accuracy: 0.6447 - loss: 19.2051 - val_accuracy: 0.6419 - val_loss: 18.3985
Epoch 87/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.6451 - loss: 19.6000 - val_accuracy: 0.6419 - val_loss: 18.4336
Epoch 88/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.6435 - loss: 19.7269 - val_accuracy: 0.6420 - val_loss: 18.5917
Epoch 89/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.6424 - loss: 19.6704 - val_accuracy: 0.6417 - val_loss: 18.6501
Epoch 90/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.6468 - loss: 19.9143 - val_accuracy: 0.6413 - val_loss: 18.8265
Epoch 91/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.6410 - loss: 20.2441 - val_accuracy: 0.6427 - val_loss: 18.9700
Epoch 92/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 929us/step - accuracy: 0.6408 - loss: 20.1190 - val_accuracy: 0.6424 - val_loss: 19.0414
Epoch 93/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.6459 - loss: 19.4379 - val_accuracy: 0.6429 - val_loss: 19.1198
Epoch 94/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.6458 - loss: 20.1721 - val_accuracy: 0.6419 - val_loss: 19.2541
Epoch 95/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6413 - loss: 20.3162 - val_accuracy: 0.6415 - val_loss: 19.3367
Epoch 96/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 930us/step - accuracy: 0.6482 - loss: 20.3492 - val_accuracy: 0.6420 - val_loss: 19.3925
Epoch 97/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.6475 - loss: 20.6989 - val_accuracy: 0.6417 - val_loss: 19.5653
Epoch 98/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.6365 - loss: 20.4861 - val_accuracy: 0.6419 - val_loss: 19.6618
Epoch 99/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 931us/step - accuracy: 0.6406 - loss: 20.7614 - val_accuracy: 0.6419 - val_loss: 19.6399
Epoch 100/100
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6442 - loss: 21.0638 - val_accuracy: 0.6417 - val_loss: 19.8618

In [119]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [120]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
Pred        BASEL  BUDAPEST  DUSSELDORF  MADRID
True
BASEL        3682         0           0       0
BELGRADE     1091         0           0       1
BUDAPEST      214         0           0       0
DEBILT         82         0           0       0
DUSSELDORF     29         0           0       0
HEATHROW       82         0           0       0
KASSEL         11         0           0       0
LJUBLJANA      61         0           0       0
MAASTRICHT      9         0           0       0
MADRID        458         0           0       0
MUNCHENB        7         0           1       0
OSLO            5         0           0       0
STOCKHOLM       3         1           0       0
VALENTIA        1         0           0       0